### ISSUE TITLE
Test OccTax 0.1.6

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_occtax#10]
Premiers tests en Vanoise sur cette version. Voici nos commentaires

- Quand on place un point sur la carte, on ne le voit pas apparaître immédiatement, ce qui peut être déroutant. On voit le point dès qu'on se déplace
- ce serait bien d'avoir une recherche de taxon similaire aux applications antérieures: filtrage par règne/groupe INPN, par statut de protection/patrimonialité et pouvoir alterner entre nom vernaculaire ou scientifique
- Quand on termine le relevé, on revient sur la page d'accueil mais le relevé ne s'y trouve pas
- Quand on clique sur un relevé en cours, ce serait bien d'avoir une page de résumé du relevé (observateur/date/localisation/especes) qui permettrait de revenir à une étape précise sans avoir à redéfiler tous les écrans: pratique si on a de nombreuses espèces
- La partie Effectifs fera partie d'une nouvelle release?

**Comment by sgrimault** [comment]
>  * Quand on place un point sur la carte, on ne le voit pas apparaître immédiatement, ce qui peut être déroutant. On voit le point dès qu'on se déplace

C'est un bug visuel à priori. À voir si il persiste en mode non debug.

> * ce serait bien d'avoir une recherche de taxon similaire aux applications antérieures: filtrage par règne/groupe INPN, par statut de protection/patrimonialité et pouvoir alterner entre nom vernaculaire ou scientifique

C'est bien prévu. Pour l'instant il y a juste la recherche simple qui est implémentée.

> * Quand on termine le relevé, on revient sur la page d'accueil mais le relevé ne s'y trouve pas

Si vous allez juste qu'au bout de la saisie, à la dernière étape actuelle, le bouton "Terminer" termine la saisie en vue d'être synchronisée ultérieurement. Elle est donc considérée comme terminée. C'est pour ça que vous ne l'a retrouvez plus dans la liste des relevés en cours. Si vous quittez la saisie en cours de route (même à la dernière étape) via le bouton "back" du terminal, la saisie est sauvegardée et est considérée comme non terminée.
Ici il manque les étapes 5 et 6 pour que le bouton "Terminer" prenne tout son sens.
 
> * Quand on clique sur un relevé en cours, ce serait bien d'avoir une page de résumé du relevé (observateur/date/localisation/espèces) qui permettrait de revenir à une étape précise sans avoir à redéfiler tous les écrans: pratique si on a de nombreuses espèces

Actuellement la pagination d'une saisie en cours ne permet pas de restaurer selon la dernière étape valide. L'idée serait de se repositionner automatiquement sur la dernière étape valide de la saisie sans devoir effectivement repasser par toutes les étapes en partant de la première.
À terme, le workflow de la saisie permettra aussi de saisir n taxons pour une position donnée. La question de pouvoir repartir sur un taxon de la saisie (et non pas forcément le dernier ajouté) n'a pas été évoquée et implique une petite refonte sur le fonctionnement actuel de la pagination.
Votre suggestion implique une étape intermédiaire (une sorte de récapitulatif de la saisie), qui liste dans les grandes lignes la saisie dans sa globalité avec possibilité de se repositionner sur une étape pour un taxon donnée.

> * La partie Effectifs fera partie d'une nouvelle release ?

Oui. L'étape 5 est en cours.

**Comment by TheoLechemia** [comment]
Pour la recherche de taxon, il serait bien d'uniformiser la recherche entre le web et le mobile.
On a déjà bien creusé la chose pour le web (rechercher dans un même champs en latin, filtre par groupeInpn et regne, trigramme etc...).
Voir: https://github.com/PnX-SI/TaxHub/blob/master/data/taxhubdb.sql#L722
et https://github.com/PnX-SI/TaxHub/blob/master/data/taxhubdb.sql#L722
Pour la protection/patromonialité, ce sont des attributs TaxHub facultatifs, donc si on le met, ils doivent être parametrable

**Comment by TheoLechemia** [comment]
Je viens de testé l'installation sur un Samsung J7. Le répertoire `Android/data/fr.geonature.occtax` n'a pas été créé (ni sur la carte SD, ni sur le téléphone). Du coup je ne peux pas mettre le fichier `settings_occtax.json`.
Testé hier sur mon tel perso et le répertoire était bien là (sur le telephone, car je n'avais pas de carte SD)
