### ISSUE TITLE
[Sync] - Désactiver la coloration

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#100]
Bonjour à tous,

J'ai depuis toujours des problèmes de synchronisation des taxons (nombre de taxon différent à chaque synchro mais jamais complète).
Du coup, je me demandais si ce ne pourrait pas être lié à la synchronisation de la coloration. J'aimerais donc la désactiver pour récupérer la liste des taxons uniquement.

Pour ça, j'ai retiré dans le setting de sync 
```
  "code_area_type": "M1",
```

et dans le setting de occtax le lien avec la couche geojson des mailles.

Malgré cela, quand je lance la synchro, sync semble toujours vouloir récupérer la coloration ("synchronisation cartographique") et je n'arrive toujours pas à avoir ma liste de taxons complète.

Auriez-vous des piste pour permettre cette désactivation ?
Pensez-vous que c'est une solution à mon problème initial ?

Merci par avance

**Comment by DonovanMaillard** [comment]
Bonjour, 

Nous sommes en train de travailler sur la récupération des taxons dans le cadre de la refonte de l'appli mobile pour une version 2 à venir. 

Le nombre de taxons récupéré n'est généralement pas lié aux colorations à priori, mais c'est un problème récurrent que beaucoup ont sans connaitre vrzaiment la raison à ce stade... A savoir que le mobile change actuellement le nombre de taxons lui-même lors de la synchro en dédoublonnant certaines infos, noms latins etc... 

On réfléchit à ce que ce travail de "préparation de la liste des taxons" se fasse de manière plus clair et coté serveur, non plus coté mobile. 

Parmis les "solutions", mettre un paramètre "page_size" assez élevé semble régler le soucis chez un certain nombre d'entre nous.

**Comment by camillemonchicourt** [comment]
Ouais on a pas mal tourné autour de ce sujet, des offset, paginations etc....
Je me demande si on n'a pas un soucis de offset comme identifié sur https://github.com/PnX-SI/gn_module_export/issues/101
A mettre à plat et creuser en effet.

**Comment by camillemonchicourt** [comment]
Et pour la coloration c'est vrai qu'il faudrait qu'un paramètre puisse la désactiver complètement.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.7.0 en ne renseignant pas le paramètre.
