### ISSUE TITLE
Passage à une seule application Occtax-mobile : gestion de la mise à jour

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_occtax#102]
Bonjour à toutes et tous, 

Comme annoncé sur les tickets dédiés, nous sommes en train de faire évoluer la solution mobile d'occtax pour passer à une unique application : il n'y aura donc plus nécessité d'installer Sync en complément d'occtax, ses fonctionnalités seront embarquées par la nouvelle application unique. 

Dans ce cadre, nous publierons dans les prochains mois une version 2.0.0 d'occtax mobile (ou des rc pour commencer). Se pose cependant la question de la migration entre la version 1.x avec sync, et la version 2.0 sans sync à coté. 

@sgrimault , est-ce qu'une version 2.0 "tout en un" pourra bien cohabiter avec une version 1.x + Sync ? 

Pour tous les autres utilisateurs : **est-ce problématique que cette migration vers une 2.0 se fasse avec une intervention manuelle, ou faut-il impérativement que cette mise à jour puisse être automatique ?** Cela consistera, pour l'utilisateur, à : 

- Synchroniser l'ensemble de ses relevés terminés
- Supprimer l'application Sync
- Supprimer l'application Occtax-mobile
- Installer la version 2.0

Naturellement les mises à jour seront de nouveau automatisées entre la version 2.0 et les versions 2.X suivantes. La question concerne uniquement la mise à jour passant de 2 applications à une seule.

A défaut, il nous faudra trouver les financements nécessaires pour développer les fonctionnalités automatisant ces manipulations (quelques jours, puisqu'il faut gérer les droits nécessaires pour qu'une application puisse en supprimer une autre notamment).

**Comment by sgrimault** [comment]
La version 2 pourra tout à fait cohabiter avec la version actuelle ("Occtax"+ "sync") ; elle aura un identifiant (`applicationId`) différent : `fr.geonature.occtax2` par exemple au lieu de `fr.geonature.occtax` pour l'actuelle.

**Comment by DonovanMaillard** [comment]
Pas de retour à ce stade, on ne prévoit donc pas de processus de mise à jour automatique entre la version 1 du mobile (sync + occtax) et la version 2 à venir à ce stade.

**Comment by camillemonchicourt** [comment]
Retour de @sgrimault sur le sujet : 

> Pour que la mise à jour puisse se faire automatiquement et sans installer manuellement la version 2.0 sur chaque appareil mobile, cela impliquerait de mettre en oeuvre un workflow qui nécessite quelques ajustements côté l'application de synchronisation pour gérer la migration comme suit :
> 
> * Corrections sur l'application de synchronisation existante pour qu'elle puisse "voir" et proposer la nouvelle version de "Occtax".
> * Avant toute mise à jour vers la v2 de "Occtax", l'application s'assure que tous les relevés prêts à être synchronisés sont envoyés.
> * L'application affiche à l'utilisateur une boîte de dialogue explicative que la v2 de "Occtax" est disponible. Si l'utilisateur confirme, l'application de synchronisation procède à l'installation de la v2 de "Occtax". Lors de l'installation, l'application de synchronisation en profite pour aller récupérer aussi le fichier de paramétrage côté GeoNature. Ainsi l'utilisateur n'aura pas à renseigner les URLs d'accès à GeoNature.
> * À ce stade, on a donc les deux versions de "Occtax" qui vont cohabiter. Il faudrait peut être changer le thème couleur de la v2 de "Occtax" (ou son icône, ou son nom, ou un peu des trois pour la distinguer) :
>   * Soit on laisse l'utilisateur faire le "ménage" tout seul en supprimant la v1 de "Occtax" et l'application de synchronisation.
>   * Soit l'application de synchronisation "détecte" que la v2 de "Occtax" est bien présente et tente une désinstallation automatique de la v1 de "Occtax" puis se désinstalle elle même (à vérifier si c'est possible pour ce dernier point)
> 
> En parallèle, il faudra faire une petite communication auprès des agents pour le passage à la v2 de "Occtax". Car il est important de signaler que tout relevé commencé mais non terminé sera perdu. Seuls les relevés terminés et prêts à être synchronisés seront effectivement envoyés à l'instance de GeoNature. Pour quand même gérer ce cas là, il faudra aussi faire des ajustements sur la v1 de "Occtax" pour pouvoir "exporter" tous les relevés (même ceux commencés). Ce dernier point pourrait rejoindre une demande d'Amandine sur la possibilité de pouvoir reprendre en modification un relevé terminé (et donc prêt à être synchronisé).
