### ISSUE TITLE
Customisation de l'application, généricité et simplification

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_occtax#103]
Actuellement, l'application embarque des répertoires et assets spécifiques aux différents parcs nationaux (image de lancement de l'application). 

A chaque release, il est donc habituel de compiler et publier plusieurs APK, et fournir plusieurs assets. 

Est-il possible de simplifier le fonctionnement actuel en ne publiant qu'une seule APK, et en supprimant ces répertoires et spécificités du code ? 

L'intérieur de l'application pourrait être customisée par une variable "color" dans la configuration à la place (déjà existant?). 

Concernant l'icone, on peut imaginer de partager une seule et même icone générique ? Ou alors, est-il possible d'avoir une icone par défaut, dont la couleur soit modifiable par la variable "color" de la configuration ?

**Comment by camillemonchicourt** [comment]
Oui on pourrait se limiter à une seule APK.

Intéressant si on peut customiser la couleur du thème, et pourquoi pas l'icône, mais pas essentiel du tout.
On peut se contenter de la version générique en vert.

**Comment by sgrimault** [comment]
On peut imaginer un pack de thème par parc national directement embarqués dans l'application, avec la possibilité à l'utilisateur de sélectionner le thème et de l'appliquer à la volée (ou de le fixer par configuration). Par contre, il ne sera pas possible de changer l'icône de l'application : Il y aura des spécificités par version d'Android et aussi selon les terminaux, en fonction des constructeurs.

**Comment by camillemonchicourt** [comment]
OK je penche pour un thème unique et une icône unique, comme le vert générique actuel

**Comment by DonovanMaillard** [comment]
Pour l'icône unique je suis assez d'accord, ça simplifierait les choses. 

En revanche, je pense que la question se pose pour l'appli en elle-même. S'il est facilement possible de configurer deux couleurs (main/secondary en remplacement du vert/orange de l'actuelle generic), en fournissant deux codes hexadécimaux par exemple, je pense que ça peut rester pertinent pour certains acteurs qui auraient la volonté de coller à leur charte grphique, dans la mesure où on vise à faciliter largement le déploiement de l'application et la rendre plus accessible pour un maximum de personnes. Personnellement j'utilise la release generic en vert en orange et je survis... mais ca peut rester un gadget intéressant si facilement faisable.

Détail pour Sébastien, à noter qu'il faut viser un fonctionnement généique et pas forcement des thèmes par Parc : il y a de plus en plus d'utilisateurs hors parcs et on ne connait pas à l'avance les différents utilisateurs de l'appli.

**Comment by sgrimault** [comment]
Actuellement, la variante par défaut de l'application est celle que vous connaissez déjà (thème vert). Donc si vous le souhaitez, je ne proposerai que cette variante lors des prochains builds de l'application, les autres seront toujours présentes pour information, à charge des parcs intéressés de lancer un build spécifique de l'application qui suit les couleurs du parc. Cette partie est documentée.

**Comment by DonovanMaillard** [comment]
A discuter, mais l'idée est aussi de ne pas conserver/embarquer toutes ces variantes si elles ne servent plus, pour épurer le dépôt en même temps qu'on passe sur une nouvelle version :)

**Comment by DonovanMaillard** [comment]
A partir de la v2.0, il n'y aura donc plus que le thème generic (en vers) qui sera publié lors des releases.

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.0.0 en supprimant les thèmes spécifiques à certains parcs nationaux, et en ne publiant plus qu'une APK générique à chaque release.
