### ISSUE TITLE
Incompatibilité - Sync 1.3.0 - GN 2.6.2 ?

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_mobile_occtax#108]
Bonjour, 

Après avoir trouvé une discussion sur le sujet : https://github.com/PnX-SI/gn_mobile_occtax/issues/97
On a aussi un problème entre un GN 2.6.2 et un OccTax-mobile qui ne se synchronisent pas malgré une supposée compatibilité : les listes de taxons ne remontent plus ? 
On est sur Android 10. 

On va donc tenter une montée de version de GN pour résoudre, et prier !

**Comment by DonovanMaillard** [comment]
A voir sur le dépot de l'application Sync si besoin de rétrocompatibilité. 

Pour ce qui concerne Occtax, les fonctions de synchronisations ont été intégrées à l'application Occtax mobile dans la version 2.x, et permet d'améliorer la lisibilité notamment entre les compatibilités d'une appli mobile unique et geonature
