### ISSUE TITLE
Test OccTax 0.1.9

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#11]
Bonjour @sgrimault 
Je suis en train de tester OccTax 0.1.9 sur les nouveaux smartphone qu'on a acheté (Samsung A50 avec Android 9).
Pas facile pour configurer le chemin des fonds carto dans la fichier de settings. Avant dans les applis Gestionnaire de fichier d'Android, on avait l'identifiant de la carte SD. Plus maintenant.
Sais tu comment récupérer le numéro de la carte SD ou quel chemin je peux mettre dans les settings. J'ai essayé avec extSdCard sans succès.
Merci.

**Comment by sgrimault** [comment]
Bonjour @Chrispnv 

Si tu as l'utilitaire `adb` à porté de main, tu pourras retrouver cette information via les commandes suivantes :

```shell
echo $EXTERNAL_STORAGE
echo $EXTERNAL_SDCARD_STORAGE
```

La première commmande doit te retourner le chemin absolu vers la mémoire interne du terminal. La seconde doit te retourner le chemin absolu vers la carte SD externe du terminal. Si elle ne retourne rien, il faudra du coup lire le fichier `/system/etc/vold.fstab` :

```shell
cat /system/etc/vold.fstab
```

Dans lequel tu vas retrouver tous les points de montage déclarés.

Pour information, l'application "OccTax" affiche dans les logs (via la commande `adb logcat`) les points de montage détectés au démarrage.

**Comment by Chrispnv** [comment]
@sgrimault 

echo $EXTERNAL_SDCARD_STORAGE me renvoie rien. Je ne trouve pas le fichier vold.fstab et je ne peux pas faire de recherche car je n'ai pas les droits admin.
Une autre idée ?

Merci.

**Comment by Chrispnv** [comment]
@sgrimault 

J'ai aussi lancé un logcat et ensuite démarrer occtax, mais les logs défilent en continu. Est ce qu'il y a des paramètres pour gérer cela ?

**Comment by Chrispnv** [comment]
@sgrimault 

C'est bon. J'avais pas copié le fichier de settings au bon endroit.

Pour trouvé le nom du point de montage de la carte SD, j'ai utilisé la commande suivante depuis adb en mode shell sur le téléphone :
df -h | grep /storage/

**Comment by gildeluermoz** [comment]
Tu ajoutes au logcat un `> /chemin/vers/meslog.log` et ça va écrire les log dans le fichier `meslog.log`. Ensuite tu peux le regarder tranquille et/ou l'envoyer à Sébastien

**Comment by Chrispnv** [comment]
Salut @gildeluermoz 

Merci pour la manip.

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Il faut toujours mettre en dur le chemin de la carte sd pour que cela fonctionne
Est-il prévu de mettre un chemin standard mnt/sdcard
Cela faciliterait grandement le déploiement futur

**Comment by sgrimault** [comment]
Oui, c'est prévu de pouvoir seulement indiquer un chemin relatif, sachant que par défaut, l'application va privilégier le choix de la carte SD externe si elle présente.
