### ISSUE TITLE
Observateur par défaut

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_mobile_occtax#110]
Bonjour à tous, 

Petite question : 
Dans les paramètres d'Occtax-mobile, il est possible de renseigner qu'un seul observateur par défaut. Or les observateurs sont parfois plusieurs sur le terrain et ce pour tout une période. Est-il possible / envisager dans les versions à venir de permettre la sélection de plusieurs utilisateurs par défaut ? 
Ça permettrait de ne pas avoir à re-saisir les multiples utilisateurs du jour pour chaque observation (ce qui peut être assez lourd..).

Apareil mobile : Samsung galaxy Note 9, Andoid 10
Version d'Occtax-mobile : 1.3.0

**Comment by camillemonchicourt** [comment]
OK dans la 2.2.0-RC0

**Comment by cen-cgeier** [comment]
Trop bien, merci pour cet adaptation !
