### ISSUE TITLE
Plusieurs configurations mobile pour un GeoNature

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/gn_mobile_occtax#117]
Étant donné que les paramètres de l'application mobile sont définies dans le fichier settings_occtax.json, on pourrait imaginer de faire un fichier différent pour chaque utilisateur d'un site ? Pour avoir sa propre liste d'observateurs, sa liste de taxons et sa configuration de carte adaptée à son site ? 
Ça implique évidemment de faire l'import manuel sur le mobile mais ça doit marcher non ? Ou est-ce que à la synchronisation il va retourner chercher le fichier de conf sur le serveur ?

**Comment by camillemonchicourt** [comment]
Sujet prévu parmi les améliorations ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/95
