### ISSUE TITLE
Etape 2 Carte - Affichage orthophoto

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#12]
Ajouter sur la carte un bouton pour switcher entre fonds topo et orthophoto.

**Comment by sgrimault** [comment]
C'est prévu d'ajouter un autre bouton pour lister et afficher les couches sur la carte (fonds, couches vectorielles, etc.)

**Comment by Chrispnv** [comment]
OK

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Toujours impossible de switcher entre les couches définies dans le fichier de settings.

**Comment by sgrimault** [comment]
Oui, c'est en cours de développement :)

**Comment by ClaireLagaye** [comment]
Fonctionnement parfait en 0.2.6
