### ISSUE TITLE
UX : Compliqué de retrouver un JDD long sur l'application mobile - Enhancement

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_mobile_occtax#120]
Retour d'un BE (Emberiza) : 
Lorsque les noms des jeux de données sont longs et qu'ils se ressemblent, il est difficile de les retrouver. 
Une amélioration pourrait être que le nom du JDD défile lorsque celui-ci est sélectionné.

**Comment by DonovanMaillard** [comment]
Je garde l'idée de côté pour un peu plus tard dans l'année. On a plusieurs améliorations ergonomiques en tête, et celle la doit être ajoutée à la liste.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.4.0.
