### ISSUE TITLE
Edition de relevé 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_mobile_occtax#124]
Lorsque la saisie est terminée, et qu'un relevé est prêt à être synchronisé, j'ai l'impression que ce n'est pas possible de revenir dessus ? 
Cela pourrait pourtant être intéressant, notamment de l'éditer pour une espèce oubliée ou une modification de dernière minute.

**Comment by DonovanMaillard** [comment]
C'est prévu et ca sera fait courant 2022 ;)  c'était déjà prévu en 2021 mais d'autres choses ont du être mises en priorité.

**Comment by Idaline** [comment]
Je me permet d'ajouter que de pouvoir visualiser les relevés saisis sur la carte serait très utile !

**Comment by DonovanMaillard** [comment]
Bonjour, 

L'idée est en effet évoquée, pour autant je ne suis pas certain que ca rentre dans le budget de l'Appel à projet sur lequel nous travaillons actuellement. Le cahier des charges est en cours pour ca, les modéles sont déjà faits... restera à trouver le budget si on ne peut pas le faire :)

**Comment by DonovanMaillard** [comment]
Du nouveau sur ces tickets : 

- Sébastien est en train de commencer les développements nécessaires pour modifier les relevés marqués "terminés". Les relevés auront un statut (en cours ou terminé), et les relevés terminés pourront repasser en cours si on clique dessus pour reprendre l'édition. 

- Un affichage sur carte est bien prévu également. 

Ces deux fonctionnalités sont financées par les parcs nationaux sur cette fin d'année, en parallèle des développements faits dans le cadre de l'Appel à Projet.

**Comment by DonovanMaillard** [comment]
@camillemonchicourt , à lier au projet PNX 2022 ;)

**Comment by camillemonchicourt** [comment]
Sujet traité ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/78
