### ISSUE TITLE
Feat : pas de zoom automatique lorsque pointeur de position

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_mobile_occtax#126]
Demande d'un BE (Tereo-EREN) 
Le pointeur de géolocalisation, quand il est sélectionné, zoome énormément sur la carte. Est-ce qu'il est possible de descendre à un zoom moins important ? Un paramètre est-il réglable ? Faut-il des développements ?

**Comment by DonovanMaillard** [comment]
Je n'en suis pas certain ca reste à vérifier. Mais est ce que le niveau de zoom atteint n'est pas celui nécessaire pour la saisie ? Si non, on peut imaginer que Le zoom automatique soit défini par ce paramètre. 

Par cohérence ca permettrait d'avoir assez de précision pour pointer manuellement ou contrôler un pointage automatique. 

A tester.

**Comment by sgrimault** [comment]
Bonjour @Adrien-Pajot,

L'ajout/l'édition du marqueur de position sur la carte est contraint par le paramètre [`maps/min_zoom_editing`](https://github.com/PnX-SI/gn_mobile_maps/blob/develop/maps/README.md#parameters-description) depuis le fichier de paramétrage de l'application :
* Pour ajouter un marqueur, il faut d'abord zoomer suffisamment sur la carte afin d'atteindre la valeur de zoom requis pour l'édition afin que le bouton d'ajout apparaisse
* Pour modifier le marqueur (pour le déplacer ou le supprimer), il suffit de faire un "toucher simple" dessus pour qu'il passe en mode édition.
Et comme on passe en mode édition, la carte va zoomer suffisamment pour atteindre le zoom requis pour l'édition. Si l'utilisateur se trouve à un niveau zoom assez faible et qu'il sélectionne le marqueur, alors on aura effectivement l'effet de zoom autour du marqueur qui sera plus prononcé, selon la valeur attendue pour le niveau de zoom minimum requis pour l'édition.
Si entre temps l'utilisateur dézoome trop pendant l'édition du marqueur au point de quitter le niveau de zoom requis pour l'édition, on quitte le mode édition du marqueur en validant la dernière position.
