### ISSUE TITLE
OccTax 0.1.9 - Etape 2 Carte - Pointage sur la carte

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#13]
Le pointeur ne s'affiche pas au clic sur l'écran. Il faut déplacer la carte pour que le pointeur apparaisse.
Attendu : Le pointeur s'affiche sur le clic sur la carte.

**Comment by sgrimault** [comment]
Corrigé dans la version 0.3.6 du module [Maps](https://github.com/PnX-SI/gn_mobile_maps).

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Cela fonctionne
