### ISSUE TITLE
Toujours pas de synchronisation correct des taxons

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#131]
**Version de l'application**
Version d'Occtax-mobile affectée par le bug : 2.0.0
Version de GeoNature utilisée : 2.9.2

**Terminal et Version Android**
Marque et modèle du terminal : Samsung Galaxy A40
Version d'Android : 11

**Description du bug et comportement attendu**
Je pensais que cette version allait corriger le problème rencontré sur la précédente au niveau de la synchronisation des taxons. **Élément bloquant pour le déploiement de l'application ! **
Ce n'est pas le cas.
J'ai retiré la coloration à la maille de 1km car j'ai beaucoup trop de données (323595 dans gn_synthese.v_color_taxon_area), la synchro est alors très/trop longue (plusieurs heures)
Sans coloration c'est alors bien plus rapide mais il ne récupère pas tout.
J'ai 9716 cd_ref distinct (pas de synonyme dans ma liste) mais seulement 6481 ont été récupérés par l'appli (alors qu'au moment de la synchro ça monte bien au dessus... d'ailleurs je ne comprend pas pourquoi la synchronisation des taxon monte à 13750...).
Et comme toujours, si je relance une synchro, le nombre de taxon change (6462 pour la deuxième synchro, 6684 pour une troisième).

La résolution de ce problème ne devait-elle pas faire partie de la prestation ?

(désolé si je suis un peu dur mais ça fait un an qu'on est bloqué par ce problème, nos agents son très demandeur de l'appli mais je ne suis pas en mesure de leur installer un outil qui contient des anomalies. Je suis un peu usé...)

**Comment by camillemonchicourt** [comment]
Ce sujet a été expliqué dans plusieurs autres tickets et n'était pas lié à Occtax-mobile mais à un soucis de pagination et d'ordonnancement des résultats de la route dans TaxHub.
Quelle version de TaxHub tu utilises ?

**Comment by camillemonchicourt** [comment]
En complément, pour clarifier certains éléments : 

- La version 2.0.0 qui vient de sortir s'est concentrée sur la première étape qu'était la fusion d'Occtax-mobile et Sync-mobile
- Il nous reste encore beaucoup de choses à faire sur les développements, mais on avance point par point, comme on peut, avec de l'analyse, des tests, des corrections, de la documentation. Toute aide ou contribution est la bienvenue
- Le soucis de la synchronisation des taxons est indépendant d'Occtax-mobile d'après nos tests et nous l'avons normalement corrigé dans TaxHub avec @TheoLechemia en janvier. Il ne devrait donc plus être présent si ton TaxHub est à jour. Tu aurais pu le contourner depuis le départ en augmentant la valeur du paramètre ``"page_size"`` en le mettant à 20.000 si ta route renvoie 13750 éléments. On l'a évoqué dans d'autres tickets. On a aussi évoqué la raison pour laquelle l'application affiche une synchronisation du nombre de taxons supérieure aux nombre de taxons dans ta liste. C'est car la route utilisée renvoie une ligne pour le nom scientifique et une pour le nom vernaculaire quand il existe.
- Pour la couleur des taxons, l'API renvoie une ligne par taxon par unité géographique. Donc forcément si tu as laissé les mailles de 1km, ça fait beaucoup trop de données à récupérer à chaque fois (et à mettre à jour) sur un territoire comme le votre. Il faut passer sur les mailles de 5km (``"code_area_type": "M5"``) ou plus, sinon cela ne pourra être que trop long, pas de miracle possible...

On passe beaucoup de temps à concevoir, analyser, tester, documenter pour que l'outil puisse servir aux autres. On y met du temps et de l'argent alors qu'au PNE on n'utilise pas encore Occtax-mobile et qu'on n'a pas d'urgence car nos anciennes applications mobiles fonctionnent.
Personne n'est payé pour répondre aux tickets des utilisateurs, mais on essaie de le faire autant que possible, en plus de nos missions.
Plusieurs structures utilisent déjà l'application depuis un moment, en production.
Certaines qui ont rencontré des soucis ont cherché à les résoudre ou alors se sont fait accompagner avec quelques heures de prestation.

Donc j'ai vraiment du mal à comprendre le ton "dur" et le fait de pouvoir être "usé" d'attendre des corrections ou évolutions d'un outil sans y contribuer d'une manière ou d'une autre.

**Comment by PNPyrenees** [comment]
Ah bon sang mais tu as raison Camille, ce n'est pas la dernière version de taxhub qui a été installé sur nos hébergements BRGM malgré le passage en GN 2.9.2, on est resté en TH 1.9.1 - Grrr 
Bon bin, je vais aller taper sur une autre porte. :)

Je reviens rapidement sur vos réactions (j'ai pas volé le p'tit coup pied dans le c.. ;) ),

Je comprends très bien l'approche itérative, et ne remet pas en cause vos activités sur le github, certainement pas.
C'est purement de l'agacement que j'ai eu hier, après avoir bataillé pour faire fonctionner l'outil je me retrouve avec le même problème qu'avant et de l'autre côté j'ai quand même une petite pression des agents de terrain. J'ai alors eu l'impression de vivre un jour sans fin... Et donc, tel le hérisson, hier, je me suis mis en boule et j'ai sorti les pics.

Pour le côté implication dans le projet, j'avais proposé à Donovan de m'inclure comme testeur. Peu en importe la raison, mais ça n'a pas été le cas, c'est comme ça, ce n'est pas grave et ne jette la faute à personne. Et quand, Camille, tu nous as informé de la sortie de la version debug, c'est vrai que c'était dans une phase de forte charge et j'étais au final pas en capacité à vous faire des retours dans les temps.

On peut en rediscuter de vive voix,
Je ferme le ticket.
