### ISSUE TITLE
Etape 5 - pas de bouton précédent

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_mobile_occtax#132]
**Type d'amélioration**
ergonomie

**Proposition**
A l'étape 5 (dénombrement), il n'y a pas de bouton "précédent", mais une croix en haut à droite. Cette croix ne redirige pas vers l'étape précédente, mais sur la suivante (bilan des dénombrement). 
Ma proposition ici https://github.com/PnX-SI/gn_mobile_occtax/issues/114#issuecomment-1080456284 permettrait de répondre à ce "problème".

**Comment by sgrimault** [comment]
C'est parce qu'on arrive automatiquement sur la page "formulaire" du dénombrement si aucun dénombrement n'a été créé. Une fois ce dernier terminé, on revient sur la page qui liste les dénombrements pour laisser à l'utilisateur d'en ajouter un nouveau.
Donc je ne vois pas très bien de l'utilité d'un bouton "Précédent" sur la page "formulaire", car en doublon du bouton "back" physique.

La page "formulaire" des dénombrements n'est pas petite (on doit scroller) et je ne suis pas sur de l'idée de "fusionner" la page qui liste les dénombrements avec le formulaire de création/édition d'un dénombrement via ce genre de composant (https://material.io/archive/guidelines/components/expansion-panels.html#), car on va perdre en lisibilité sur la liste des dénombrements présents.

L'autre possibilité serait de rajouter un panneau contextuel à la liste qui viendrait "par dessus" cette liste pour afficher le "formulaire" (cf. https://material.io/components/backdrop ou https://material.io/components/sheets-bottom). Ça donnerait l'impression de rester sur la même page. Le seule inconvénient est que ça ne s'y prête pas bien pour une liste vide (l'utilisateur a tout supprimé) ou lors de la création du premier dénombrement.

**Comment by DonovanMaillard** [comment]
On va effectivement faire en sorte d'homogénéiser les boutons suivant/valider en bas à droite des pages, les boutons retour/précédents en bas à gauche, et les outils "de configuration" (page de paramètre etc) en haut à droite. 

La question se posera aussi de certains affichages de menus déroulants, formulaires etc, pour homogénéiser et clarifier la différence entre les sélections de choix (y compris multiples comme les observateurs) et les pages de formulaires pour mieux identifier les différentes étapes de la saisie

**Comment by TheoLechemia** [comment]
> Donc je ne vois pas très bien de l'utilité d'un bouton "Précédent" sur la page "formulaire", car en doublon du bouton "back" physique.
Si j'ai mis suivant à mon "occurrence" et que je me rend compte que j'ai fait une erreur, je voudrait pouvoir cliquer sur un bouton précédent pour y retourner. Là je doit cliquer sur la croix qui m'envoie vers l'écran suivant (ce que je trouve contre-intuitif) puis recliquer sur précédent. Donc 2 étapes pour un truc qui devrait en prendre une à mon sens.

Le composant "backdrop" pourrait bien allé en effet ! Et pour la taille et le scroll, je pense qu'on peut largement baisser la taille des "input" sans que ça nuise à la lisibilité !

**Comment by DonovanMaillard** [comment]
De premières évolutions ont été mises en place dans la 2.2 dont la release est en cours, concernant le bouton "modifier". L'affichage des dénombrements évoluera au profit d'une modale dans la prochaine commande que nous sommes en train de formuler dans le cadre de l'Appel à projet OFB.

**Comment by DonovanMaillard** [comment]
Après discussion avec Camille et pour limiter les risques de mauvais affichages sur les plus petits écrans:

- Le formulaire de dénombrement ne sera pas affiché sur une modale "au dessus" de la liste de dénombrements mais restera sur une page/modale affichée en plein écran
- Le bouton sauvegardé en haut à droite sera supprimé, au profit d'un bouton "valider" en bas à droite, avec le même design que les boutons "suivant" qui permet de passer d'étapes en étapes
- une flèche "retour arrière" en haut à gauche (standard android: https://developer.android.com/guide/navigation/navigation-principles) comment sur les fenetres de sélection des observateurs et JDD, permettra d'annuler la saisie en cours.

**Comment by sgrimault** [comment]
Ok c'est noté :-)

Ce sera donc une légère refonte ergonomique.
Actuellement l'écran formulaire du dénombrement est déjà une modale pleine
écran.

**Comment by DonovanMaillard** [comment]
Oui, plus léger que prévu :) 

On a finalement un peu peur que l'affichage en modale nous pose plus de soucis que de bénéfices : mauvais affichage sur les écrans plus petits, inputs dropdown dans une modale (il se passe quoi si la liste descend sous la limite basse de la modale etc). On va donc simplement homogénéiser le positionnement des boutons, qui reste le soucis principal :) 

Bon, malgré tout au delà de ce point, il y en a quelques unes des modifications de ce type, tu devrais avoir de quoi faire quand même :)

**Comment by sgrimault** [comment]
Oui, j'avais prévu notamment que le choix des listes déroulantes ne soit
pas présentées sous forme de modale (avec le problème d'un écran principal
sous forme de modale qui peut afficher des listes elles aussi sous forme
modale...)
Le "problème" de ces listes est que les données sont chargées de manière
"tardive" à la demande afin d'éviter de devoir tout charger depuis l'écran
formulaire.
Maintenant que l'on va rester sur une approche plus "classique", ce travail
n'est plus requis pour l'instant et les listes peuvent garder le
fonctionnement actuel.

Ça pourra faire éventuellement l'objet d'une refonte plus tard.

**Comment by DonovanMaillard** [comment]
La flèche "retour arrière" du formulaire de saisie d'un dénombrement permet désormais de revenir sur la liste des dénombrements en cours de saisis. 

L'affichage du formulaire de dénombrement sur une modale pleine page est conservé à ce stade et semble être la meilleure solution. 
La proposition d'avoir le formulaire sur la même page que la liste des dénombrements saisis ou d'autres solutions proposées (backdrop etc) posent divers soucis d'affichage et de complexités en termes de comportement des utilisateurs (risque de ne pas terminer une saisie, passer en mode édition sur un dénombrement alors que la saisie d'un autre n'est pas terminée, passer en mode édition alors qu'on veut simplement voir un dénombrement terminé etc). A ce stade on est restés sur des ajustements plus simples sans entrer dans une refonte trop lourde de la navigation entre étapes de saisie.
