### ISSUE TITLE
[Occtax Mobile 2.0] Format et compatibilité des fonds de carte Online

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_mobile_occtax#135]
Bonjour à tous.

Avec le passage à la V2, y a t il eu des modifications concernant les fonds de cartes en ligne compatibles ?
En gros, est-il possible d'afficher une ortho (IGN, google, ou autre) ou faut-il toujours passer par des fonds en ligne ?

Merci

**Comment by camillemonchicourt** [comment]
Il n'y a pas de changement au niveau des fonds de carte.
Comme pour la v1, tu peux utiliser des fonds offline, ou des fonds online, ou combiner les 2.

**Comment by JeromeMaruejouls** [comment]
Ok, merci. Du coup, si j'ai bien suivi, pour les fonds en ligne, il est uniquement possible de mettre des fonds compatibles osmdroid et il n'y a pas de compatibilité avec les fonds IGN (contrairement à Geonature).

**Comment by camillemonchicourt** [comment]
OK, maintenant qu'il n'y a plus besoin de clé et de referer, cela devrait être beaucoup moins problématique.

**Comment by camillemonchicourt** [comment]
Fonds IGN en ligne disponibles dans la version 2.6.0 d'Occtax-mobile.
Avec la documentation associée - https://github.com/PnX-SI/gn_mobile_maps/tree/develop/maps
