### ISSUE TITLE
Synchro automatique risquée

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#137]
**Type d'amélioration**
Configuration

**Proposition**
Empêcher l'émission automatique des relevés en attente de synchro lors de l'ouverture de l'appli.
Nous avons constaté sur le terrain que **l'ouverture de l'application** déclenche automatiquement l'envoie des relevés saisies qui n'auraient pas encore été synchronisés. 
En plus de l'effet surprise (3 relevés en attente de synchro en fin de matinée alors qu'on en a saisie au moins 7), il y a un risque si le réseaux n'est pas fiable, ça consomme batterie (certes, pas énormément mais sur le terrain on est parfois au pourcent près...) et data.
Je pencherais vers une synchro manuelle uniquement, déclenchée par l'utilisateur lorsqu'il est dans un réseaux de confiance.

**Comment by DonovanMaillard** [comment]
Merci Ludovic, @TheoLechemia a fait remonter un autre besoin mais qui va dans le même sens : dissocier la synchro des relevés, et la synchro des données (nomenclatures, datasets etc). 

De son coté il ne veut pas télécharger les nomenclatures, dataset etc à chaque envoi des relevés. De ton coté c'est l'inverse mais le résultat sera le même, il faudra faire 2 process distincts.

**Comment by PNPyrenees** [comment]
J'ajoute pour précision qu'à l'ouverture de l'application seul les relevés sont remontés, le reste (les nomenclature, liste d’observateurs ...) ne sont pas synchronisé (tout du moins rien sur l'interface laisse penser que ces données se synchronisent).
Il y aurais donc déjà une dissociation relevés / autres données

**Comment by DonovanMaillard** [comment]
oui, et j'ai eu mon collegue au telephone à l'instant, qui me remonte un autre soucis lié. 

Au démarrage l'appli veut a tout prix faire sa synchro et bloquerait les autres fonctionnalités. S'il n'a pas de réseau suffisant, il démarre l'appli, elle cherche à synchro, ca ne marche pas, et il ne peut rien saisir... à reproduire et creuser

**Comment by camillemonchicourt** [comment]
Dans la 2.6.0, la synchro des relevés est désormais dissociée de la mise à jour des données de référence, et est lancée seulement à la demande de l'utilisateur. 
D'autant plus nécessaire, que l'on peut désormais modifier un relevé terminé.
