### ISSUE TITLE
Bloquer la rotation de la carte

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#139]
**Type d'amélioration**
Ergonomie

**Proposition**
Ne voyant pas l'intérêt de pouvoir réaliser une rotation de la carte, est-il possible de la bloquer orientée nord.
S'il devait y avoir un réel intérêt de permettre cette rotation, l'idéal serait de pouvoir l'activer ou non depuis le paramétrage de l'appli.

**Comment by DonovanMaillard** [comment]
oui, besoin remonté par les écrins également lors de nos derniers échanges. On garde dans un coin de la tête pour la prochaine commande, qui touchera aussi au module carto

**Comment by DonovanMaillard** [comment]
Depuis la version 2.3.0, 

- La rotation de la carte est désactivée par défaut
- Un paramètre est ajouté (page "paramètres" dans l'interface de l'application) pour permettre à ceux qui le souhaitent d'activer cette rotation
