### ISSUE TITLE
Etape 2 Carte - Localisation du pointeur sur la carte

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#14]
A clic sur carte le pointeur ne se localise pas où on a cliqué mais au centre de la carte. Il faut le déplacer pour le localiser au bon endroit.
Attendu : Le pointeur s'affiche là où on a cliqué sur la carte.

**Comment by sgrimault** [comment]
Le comportement actuel est que le bouton "+" ajoute directement le marqueur automatiquement centré sur la carte. Il faut ensuite le sélectionner de nouveau pour le déplacer à l'endroit souhaité en faisant un toucher long. Si on se déplace ainsi pendant la sélection, la carte va suivre automatiquement le mouvement de l'utilisateur pour accompagner le déplacement. L'avantage est que l'on peut placer rapidement un marqueur avec peu d'interactions (aucune étape intermédiaire), contrairement aux comportements possibles suivants :

L'autre comportement possible serait de passer par une étape intermédiaire lors du "clic" sur le bouton "+" et laisser l'utilisateur de placer le marqueur en "cliquant" sur la carte avec un message explicatif. Je ne suis pas sur si c'est plus simple ou plus intuitif pour l'utilisateur car le "clic" sur la carte restera de toute manière peu précis au final et il faudra du coup sélectionner à nouveau le marqueur pour le positionner à nouveau. On revient du coup à ce qui existe déjà.

Un autre comportement possible serait d'afficher un marqueur "fantôme" (semi transparent) automatiquement centré sur la carte lors du "clic" sur le bouton "+". Un message explicatif devra être affiché pour expliquer à l'utilisateur qu'il peut positionner le marqueur final en se déplaçant sur la carte ; le marqueur "fantôme" jouant alors d'aide à la saisie. Le message explicatif serait accompagné des boutons "OK" / "Valider" pour terminer la saisie, ou de l'abandonner. Ce même principe pourrait être utilisé lors de l'édition où on verrait deux marqueurs sur la carte : Le marqueur existant déjà positionné, le marqueur "fantôme" d'aide à la saisie pour fixer la nouvelle position. L'avantage est que l'on aura une saisie plus précise. L'inconvénient est que l'on rentre dans un workflow de saisie plus compliqué.

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Le marqueur se met au centre de la carte mais l'édition est simple et intuitive je trouve

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour avoir testé aussi l'application, c'est peu intuitif je trouve. Je m'attendais comme christophe a un appui long qui positionnerait d'office un pointage, sans avoir à appuyer sur le + puis placer le marqueur ensuite. 

Là pour le pointage, ca oblige à faire 2 étapes, d'abord créer un pointage, ensuite le placer... ca double les actions nécessaires et fait perdre du temps lors de la saisie à mon sens.

**Comment by DonovanMaillard** [comment]
Quelques versions, mois et saisies plus tard, le retour utilisateur reste le même de mon coté et pour mon collègue. Tout en conservant le fonctionnement actuel, on aimerait qu'un appui long crée le pointage sur la carte ou déplace le pointage existant, sans avoir à créer un point pour le déplacer et le positionner précisément. 

Est-ce que vous avez d'autres retours utilisateurs sur cette étape désormais ?

**Comment by DonovanMaillard** [comment]
Envisagé dans une révision ergonomique plus large dans le cadre du projet AAP SINP

**Comment by cen-cgeier** [comment]
Bonjour à tous,

J'ai installé Occtax-mobile en test, avant de le déployer plus largement et de le rendre utilisable par les collègues au printemps.
Config du mobile : Samsung galaxy Note 9, Andoid 10
Version d'Occtax-mobile : 1.3.0
Je sais qu'une V2 est en cours, et globalement je fais le même constat que @DonovanMaillard. 

J'ajouterais qu'il n'est pas possible de mon côté de supprimer un marqueur, une fois positionné. 
Rester appuyé sur le pointeur permet de le basculer en mode édition et de faire apparaître une poubelle en haut à droite. Sauf que relâcher le pointeur pour appuyer sur la poubelle désactive l'édition. La suppression devient alors impossible. J'ai testé de faire glisser le pointeur jusqu'à la poubelle (comme les désinstallations d'appli android), ça déplace le pointeur mais ne le supprime pas. Appuyer à la fois sur le pointeur et sur la poubelle ne fonctionne pas non plus. La seule solution que j'ai trouvé reste de "sortir" du relevé, le supprimer et d'en réaliser un autre.

**Comment by sgrimault** [comment]
Bonjour @cen-cgeier,

Juste pour clarifier et expliquer le fonctionnement actuel :
* L'utilisateur zoom suffisamment sur la carte pour que le bouton d'ajout d'un marqueur apparaisse. Cette contrainte est pilotée coté paramétrage de l'application où on peut fixer le zoom minimal requis pour poser un marqueur:
* L'utilisateur "tape" sur le bouton d'ajout pour poser un marqueur centrée sur la carte pour le niveau de zoom actuel. Le bouton d'ajout disparait alors car on n'autorise qu'un seul marqueur de position pour un relevé.
* Ensuite, l'utilisateur sélectionne le marqueur en faisant un toucher long dessus pour pouvoir le sélectionner et le déplacer à l'endroit voulu. Dès que l'utilisateur "relâche" le marqueur, celui-ci garde sa dernière position.
* L'utilisateur peut aussi sélectionner le marqueur en faisant juste un tape simple. On voit alors apparaitre une barre d'action contextuelle au marqueur de couleur foncée par dessus la barre d'action de la carte dans lequel on va retrouver le bouton "poubelle" qui permet de le supprimer. En supprimant le marqueur et si le zoom actuel permet d'en ajouter un, le bouton d'ajout d'un marqueur réapparait.

**Comment by gildeluermoz** [comment]
Je confirme que la suppression du marqueur fonctionne avec un tape simple sur le marqueur comme décrit par @sgrimault 
Android 8, galaxy S7 Occtax_mobile V1.3.1

**Comment by cen-cgeier** [comment]
Autant pour moi, j'avais pas la notion de la "tape simple" sur le marqueur pour le basculer en mode édition.. 
Effectivement, la suppression du marqueur fonctionne très bien maintenant que je le sais. 
Merci @sgrimault !

**Comment by camillemonchicourt** [comment]
Je relance ce sujet car on a souvent des retours sur la localisation du relevé dans Occtax-mobile.
Un retour d'aujourd'hui : 

> le pointage est moins bon qu'avant : il suffisait de taper ou on voulait pour déplacer le pointeur. Maintenant il faut le sélectionner (il devient bleu) et on le bouge : mais on ne voit pas bien la carte sous son doigt et quand il fait froid c'est pas top.

**Comment by DonovanMaillard** [comment]
Oui Camille, même retour de notre coté, il faudrait revenir au fonctionnement précédent sur ce point...

**Comment by DonovanMaillard** [comment]
Le comportement de positionner ou repositionner le point par un appui long a été mis en place dans la version 2.3.0 d'Occtax-mobile.

Pour les plus anciens utilisateurs de GeoNature, on retrouve donc le comportement des anciennes applications mobiles de GeoNature V1
