### ISSUE TITLE
Replacer le champ commentaire relevé

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#140]
**Type d'amélioration**
Ergonomie

**Proposition**
Il me semblerait plus logique que le champ commentaire (correspondant au commentaire du relevé) soit placé sur la première page plutôt que ce soit un bouton en haut à droite en fin de saisie.

![image](https://user-images.githubusercontent.com/85548796/162684085-12882e50-1182-4deb-bcee-db5b6b4f4318.png)

A mon sens, ce champ sert à préciser la localisation ou l'accès au point d'observation, les conditions climatiques etc.. Le placer en fin de saisie me semble apporter de la confusion car on fait un retour au niveau relevé après avoir saisie les observations (saisie infos relevés -> saisie occurrences de taxon -> saisie commentaire relevé)

**Comment by DonovanMaillard** [comment]
Totalement. Et le placer avec une icone comme ca, hors du formulaire, est à revoir aussi à mon sens :) Il était passé à travers de mon coup d'oeil celui ci :)

**Comment by PNPyrenees** [comment]
Oui, idéalement,il faudrait qu'il s'affiche comme le commentaire associé à une observation et sur la première page de saisie
![image](https://user-images.githubusercontent.com/85548796/162686626-6be50a0a-d079-490c-b830-894fe239eb8c.png)

**Comment by DonovanMaillard** [comment]
c'est ça, mais renommé "commentaire de relevé"

**Comment by DonovanMaillard** [comment]
Depuis la version 2.3.0, le champs commentaire de relevé est accessible directement dans l'étape 1, comme les autres champs de relevé 

L'icone de l'étape 6 sera remplacée dans une prochaine version par un raccourci qui permettra de modifier l'heure de fin du relevé si celle-ci est active, (mais cette info restera quand même affichée dans l'étape 1, c'est un simple raccourci car cette info n'est souvent connue qu'en fin de saisie).
