### ISSUE TITLE
Amélioration la recherche de taxon

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#141]
**Type d'amélioration**
Ergonomie

**Proposition**
Serait-il possible d'améliorer la recherche de taxon pour reprendre le fonctionnement sur OccTax-Web
ex: taper "bel per" propose "Bellis perenis"
Aujourd'hui, on est obligé de saisir le genre en entier.

**Comment by JeromeMaruejouls** [comment]
Voir ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/91

Apparemment, assez compliqué d'avoir une recherche aussi efficace en offline.

**Comment by camillemonchicourt** [comment]
Duplicate
