### ISSUE TITLE
Améliorer la page de sélection des observateurs

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#142]
**Type d'amélioration**
Ergonomie,

**Proposition**
Dès lors qu'un observateur est sélectionné, il n'est plus possible d'utiliser la fonction de recherche.
Serait-il possible de déplacer le compteur du nombre d'observateurs sélectionnés ?

![image](https://user-images.githubusercontent.com/85548796/162684928-84a14724-fa67-4d12-b511-27c898357d3b.png)

**Comment by DonovanMaillard** [comment]
On est en train de revoir globalement l'affichage de ces pages d'une manière plus globale, pour les passer sur une modale qui vient se superposer au formulaire du relevé. Et on va aussi pouvoir sélectionner et conserver plusieurs observateurs "par défaut", pour quand on fait plusieurs relevés en groupe. A voir comment on peut garder une recherche sur un affichage modale

**Comment by sgrimault** [comment]
Oui, la barre d'action contextuelle se met par dessus la barre d'action qui contient le filtre par recherche. Il faudrait donc changer se comportement (via une snackbar par exemple, pour le décompte).

**Comment by DonovanMaillard** [comment]
Fait dans la 2.4 en laissant l'outil de recherche
