### ISSUE TITLE
Amélioration affichage textes de synchro

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/gn_mobile_occtax#143]
**Type d'amélioration**
Ergonomie

**Proposition**
Améliorer l'affichage des textes affichés lors de la synchronisation pour les rendre pleinement lisible.

![image](https://user-images.githubusercontent.com/85548796/162686289-0eb92155-fb64-487a-b748-46031958f253.png)

**Comment by DonovanMaillard** [comment]
Bien vu. Commencer par supprier "Synchronisation des", puisque c'est écrit au dessus :) Et ensuite on visera comme pour les bilans des occurrences saisies, et comme on le fait en ce moment pour les noms de jeux de données : mettre en plce un défilement

**Comment by DonovanMaillard** [comment]
Fait dans la version 2.4, avec des libellés plus courts.
