### ISSUE TITLE
OccTax 0.1.9 - Etape initiale - Param jeux de données

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#15]
Dans les paramètres utilisateur est attendu le choix du jeu de données depuis une liste déroulante.
Dans le cdc (p18) il y a une valeur par défaut qui est 'Vide'. Au final, est ce le bon choix. Est ce que Geonature de chaque structure peut envoyée une valeur par défaut lors de l'installation ou la synchro de l'appli OccTax ?
Qu'en pensez vous @camillemonchicourt  @gildeluermoz  @TheoLechemia ?

**Comment by TheoLechemia** [comment]
Les JDD vont être propre à chaque utilisateur en fonction des droits qu'il ont (cf CRUVED), il faut donc une liste déroulante au niveau du relevé, ou l'utilisateur peut choisir son JDD le plus "courant" qui s'affiche en premier, sur le modèle de ce qu'il y a pour les observateurs.
Au passage la récupération du CRUVED nécessite une authentification, qui n'est pas encore développée

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Cela fonctionne, dans les paramètres, possiblilltés de choisir le jdd et l'observateur par défaut
