### ISSUE TITLE
[Etape 6] Affichage du nom vernaculaire

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_mobile_occtax#153]
**Type d'amélioration**
Sur l'étape 6 du bilan de la saisie, seul les noms latins sont affichés

**Proposition**
Afficher également le nom vernaculaire

**Comment by sgrimault** [comment]
Doublon de #113.

**Comment by TheoLechemia** [comment]
Duplicate

**Comment by DonovanMaillard** [comment]
j'ai fermé l'autre ticet qui était moins précis du coup ;)

**Comment by DonovanMaillard** [comment]
Fait dans la version 2.4
