### ISSUE TITLE
[Etape 1] Saisi d'un commentaire pour les Relevés

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_mobile_occtax#154]
**Type d'amélioration**
Actuellement il n'est possible de saisir un commentaire qu'au niveau du taxon.

**Proposition**
Proposer la possibilité de saisir un commentaire au niveau du relevé (étape 1), pour noter des infos générales, comme les conditions météorologiques ou des informations sur le lieu (et donc communes à tous les taxons qui seront saisis ensuite)

**Comment by camillemonchicourt** [comment]
Sauf erreur de ma part, il y a un commentaire global du relevé à la dernière étape, mais il n'y a pas de commentaire par taxon actuellement.

**Comment by camillemonchicourt** [comment]
Voir aussi - https://github.com/PnX-SI/gn_mobile_occtax/issues/140

**Comment by JeromeMaruejouls** [comment]
Exactement ! J'étais passé à coté de ce bouton... Donc, juste une question d'ergonomie à revoir.
Je clos ce message, le #140 résume bien le problème actuel

**Comment by DonovanMaillard** [comment]
On a bien identifié ce point de repasser le commentaire de relevé au niveau..; du relevé ;) Ca sera fait dans les prochaines révisions ergonomiques je pense, par cohérence.
