### ISSUE TITLE
Etape 1 - Bouton retour

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#16]
Cela n'a pas été mis dans la cdc (p19). 
Peut on rajouter un bouton 'Précédent' pour revenir à l'étape initiale depuis l'étape 1 ?

**Comment by sgrimault** [comment]
Je ne suis pas sur de bien comprendre : L'écran d'accueil de l'application récapitule l'état de la synchronisation et les saisies en cours. Quand on sélectionne une saisie existante (non terminée) ou que l'on créé une nouvelle saisie, on rentre dans les écrans de la saisie en elle même qui est totalement décorrélée de l'écran d'accueil. Donc la première étape de la saisie est la première étape, il n'y a rien avant :) Si on fait back à tout moment, on quitte la saisie qui est simplement sauvegardée pour être reprise plus tard.

**Comment by Chrispnv** [comment]
Effectivement. Il ne faut pas de bouton retour vers la page initiale. Par contre, un utilisateur peut faire un retour avec le bouton retour du téléphone donc sortir de la saisie et avoir une ligne relevé créé dans relevés en cours. Que fait on dans ce cas là ?
