### ISSUE TITLE
[2.2 RC] Bouton recherche lors de la sélection de plusieurs utilisateurs (par défault ou pour une obs)

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_mobile_occtax#164]
L'ajout de plusieurs utilisateurs pour une observation fonctionne correctement.

Par contre, je rencontre un problème d'ergonomie : 
- lorsque l'on veut rajouter le premier utilisateur, un bouton recherche apparait et permet de filtrer la liste
- lorsque l'on veut rajouter d'autres utilisateurs, le bouton n'est plus disponible.

Est il possible de modifier l'interface pour garder ce bouton actif ?

Merci !

**Comment by DonovanMaillard** [comment]
Bonjour, 

Ce soucis a déjà été identifié récemment en effet et est abordé sur le #142 :)
