### ISSUE TITLE
Toutes Etapes - Numéro étape

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#17]
Dans chaque étape, afficher le titre de la façon suivante
Etape x - Nom étape

**Comment by sgrimault** [comment]
Je peux rajouter une numérotation automatique ce qui donnerait ceci :
1. Observers & date
2. Pointing
3. etc.

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
