### ISSUE TITLE
Etape 2 Carte - Boutons zoom

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#18]
Ajouter des boutons zoom +/- en plus de l'action avec les doigts.

**Comment by sgrimault** [comment]
Ok :)
Par défaut le widget des boutons de zoom est moche par défaut, j'ai tendance à suivre l'approche minimaliste pour avoir le moins de boutons possibles à l'écran sachant que maintenant le pattern "pinch to zoom" est bien connu des utilisateurs (merci Google Maps).

Actuellement sur la carte on a 3 boutons :
* Le compas / rotation automatique de la carte
* GPS, centrage et tracking automatique sur la carte
* Le bouton "+" pour ajouter un marqueur

Il y aura bientôt un quatrième qui sera positionné sous le compas pour le choix des couches à afficher sur la carte.

En bas à gauche on a l'échelle qui s'affiche sur la carte. Il ne reste donc plus que le coin en haut à gauche pour ajouter le widget des boutons de zoom.

**Comment by camillemonchicourt** [comment]
Oui je suis favorable aussi au moins de boutons possibles, surtout qu'en effet le "pinch to zoom" est clairement rentré dans les habitudes.

**Comment by Chrispnv** [comment]
Il ne faut pas oublier les conditions de travail sur le terrain avec des gants notamment. Donc je milite quand même pour avoir les boutons zoom en plus.

**Comment by lpofredc** [comment]
Et un fonctionnement avec les boutons de gestion du volume (+/-), présents sur la majorité des téléphones?

**Comment by camillemonchicourt** [comment]
OK alors si il faut le zoom +-, il faudrait un paramètre pour pouvoir le masquer.

**Comment by sgrimault** [comment]
![image](https://user-images.githubusercontent.com/620816/71924757-ef1d9880-318f-11ea-81b2-702940e44227.png)
