### ISSUE TITLE
La saisie produit des données de présence (`id_nomenclature_observation_status`) de valeur `NULL`

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_mobile_occtax#180]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 1.3.0
Version de GeoNature utilisée : 2.9.2

### Terminal et Version Android

Marque et modèle du terminal : ?
Version d'Android : ?

### Description du bug et comportement attendu

Les données produite par la saisie mobile donnent des ligne de `pr_occtax.t_releves` avec des `id_nomenclature_observation_status` à `NULL` (qui sont répercutés dans la synthèse)

Il faudrait envoyer par défault la valeur correspondant à présent pour ce champs (et donner la possbilité de choisir si besoin et en option mais caché par défaut)

### Comment reproduire

Faire une saisie mobile  et verifier la valeur de `id_nomenclature_observation_status` dans les tables 
`pr_occtax.t_releves` et `gn_synthese.synthese`

ou faire cette commande sql pour avoir une vue d'ensemble des données présentant ce soucis 

```
SELECT meta_device_entry , count(*) , id_nomenclature_observation_status --
FROM pr_occtax.t_releves_occtax AS tro
JOIN pr_occtax.t_occurrences_occtax AS too
ON tro.id_releve_occtax = too.id_releve_occtax
--WHERE too.id_nomenclature_observation_status IS NULL
GROUP BY meta_device_entry, id_nomenclature_observation_status
```

**Comment by DonovanMaillard** [comment]
duplicate #66 & #146 

Le soucis est de mémoire que l'appli renvoie explicitement un NULL donc lors du POST, la base ne renseigne pas la valeur par défaut "présent" cas le champs est renseigné NULL au lieu d'être laissé réellement null 

C'est un petit détail à régler avec @sgrimault lors de la prochaine prestation qui portera sur la synchronisation...

**Comment by joelclems** [comment]
merci donovan (j'aurai du chercher dans les issues)

je crois que l'appli ne renvoie pas de champs id_nomenclature_observation_status
 et il n'y a pas de valeur par defaut pour id_nomenclature_observation_status dans la table pr_occtax.t_occurrences_occtax

**Comment by TheoLechemia** [comment]
C'est solutionné par cette PR : https://github.com/PnX-SI/GeoNature/pull/1857

**Comment by DonovanMaillard** [comment]
En effet, j'ai retenu l'inverse de ce qu'il fallait... 

pas de soucis pour le doublon, dans tous les cas solutionné en principe avec GeoNature 2.10 à paraitre, merci Théo :)

**Comment by camillemonchicourt** [comment]
En plus de l'ajout des valeurs par défaut dans la BDD, il faudrait reprendre les données anciennes dont la valeur est à NULL.

**Comment by AudreyEnGuyane** [comment]
Salut à tous,
Si l'ajout d'une valeur par défaut serait déjà bien, serait-il possible d'ajouter la saisie de ce champ sur occtax? (parmi les champs avancés?).
Exemple très concrêt: quand on recherche une espèce sur un secteur et qu'elle n'y est pas trouvé, on est dans le cas d'une donnée d'absence. 
Ce champ pourrait être assez stratégique pour la recherche d'espèces ciblées ou le suivi de la lutte contre des espèces invasives...

**Comment by camillemonchicourt** [comment]
https://github.com/PnX-SI/gn_mobile_occtax/issues/66#issuecomment-1238268033

**Comment by camillemonchicourt** [comment]
Dans la version 2.10 de GeoNature, si aucune valeur n'est poussée, il renseigne par défaut la valeur définie dans la BDD.
En complément, pour les anciennes données, lors du passage en 2.10, elles sont mises à jour avec cette même valeur par défaut.
Concernant la possibilité de renseigner ce champs lors de la saisie mobile, voir le ticket ouvert sur le sujet.
