### ISSUE TITLE
Filtres sur les taxons: limiter les rangs taxonomiques

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_mobile_occtax#181]
Bonjour à tous,
Nous allons mettre à disposition de nos agents occTax Mobile.
Bon, la biodiversité en Guyane étant quelque peu "foisonnante", nous allons commencer doucement en se limitant aux vertébrés et quelques groupes floristiques pour lesquels nous avons des compétences.
Ainsi, la liste d'espèce a été créée, est bien chargée dans l'appli et on peut saisir nos observations.
Par contre, quand on essaie de filtrer les espèces, on se retrouve avec un pack de rangs taxonomiques dont des groupes non référencés dans notre taxref (ni dans group1_inpn, ni dans group2_inpn) et encore moins dans la liste des espèces ciblées pour la saisie.
Par contre, les nôtres ont été ajoutés.
Par exemple, nous n'avons pas de "mammifères" mais des "mammifères volants" et des "mammifères non volants", mais les 3 apparaissent.
Sur quoi se base la synchro pour faire cette liste de filtres?
Merci d'avance!

**Comment by DonovanMaillard** [comment]
Bonjour, 

Une bonne question pour @sgrimault :)

**Comment by sgrimault** [comment]
Bonjour,

La constitution des filtres par espèces se fait lors de la synchronisation des données, avec notamment l'appel à la route `/api/taxref/regnewithgroupe2` coté TaxHub. Cette route liste les rangs taxonomique sur lesquels sont rattachés les taxons.

**Comment by AudreyEnGuyane** [comment]
Merci pour la précision @sgrimault!

Y aurait-il un moyen de filtrer ces regnewithgroupe2 en fonction de la liste d'espèces appelée par OccTax mobile? Mes agents vont flipper si ils voient tous les groupes apparaître...

**Comment by sgrimault** [comment]
Ça je ne sait pas :)
La synchronisation récupère effectivement tout ce que retourne l'API (TaxHub) et je ne sais pas si il est possible d'appliquer des filtres ou non.
Si coté API rien n'est prévu pour retourner une liste "filtrée", l'autre possibilité est de faire ce traitement lors de la synchronisation coté application mobile. Ça risque d'alourdir un peu plus le traitement surtout si on a beaucoup de taxons à synchroniser.

À voir avec @DonovanMaillard et @TheoLechemia ?

**Comment by DonovanMaillard** [comment]
A mon sens ce filtrage doit avoir lieu sur l'API en effet. S'il n'y a pas d'invertébrés dans les taxons retournés, en principe l'API ne devrait pas renvoyer de group2_INPN correspondant à ces espèces. Je n'ai pas ces API en tête, mais je vais creuser un peu pour intégrer ça à nos réflexions sur la synchronisation des taxons.

**Comment by AudreyEnGuyane** [comment]
L'appli fait un toilettage des taxons orphelins lors de la synchronisation. 
Peut-être pourrait-on réaliser aussi le toilettage des groupes sans références taxonomiques chargées ?
Ca éviterai de toucher à l'API...

**Comment by sgrimault** [comment]
Oui, c'est ce que je disais en parlant de traitement supplémentaire à faire coté application mobile. Après je rejoins @DonovanMaillard où idéalement tout devrait se faire coté API, l'application se contentant de récupérer ce que retourne l'API sans se poser de questions :)

**Comment by DonovanMaillard** [comment]
Oui, d'autant qu'on risque de toucher aux API pour récupérer les taxons de manière plus efficace et préparer le terrain pour récupérer les taxons en fonction des JDD dans un second temps :)

**Comment by AudreyEnGuyane** [comment]
En fait, on touche au #57 ?

**Comment by DonovanMaillard** [comment]
en effet, c'est un doublon avec le #57 , bien vu
