### ISSUE TITLE
Le champ "Techniques d'observation" liste des méthodes d'observation

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_mobile_occtax#185]
### Version de l'application
Version d'Occtax-mobile affectée par le bug : 2.3.0
Version de GeoNature utilisée : 2.9.3

### Terminal et Version Android
Marque et modèle du terminal : Glaxy A02s
Version d'Android : 11

### Description du bug et comportement attendu
Description du problème rencontré (message d’erreur, code HTTP de retour inattendu, …): Pas de bug mais le champ `Techniques d'observation` liste des méthodes d'observation (id_type = 14!)... 

### Comment reproduire
Sélectionnez n'importe quel taxon puis passez à l'étape `4-Informations` et faites dérouler la liste `techniques d'observation`.
Peut-être juste changer le libellé associé à la liste déroulante dans le formulaire `4-Informations` ?

**Comment by TheoLechemia** [comment]
Salut Audrey,
ce n'est pas un bug, mais un changement dans le standard occurrence de taxon. Le standard a renommé un champs "méthode d'obs" en "technique d'obs" (la confusion est d'autant plus grande qu'on avait déjà un champs technique d'obs dans occtax...) Dans la base les "mnémonique" sont utilisé comme des clés pour sélectionner les nomenclatures, c'est un peu comme une clé primaire, du coup on ne l'a pas changé ...
https://github.com/PnX-SI/GeoNature/issues/1329

**Comment by DonovanMaillard** [comment]
Comme dit théo, simple confusion liée à l'évolution du standard SINP. Mais les "techniques" correspondent bien aux anciennement nommées "méthodes", donc pas de soucis ici :) je ferme le ticket :)

**Comment by DonovanMaillard** [comment]
@camillemonchicourt tu l'avais tagué dans le projet PNX 2022. Tu comptais faire quelque chose de particulier sur ce point ou c'est une erreur ?

**Comment by camillemonchicourt** [comment]
Non, je sais pas, peut-être clarifier ce sujet serpent de mer, mais y a peut-être rien de plus à faire.

**Comment by DonovanMaillard** [comment]
A priori la seule chose à faire s'il faut faire quelque chose, c'est de changer la clé "METH_OBS" pour ce type de nomenclature, mais pas essentiel...
