### ISSUE TITLE
Chargement des listes d'espèces adaptées aux jeux de données

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_mobile_occtax#187]
**Type d'amélioration**
Configuration
L'installation et la synchronisation d'occtax ne permet de charger qu'une liste d'utilisateurs et une liste d'espèces.
Hors ces listes varient selon les jeux de données. Et l'accès à la saisie dans un jeu de données peut également varier d'un utilisateur à l'autre.
Pour exemple: 
- tout le monde peut saisir n'importe quelle espèce dans les données opportunistes 
- seule une dizaine de personne réalise les suivis de grande faune avec quelques champs additionnels dédiés (qui ne concerne qu'une quinzaine d'espèces)
- le grand public (avec un compte) ne pourrait saisir que dans des jeux de données de protocoles participatifs ayant une liste dédiée (esp. invasives? papillons? autres...)

**Proposition**
Lors du chargement, charger 1/ les JDD et leurs champs additionnels et 2/ les listes d'espèces associées (#41 et #122).
Question subsidiaire: comment limiter l'accès aux différents JDD selon la liste d'utilisateurs?

**Comment by camillemonchicourt** [comment]
Même chose que https://github.com/PnX-SI/gn_mobile_core/issues/41 et https://github.com/PnX-SI/gn_mobile_occtax/issues/122, non ?

**Comment by DonovanMaillard** [comment]
La liste des utilisateurs n'est pas différente selon les JDD, c'est la liste de saisie Occtax (dépendante du module) qui sert toujours. Seuls les personnes connectées ayant accès à tel ou tel JDD varient, mais ca c'est déjà fonctionnel selon qui se connecte. 

Les champs additionnels et filtrages des taxons sont déjà en discussion en effet. Je ferme pour limiter les doublons ouverts :)
