### ISSUE TITLE
Application mobile : récupération des taxons

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#188]
Bonjour,
Nous avons un GEONATURE 2.7.5, TAXHUB 1.8.1 et les applications mobiles en 1.3.0.

Nous avions précédemment des problèmes sur la remontée des taxons qui a été résolu.
Issue : http://github.com/PnX-SI/gn_mobile_occtax/issues/61
Les paramètres page_size et page_max_size n'était pas bon.

Les utilisateurs m'ont de nouveau signalé le problème. Certains espèces ne remontent pas sur les smartphones.
Exemple le faucon pélerin.
J'ai donc refait l'appel à l'api mentionnée dans l'issue 61 (https://ra-na.fr/taxhub/api/taxref/allnamebylist/100?limit=50000)
Je récupère bien le faucon pélérin.
Le paramétrage est actuellement 
page_size=10000 et page_max_size = 5
Plus que suffisant pour récupérer les 2310 espèces (23 100 lignes)

J'ai vu qu'il y a l'issue https://github.com/PnX-SI/gn_mobile_occtax/issues/81
Elle mentionne un autre problème avec les lignes de la vue gn_synthese.v_color_taxon_area
La vue à Cistude Nature contient 17699 lignes donc suffisant.

J'ai demandé à passer le paramètre page_max_size à 20 mais on ne récupère toujours pas le Faucon Pélerin.

Quel pourrais être le problème ? Y-a-til moyen de savoir ce que récupère vraiment l'application sur le smartphone ?

C'est assez embêtant pour les saisies sur le terrain.

Christian Bièche
Cistude Nature

**Comment by camillemonchicourt** [comment]
Comme évoqué dans de nombreux tickets, le soucis a été réglé dans la version 1.9.4 de TaxHub.

**Comment by christianbieche** [comment]
Très bien Camille. Par contre je ne vois pas bien pourquoi puisqu'on utilise une requête sur taxhub qui renvoie actuellement la totalité des taxons. Il y a une évolution des applications android en même temps ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

de mémoire il y avait un soucis avec l'ordre des résultats ou la mise en forme des données renvoyées, qui ont été corrigées, même si la route renvoyait tout le mobile ne récupérait pas tout. 

D'une manière générale avant de faire un retour sur un bug, il faut s'assurer qu'il est toujours présent quand tous les outils sont à jour. Cela nous évite aussi d'avoir à revenir comme ici sur des soucis réglés et dont on ne se souvient pas toujours du détail.

Par ailleurs, nous sommes en train de travailler sur la synchronisation des données d'une manière assez large, avec des rendus prévus début 2023. Il y a plusieurs tickets sur le sujet et on a on travaille sur le cahier des charges des prochains développements sur le sujet.
On prévoit notamment de ne récupérer que les données qui ont été modifiées depuis la dernière synchronisation pour gagner du volume et du temps, et de récupérer les taxons en fonction des listes associées aux jeux de données.

**Comment by camillemonchicourt** [comment]
Voici à nouveau ce qui a été expliqué dans plusieurs tickets sur le sujet.
Au niveau de TaxHub les résultats de l'API n'étaient pas ordonnés. Donc quand l'appel à la route se fait en plusieurs pages, de manière paginée, il était possible que certains taxons soient en page 1, mais aussi en page 3 et que certains taxons passent ainsi à la trappe.

La version 1.9.4 de TaxHub a corrigé la pagination de cette route, en ordonnant bien les résultats de chaque page.
