### ISSUE TITLE
OccTax 0.1.9 - Etape 2 Carte - Bouton centrage carte

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#19]
Ajouter un bouton de centrage de la carte sur la position GPS courante.

**Comment by sgrimault** [comment]
Il existe déjà ?
C'est le bouton placé au dessus du bouton "+" pour ajouter un marqueur.

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Cela fonctionne en effet
