### ISSUE TITLE
Manque d'attribution OpenStreetMap

### ISSUE THREAD

**Issue by ghost** [PnX-SI/gn_mobile_occtax#191]
Bonjour,

En tant que contributeur à OpenStreetMap, je suis content de voir que vous utilisez une carte issue d'OpenStreetMap dans vos outils et plus particulièrement sur les services correspondants aux captures ci-dessous :
- https://geonature.fr/img/portfolio/fullsize/03-gn2-occtax.jpg
- https://github.com/PnX-SI/gn_mobile_occtax/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png

Cependant, j'ai noté que la carte n'est pas correctement attribuée. En effet, nous demandons que votre crédit comporte la mention « © les contributeurs d’OpenStreetMap » (y compris pour celle mentionnant déjà « OpenTopoMap »). Vous devez également préciser clairement que les données sont disponibles sous la licence ODbL. Vous pouvez mentionner ceci avec un lien hypertexte vers https://www.openstreetmap.org/copyright.

Une attribution correcte permet de préciser les sources de la carte ou des données ainsi que ce que les utilisateurs ont le droit d'en faire.

Si vous avez besoin d'aide pour effectuer la correction ou si vous avez des questions, ne pas hésiter à répondre à ce message ou à utiliser un de nos canaux de communication : https://wiki.openstreetmap.org/wiki/FR:Canaux_de_contact.

Enfin, une attribution correcte permet de diffuser l'existence d'OpenStreetMap, d'attirer de nouvelles contributions et d'étendre la communauté. C'est extrêmement important pour améliorer la qualité de la base de données en qui vous et des millions de personnes font confiance.

Lorsque la correction aura été faite, n'hésitez pas à me le signaler.

Merci.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Je vous remercie pour cette alerte. A noter que l'attribution des couches est configurable par chaque administrateur qui déploie l'outil, de même que les couches mises en place ou non pour le module cartographiques. Les utilisateurs peuvent donc utiliser, ou non, les couches OSM ou ajouter toute autre source, et préciser/modifier leur attribution pour une plus grande souplesse de nos outils. On ne peut donc pas garantir que tous les utilisateurs mentionnent correctement les attributions de leurs différentes couches.

Cependant pour tendre au maximum vers une bonne attribution, nous allons faire en sorte que les configurations proposées par défaut dans nos fichiers de settings fournis en exemple comportent bien les informations valides que vous mentionnez ([documenté ici](https://github.com/PnX-SI/gn_mobile_occtax/blob/60540181fe48521508e093ce4f69c9597c9a4732/README.md)). 

@sgrimault je te laisse apporter la modification dans le settings par défaut et la documentation ? On confirmera quand ça sera opérationnel lors d'une prochaine release en cloturant ce ticket,

Encore merci en tous cas pour tout le travail produit par les contributeurs d’OpenStreetMap !

**Comment by camillemonchicourt** [comment]
Merci pour ces éléments.
En effet, nous sommes bien au courant des usages d'OSM, de leurs licences et de l'importance de les afficher.

Les captures en questions ne sont pas forcément à jour et on a bien une attribution affichée sur les cartes dans Occtax-mobile.
Mais en effet, elles ne sont pas complètes et mériteraient d'être revues.

Dans la documentation de configuration (https://github.com/PnX-SI/gn_mobile_occtax/blob/master/README.md#settings), je vois bien la possibilité d'associer une attribution à chaque couche avec un exemple : 
```json
      "label": "OpenStreetMap",
      "source": "https://a.tile.openstreetmap.org/",
      "properties": {
        "attribution": "© OSM contributors"
        }
```

Quand j'utilise l'application, je vois l'attribution ``© OpenStreetMap contributors`` et non pas ``© OSM contributors``, donc j'ai du mal à voir quelle info il prend et où. D'ailleurs j'ai l'impression qu'il affiche cette attribution ``© OpenStreetMap contributors`` dans tous les cas, même si on définit une autre couche (IGN ou autre) sans attribution.

Donc il faudrait certainement vérifier et clarifier le fonctionnement des attributions, et fournir les bonnes dans la conf par défaut et dans la documentation.

``© OpenStreetMap contributors`` correspond à l'ancienne forme des attributions qui est correcte mais améliorable.

Pour la couche OSM fournie par défaut et en exemple dans Occtax-mobile, la bonne attribution serait ``<a href="https://www.openstreetmap.org/copyright" target="_blank">© OpenStreetMap contributors</a>``.

Concernant la première capture d'écran utilisant OpenTopoMap, elle correspond à un autre projet, outil et dépôt (GeoNature) et je viens de faire une correction pour compléter les attributions OSM correctement : https://github.com/PnX-SI/GeoNature/pull/2038.

Merci.

**Comment by sgrimault** [comment]
Bonjour,

Concernant les attributions, c'est une propriété optionnelle à définir par couche géographique (cf. attribut `properties/attribution`, https://github.com/PnX-SI/gn_mobile_maps/tree/develop/maps#layer-properties). Seules les couches "online" sont concernées et comme on ne peut afficher qu'une seule couche à la fois, on ne voit donc sur la carte que l'attribution de la couche active en question.

Coté module cartographique on a la possibilité aussi de configurer l'affichage ou non des attributions. Par défaut, elles sont affichées si elles sont bien définies ( cf. attribut `show_attribution`, https://github.com/PnX-SI/gn_mobile_maps/tree/develop/maps#parameters-description).

Il faudrait donc faire une petite passe sur les captures d'écrans de la documentation pour mieux illustrer les bons cas d'usage :)

**Comment by camillemonchicourt** [comment]
Il faudrait aussi qu'on améliore les valeurs par défaut dans la doc, non ?

**Comment by camillemonchicourt** [comment]
Les attributions OpenStreetMap fournies par défaut et dans la documentation ont été revues dans la version 2.6.0 : 

![Screenshot_20230508_222244_fr geonature occtax2](https://user-images.githubusercontent.com/4418840/236926642-33e0241f-7d34-464c-b564-34904be0278c.jpg)
