### ISSUE TITLE
Documentation sur les fonds cartographiques

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#192]
Rédaction d'une documentation sur le fonctionnement de l'affichage (hiérarchisation, affichage par défaut...) des fonds cartographiques récupérés en ligne et hors ligne selon la configuration de l'application. Cette documentation centralise des explications, précisions... se trouvant déjà dans des mails ou d'autres issues (https://github.com/PnX-SI/gn_mobile_maps/issues/4).

**Comment by camillemonchicourt** [comment]
Fait dans les commits référencés ci-dessus, et disponible dans le README du module MAPS - https://github.com/PnX-SI/gn_mobile_maps/blob/develop/maps/README.md
