### ISSUE TITLE
ajout version_code dans gn_commons.t_mobile_apps

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/gn_mobile_occtax#197]
Bonsoir,

Je suis en train de suivre la documentation pour l'installation et la configuration de l'appli mobile v.2.4.0 mais je ne sais pas comment ajouter le version_code dans gn_commons.t_mobile_apps ; la commande n'est pas spécifié dans la doc.

Merci pour votre aide.

Bonne soirée.

**Comment by camillemonchicourt** [comment]
On peut le faire en SQL, mais en général, on le fait directement depuis un logiciel permettant d'accéder à la consultation et administration de la base de données, comme Dbeaver ou PGadmin.

**Comment by gildeluermoz** [comment]
Il vous sera utile d'accèder en écriture à la base de données. Certaines infos de configuration de GeoNature se trouvent dans la base et certains paramètres aussi. Par exemple les valeurs par défaut des nomenclatures. Pour les lire ou les modifier, il est utile d'accèder à la base avec un logiciel SGDB comme ceux indiqués par @camillemonchicourt .
Vous aurez aussi peut-être besoin de lire les code dans le référentiel geographique pour éventuellement modifier la configuration par défaut du dashboard ou coté occtax-mobile ou encore certains filtres de la synthèse.
Bonne découverte et bonne installation.

**Comment by naidinp** [comment]
c'est fait : installation pgAdmin et renseignement de la table.

...il reste finaliser la synchro ....autre paire de manches ;)

merci pour l'aide 👍

**Comment by camillemonchicourt** [comment]
Finaliser la synchro, c'est-à-dire ?
Elle se fait toute seule quand on lance l'application mobile et qu'on renseigne l'URL du GeoNature.

**Comment by naidinp** [comment]
...ca ne fonctionne pas encore....je creuse pour comprendre car j'ai dans le logcat : GeoNatureAPIClientImpl: <-- 401 UNAUTHORIZED

**Comment by camillemonchicourt** [comment]
OK, avez-vous bien renseigné le paramètre gn_application_id dans la configuration avec l'ID de l'application GeoNature dans le fichier de configuration settings.json, placé sur le serveur GeoNature ?

**Comment by naidinp** [comment]
effectivement ca va mieux maintenant ;) merci
je continue mes tests.
Belle journée.

**Comment by naidinp** [comment]
Encore une question s'il vous plait : 
- Dans les Paramètres de l'application mobile je n'ai que l'URL de GeoNature mais pas de l'URL de TaxHub

C'est normal ? 

merci

**Comment by camillemonchicourt** [comment]
L'URL de TaxHub est à renseigner dans le paramètre dédié dans le fichier settings.json sur le serveur GeoNature

**Comment by naidinp** [comment]
L'URL de TaxHub est bien dans le fichier settings.json sur le serveur.

Je vais ouvrir un autre ticket avec un sujet diffèrent.

Merci encore pour votre aide.
