### ISSUE TITLE
Récupération liste Taxons 

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/gn_mobile_occtax#198]
Bonjour à tous,

J'ai réussi a faire fonctionner la synchro avec pas mal d'aide de votre part.
Egalement j'ai crée un jeu de données sur la plateforme et j'ai ajouté un relevé, tout fonctionne bien de ce coté.

Je me suis connecté sur l'application occtax sur le mobile et j'ai défini le Jeu de données par défaut le même que cellui utilise sur la plateforme.

Mon problème est que dans l'ecran Choix du taxon, j'ai aucune liste qui est chargé.
Comment je peut vérifier si les listes sont chargées ?

Merci

**Comment by DonovanMaillard** [comment]
Bonjour, 

Au niveau des listes, Occtax-mobile a besoin d'un identifiant de liste taxhub dans son fichier de configuration. Et il faut naturellement que cette liste soit peuplée par les taxons de votre choix du coté de taxhub. 

Occtax (web) récupére par défaut tout le taxref si rien n'est défini, mais pas le mobile pour le moment, il ne charge que par liste. Je vous propose de commencer par controler que vous avez bien une liste en place, avec vos taxons, et que c'est bien cet identifiant de liste qui est renseigné dans la conf de occtax-mobile,

A ce stade, la liste définie au niveau du jeu de données n'a pas encore d'effet sur le mobile. C'est en cours de développement, ca viendra dans l'une des prochaines versions.

**Comment by camillemonchicourt** [comment]
Oui actuellement, il faut définir une liste de taxons qui sont disponibles en saisie dans Occtax-mobile, pour ne pas charger tout Taxref dans le mobile, qui serait lourd et pas forcément utile de proposer une grosse liste de 600.000 taxons dans Occtax-mobile.

Cela peut être manuellement, taxon par taxons depuis TaxHub, voir https://taxhub.readthedocs.io/fr/latest/manuel-utilisateur.html#ajouter-une-espece-a-la-liste-de-ses-taxons.

Ou alors en SQL pour mettre tout un ensemble de taxons, par exemple, tout un groupe, toute la flore, etc.
Voir l'exemple de requête dans la doc de GeoNature : https://docs.geonature.fr/admin-manual.html#personnaliser-la-liste-des-taxons-saisissables-dans-le-module.

PS : A noter, qu'il est possible d'utiliser cette même liste de taxons au niveau d'Occtax-web, si là aussi vous voulez proposer qu'une liste d'espèces maîtrisée aux personnes qui vont saisir des observations.

**Comment by naidinp** [comment]
Super, merci pour toutes ces infos....je m'y mets dès cet après-midi dessus.

**Comment by naidinp** [comment]
C'est PARFAIT, j'ai réussi a peupler la liste 100 avec l'exemple de la commande SQL, et la récupérer a la synchro mobile.

Merci -  Je ferme ce ticket
