### ISSUE TITLE
Gestion liste taxons pour groupe/observateur

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/gn_mobile_occtax#199]
Bonjour à tous,

Je suis en phase de tests de l'application occtax mobile et la gestion des listes de taxons.

Avec votre aide et la documentation, j'ai réussi à :
1. peupler la liste Saisie Occtax (code 100), mais trop longue à synchroniser.
2. créer une deuxième liste Liste Phase Tests (code 200) que j'ai peuplé avec une dizaine de taxons.
3. déclarer cette deuxième liste dans le **settings.json** sur le serveur et récupérer la liste dans occtax mobile.

J'ai cherché dans les issues....etc mais rien trouvé comment gérer (si c'est possible) plusieurs listes pour un groupe/observateur afin de pouvoir alléger la synchro quand on est sur le terrain.

La variable  "taxa_list_id": 200, peut être peuple avec plusieurs id's ?

Merci pour vos éclaircissements.

**Comment by camillemonchicourt** [comment]
Actuellement, on ne peut définir qu'une seule liste de taxons unique pour tous les utilisateurs d'Occtax-mobile branchés sur un instance GeoNature.

Au Parc national des Écrins, nous avons défini une liste d'environ 10.000 taxons correspondant aux espèces déjà observées au moins une fois sur le territoire, pour ne pas proposer aux agents des taxons inutiles, Taxref comprenant plus de 200.000 espèces et beaucoup de synonymes.
On a déjà testé avec beaucoup plus de taxons. C'est long, mais ça passe normalement.

Un travail est en cours pour revoir globalement la synchronisation et notamment la partie taxonomie. En partie discuté ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/133, même si les réflexions ont évolué depuis.

Il y a aussi le fait que dans GeoNature et Occtax-web, on peut désormais définir des listes de taxons différentes par jeu de données, et c'est cela qu'il est prévu de répercuter dans Occtax-mobile : https://github.com/PnX-SI/gn_mobile_core/issues/41

**Comment by naidinp** [comment]
Merci pour les éclaircissements. je ferme le ticket
