### ISSUE TITLE
Parcours utilisateurs

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#2]
Par @sgrimault : Vous trouverez ci-joint une première mouture du parcours utilisateur de l'application "OccTax" : [occtax_nav.pdf](https://github.com/PnX-SI/gn_mobile_occtax/files/2946254/occtax_nav.pdf)
A suivre : la partie synchronisation (coté mobile).

Retour de @Chrispnv : 

Pour bien comprendre. Il s'agit ici de valider principalement le workflow et les différents écrans ? Le contenu exact de chaque écran viendra par la suite ?
- Accueil > Paramètres > Jeu de données => C'est une liste de choix directement dans l'écran Paramètres ou c'est comme pour les observateurs, c'est un nouvel écran qui apparait ? C'est peut être la même logique que dans l'étape 4 pour ne pas surcharger le schéma.
- Etape 4bis : Elle n'apparait pas dans le parcours utilisateur ?
- Etape 5 Dénombrement : Je suppose que Description #1 #2 reprend tous les attributs de l'écran 5 sur chaque observations.
- Bilan de saisie et Récapitulatif : idem Etape 5

Réponse de @sgrimault : 

Oui, c'est déjà de valider les grandes lignes du parcours utilisateur. Certains écrans ont déjà des libellés bien précis (comme par exemple, l'écran d'accueil, les paramètres, les étape 1, 2, 4). Les autres dépendent de beaucoup des données issues de GeoNature. Je compléterai ce diagramme et je rajouterai aussi en détail la partie synchronisation.

Concernant les premiers retours :
- Jeu de données : Le fonctionnement du choix du (ou des ?) jeux de données sera sans doute calqué sur celui du choix de l'utilisateur par défaut. On est redirigé vers un autre écran où on liste l'ensemble des jeux de données possibles. L'avantage est que l'on garde un fonctionnement similaire sur tous les écrans de choix de l'application (choix d'un ou de plusieurs observateurs à l'étape 1, choix de l'état biologique à l'étape 4, etc.). Par contre si vous pensez que cette liste contiendra peu d'éléments, alors il est possible aussi de partir sur une boite de dialogue qui présente sous forme de petite liste cette sélection. Par contre, cette approche restreint à un et un choix possible alors que la solution d'un écran dédié sous forme de liste permet une sélection multiple.
- Étape 4bis : Je compléterai le diagramme car je n'ai pas détaillé cette partie. À l'étape 4, on a une rubrique nommée "Informations avancées". Quand on clique sur le bouton "Ajouter", cette rubrique se "déplie" pour faire apparaître directement dans le même écran les autres rubriques ("Méthode de détermination", "Statut biologique", etc.). Chaque rubrique aura le même fonctionnement à savoir un bouton "Ajouter" (ou "Modifier" si l'utilisateur à déjà saisi quelque chose) qui redirige vers une liste de choix dans un écran déporté (à l'image de l'exemple avec la rubrique "État biologique"). Chaque rubrique présentera directement de manière synthétique le choix de l'utilisateur.
- Étape 5 : Cette étape récapitule bien la saisie faire à l'étape "édition d'un dénombrement". Ne sachant pas trop comment sont structurées ces données, je n'ai pas détaillé comment sera présenté un dénombrement de manière synthétique dans la liste.
- Bilan de la saisie : Même remarque que précédemment, l'idée est de pouvoir présenter de manière synthétique une saisie d'un taxon. Il faudra du coup déterminer les attributs pertinents à mettre en avant pour construire cette synthèse.
- Récapitulatif : Cet écran reprend tous les attributs d'une saisie sous forme de liste simple à partir de l'étape 3. Le bouton "édition" redirige simplement à l'étape 3. Il manquerait un bouton "supprimer" dans la barre d'action pour supprimer directement cette saisie après confirmation auprès de l'utilisateur.

**Comment by sgrimault** [comment]
Nouvelle version du parcours utilisateur :
[occtax_nav.pdf](https://github.com/PnX-SI/gn_mobile_occtax/files/2949695/occtax_nav.pdf)

**Comment by camillemonchicourt** [comment]
OK merci.
Je pense que dans l'étape 1 il faut afficher aussi le jeu de donnée comme l'observateur pour que l'utilisateur voit bien dans quel JDD il travaille et le modifie éventuellement.

Dans l'étape 3, comme dans l'ancien Contact Faune il faut afficher pour chaque taxon la couleur, ainsi que le nombre d'observation et la dernière observation dans l'unité géographique du pointage.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour le moment sur la version web, les données sont saisies dans un et un seul jdd. Dans les référentiels, en théorie, une donnée peut etre attachée à plusieurs jeux, mais ce cas n'a pas l'air prévu dans la synthèse par exemple. (et dans la pratique ça semble être relativement exceptionnel d'avoir plusieurs jdd sur une observation). 

Par ailleurs, j'aurais allégé d'une étape le parcours utilisateur pour avoir une étape de moins à sauter pour les observateurs ne remplissant que le minima. Je mettrais le dénombrement comme l'un des nombreux blocs de l'étape précédente. 
Pour une saisie rapide, ca donne "je verifie mon observateur et mon JDD (présenté en premiere page comme le dit camille), je pointe sur la carte, je saisie les espèces, je passe le détail et je valide. 

Par ailleurs, est-ce que la version mobile prévoit des saisies sur des lignes ou des polygones, ou uniquement des données au point? Si c'est uniquement au point, pourquoi avoir cette icone pour préciser qu'on veut pointer? Pourquoi ne pas simplement pointer là ou l'utilisateur appuie (tout en permettant le défilement à un doigt, et le zoom à deux doigts)

**Comment by camillemonchicourt** [comment]
Oui il n'y a bien qu'un seul JDD par relevé.

**Comment by sgrimault** [comment]
Bonjour,

L'étape "Dénombrement" est particulière car l'utilisateur peut en créer plusieurs, d'où cette étape à part entière.
Pour la saisie sur la carte, l'application "OccTax" reste proche de l'application "Faune" à savoir qu'on ne saisit que des points contrairement à l'application "Flore prioritaire" où on peut faire des saisies de chemins et de polygones en plus des points. Je détaillerai cette partie, car il sera possible de poser un point directement à partir de la positon courante de l'utilisateur.

**Comment by sgrimault** [comment]
Nouvelle version du parcours utilisateur :
[occtax_nav.pdf](https://github.com/PnX-SI/gn_mobile_occtax/files/2958804/occtax_nav.pdf)

**Comment by Chrispnv** [comment]
OK pour la nouvelle version du parcours utilisateurs.
