### ISSUE TITLE
Configuration fond de carte

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/gn_mobile_occtax#200]
Bonjour à tous,

Est-il possible d'afficher une carte orthophoto sur occtax V2?
J'aimerai tester la configuration avec un stockage en local sur le mobile.

Merci d'avance

**Comment by naidinp** [comment]
Super, merci pour l'info.....reste plu qu'a découvrir l'utilisation de MOBAC pour exporter une carte ....c'est pas facile quand on n'est pas du métier.
**Si vous avez une doc pour la procédure de génération des fonds de cartes avec MOBAC ...je suis preneur!**
Je sais que je dépasse les limites du sujet ...**.veuillez m'excuser**.

Merci encore

**Comment by gildeluermoz** [comment]
Vous trouverez des infos sur MOBAC en googlisant
par exemple : https://docplayer.fr/32882686-Le-logiciel-gratuit-mobile-atlas-creator-permet-de-faire-des-cartes-compatibles-avec-sports-tracker.html
je vous recommande de produire des fichiers (atlases) au format mbtiles.
bonne découverte

**Comment by camillemonchicourt** [comment]
De mémoire, il est aussi possible et beaucoup plus simple techniquement de générer des mbtiles directement depuis QGIS.

Un peu moins performant dans mon souvenir, mais beaucoup moins technique.

**Comment by naidinp** [comment]
Merci Messieurs pour ces précieuses informations.
Effectivement QGIS est moins technique pour la génération des cartes offline (mbtiles).

Belle journée à tous.
