### ISSUE TITLE
Fonds de cartes continent

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/gn_mobile_occtax#201]
Bonjour à tous,

Je voudrais savoir s'il est possible d'avoir des layers OpenStreeMap ou Google mais d'un continent entier genre Europe, Afrique ....etc.
Je ne vois pas comment déclarer la source dans le settings.json.

Une piste ?

Merci d'avance

**Comment by camillemonchicourt** [comment]
Là si on les veut en OFFLINE, ça va être très lourd. :-)

Par contre on peut avoir des fonds OFFLINE et/ou ONLINE (OSM notamment).
Voir https://github.com/PnX-SI/gn_mobile_occtax/issues/51

Il est prévu d'améliorer la documentation sur le sujet prochainement - https://github.com/PnX-SI/gn_mobile_occtax/issues/192

Mais ça fonctionne comme dans l'exemple qui combine 2 fonds MBTILES ONLINE et un fond OSM ONLINE - https://github.com/PnX-SI/gn_mobile_occtax#settings

**Comment by naidinp** [comment]
Effectivement j’avais vu les liens que vous m’indiquez.
En prenant l’exemple qui combine les 2 fonds, si je veux mettre un point sur une ville en Roumanie par exemple, je ne peut scroller l’écran pour afficher la Region de l’Europe de l’Est, comme sur occitan web.
Y’a t’il une limitation de l’affichage du fond de carte ?

**Comment by gildeluermoz** [comment]
Est-ce que vous avez bien paramétré les max_bounds dans le fichier settings.json de l'application pour permettre la saisie sur le pays souhaité ?
Dans l'exemple ci-dessous, on peut saisir en France métropolitaine (dont la corse) mais pas hors de ces bornes
`"max_bounds": [ [51.1,9.6], [ 41.27,-5.46] ]`

**Comment by naidinp** [comment]
….je l’avais vu ce paramètre mais pas pris le temps de regarder dans la doc :(
Demain je vais tester avec des différents paramètres mais si je ne me trompe pas, comme j’utilise une configuration centralisée sur le serveur, tous les mobiles récupéreront cette configuration. 
Pouvons nous avoir une configuration centralisé pour une flotte de mobiles, et quelques-autres avec une configuration spécifique (ex : Modifier en direct sur le mobile le fichier settings.json) ?
Merci

**Comment by camillemonchicourt** [comment]
Non, c'est la même conf pour tous, et c'est celle du fichier sur le serveur qui écrase celle en local sur les appareils.
L'idée de pouvoir surcoucher localement le fichier de configuration a été discutée ici https://github.com/PnX-SI/gn_mobile_occtax/issues/95, mais mise de côté pour le moment.

Dans tous les cas, aucun soucis à étendre la zone de "max_bound" à toute l'Europe, voire le monde entier.
Vous pouvez aussi modifier le centrage et le zoom par défaut.

**Comment by naidinp** [comment]
Merci à tous pour ces infos.

Belle journée
