### ISSUE TITLE
[2.4.1 RC] Problème Affichage partie Dénombrement

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_mobile_occtax#207]
Sur toutes les RC (1 à 4), j'ai les champs permettant de saisir le nombre min et le max d'observations qui ne s'affichent pas. Seules les 4 listes sont présentes en haut de page. Sur la RC4, je n'ai également pas accès à la partie média. Aucun problème en 2.4. 

Téléphone : Google Pixel 6A Android 13.

(Je suis dispo pour faire des tests au besoin sur ce téléphone, ou version d'Android)

**Comment by DonovanMaillard** [comment]
Merci Jérome pour ton retour. J'ai le même problème de mon coté, Sébastien a commencé à regarder. 

Il y a eu un changement de conf déjà, les champs appelés MIN et MAX sont devenus Count_min et Count_max. Mais de mon coté ca n'a pas réglé le problème.

**Comment by JeromeMaruejouls** [comment]
Ok ! Pour la conf, je ne sais pas trop comment la gérer car j'ai la conf v2.4 sur le serveur (pour les personnes utilisant l'appli normale).
Sur ce téléphone, où j'ai mis la RC, il a récupéré la conf du serveur (renommé settings_occtax.json) dans android/data/fr.geonature.occtax2. J'ai tenté d'éditer ce fichier en local, mais il est réinitialisé à la conf serveur à chaque action sur l'appli... Il faudrait donc pouvoir tester en modifiant la conf serveur et donc, sans avoir d'utilisateur de la 2.4 en même temps.

**Comment by DonovanMaillard** [comment]
pour ma part j'ai simplement ajouté les nouveaux paramètres. L'ancienne version ne connait pas cette clé donc ignorera. Et la nouvelle version ne connait pas MIN et MAX donc ignorera aussi. Mais dans mon cas ça n'a pas solutttionné le comportement que tu relèves...

**Comment by camillemonchicourt** [comment]
Merci de partager votre configuration que l'on puisse comprendre votre contexte et le solutionner.

**Comment by JeromeMaruejouls** [comment]
Voici le fichier de conf fonctionnel en 2..4 (auquel j'ai rajouté dans "counting" : count_min et count_max.

`
{
  "area_observation_duration": 365,
  "sync": {
    "geonature_url": "https://geonature.biodiv-occitanie.fr",
    "taxhub_url": "https://taxhub.biodiv-occitanie.fr",
    "gn_application_id": 3,
    "observers_list_id": 1,
    "taxa_list_id": 100,
    "code_area_type": "M5",
    "page_size": 10000
  },
  "map": {
    "show_scale": true,
    "show_compass": true,
    "max_bounds": [
      [45.5, -0.9],
      [40.5, 11.0]
    ],
    "center": [43.4, 1.9],
    "start_zoom": 10.0,
    "min_zoom": 8.0,
    "max_zoom": 20.0,
    "min_zoom_editing": 15.0,
    "base_path": "Offline_maps",
    "layers": [
      {
        "label": "OSM Web",
        "source": "https://a.tile.openstreetmap.org"
      },
      {
        "label": "OSM Web FR",
        "source": "https://a.tile.openstreetmap.fr/hot"
      },
      {
        "label": "OTM",
        "source": "https://a.tile.opentopomap.org/",
	    "properties": {
	      "attribution": "@ OTM contributors"
	    }
      },
      {
        "label": "Mailles 5x5km",
        "source": "M5.geojson",
	    "properties": {
	      "style": {
	        "stroke": true,
	        "opacity": 0.1
	      }
	    }
      },
      {
        "label": "Ortho 31",
        "source": "dep31_12_15_96dpi.mbtiles"
      }
    ]
  },
  "input" :{
    "date": {
      "enable_hours" : true,
      "enable_end_date" : false
    }
  },
  "nomenclature": {
    "save_default_values": true,
    "information": [
      "METH_OBS",
      {
        "key": "ETA_BIO"
      },
      {
        "key": "METH_DETERMIN",
        "visible": true,
        "default": false
      },
      {
        "key": "STATUT_BIO",
        "visible": true,
        "default": false
      },
      {
        "key": "OCC_COMPORTEMENT",
        "visible": true,
        "default": false
      },
      {
        "key": "NATURALITE",
        "visible": false,
        "default": false
      },
      {
        "key": "COMMENT",
        "visible": true,
        "default": false
      }
    ],
    "counting": [
      "STADE_VIE",
      "SEXE",
      "OBJ_DENBR",
      "TYP_DENBR",
      "MIN",
      "MAX",
      "COUNT_MIN",
      "COUNT_MAX"
    ]
  },
  "no_such_property": "no_such_value"
}

`

**Comment by DonovanMaillard** [comment]
Idem en version complète : 

"counting": [
          {
            "key": "STADE_VIE",
            "visible": true,
            "default": true
          },
          {
            "key": "SEXE",
            "visible": true,
            "default": true
          },
          {
            "key": "OBJ_DENBR",
            "visible": true,
            "default": true
          },
          {
            "key": "TYP_DENBR",
            "visible": true,
            "default": true
          },
          {
            "key": "MIN",
            "visible": true,
            "default": true
          },
          {
            "key": "MAX",
            "visible": true,
            "default": true
          },
          {
            "key": "Count_min",
            "visible": true,
            "default": true
          },
          {
            "key": "Count_max",
            "visible": true,
            "default": true
          }
          
        
A voir pour ce qui est des majuscules sur ces paramètres, j'ai appliqué ce que Sébastien m'a retourné par mail de mon coté

**Comment by sgrimault** [comment]
La gestion de la nomenclature a un peu changé pour notamment suivre l'attendu coté API afin de faciliter le mapping. Moins de code à maintenir, maintenance plus aisée, potentiellement moins de bugs aussi en passant :) Cette évolution fait partie des travaux qui ont commencés pour faire appel aux nouvelles APIs du module "occtax" mais aussi pour le support futur des champs additionnels.

Le [README](https://github.com/PnX-SI/gn_mobile_occtax/tree/develop#nomenclature-settings) a été mis à jour pour lister l'ensemble des propriétés attendues. Le respect du nommage des attributs est important et doit respecter la casse. Ainsi pour la partie dénombrement, l'application attend `count_min` et `count_max` et pas `COUNT_MIN` ou `COUNT_MAX`.

Ce qui serait bien aussi ce serait de respecter une forme de "versioning" de la partie paramétrage de l'application "Occtax". Actuellement, l'application fait appel à `GET -> /api/gn_commons/t_mobile_apps` pour récupérer son paramétrage en se basant uniquement sur l'attribut `package`, sans tenir compte de l'attribut `version_code` (qui lui ne sert qu'à déterminer si il y a une version plus récente de l'application ou non). Si on tient compte du couple `package` et `version_code` pour récupérer le paramétrage, on pourrait alors facilement gérer les mises à jour de l'application sur l'ensemble du parc le temps de propager la nouvelle version tout en maintenant la version n-1.
Dans notre cas, la version n-1 contiendra par exemple les attributs `MIN` et `MAX` sur la partie dénombrement et la nouvelle version aura les bons attributs `count_min` et `count_max` sans devoir combiner en plus l'ancien paramétrage.

**Comment by DonovanMaillard** [comment]
merci Sébastien, effectivement j'avais Count avec une majuscule d'après nos échanges par mail. Tout en minuscule c'est OK pour les dénombremnets. 

J'ai aussi les médias en le notant explicitement (à noter que j'ai aussi supprimé le cache de l'appli en parallèle de la mise à jour de la conf). 

Pour les médias, on avait évoqué des paramètres spécifiques sur le #84 concernant les taux de compressions et définition maximale. C'est fait en dur au final ?

**Comment by sgrimault** [comment]
Actuellement ce n'est pas paramétrable, juste le fait d'activer ou non cette fonctionnalité en configurant la partie dénombrement.
Je vais voir plus tard, pour rendre la qualité des photos paramétrable.

**Comment by DonovanMaillard** [comment]
Ca marche merci, à revoir avec @camillemonchicourt et le PN qui a passé la commande si on reste la dessus ou non. Si ca marche bien comme ca ce n'est pas nécessairement intéressant de complexifier la configuration ;)

**Comment by JeromeMaruejouls** [comment]
Parfait, ca fonctionne très bien pour moi aussi. Merci pour la mise à jour du Readme.
Je clos le topic.
