### ISSUE TITLE
Etape initiale - Horodatage relevé créé

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#21]
Est il possible de mettre l'heure en plus de la date sur les relevés créés dans le le bloc relevés en cours ?
Les agents seront intéressés d'avoir cette information pour la gestion des relevés en cours sur le terrain et même au retour avant la synchronisation.

**Comment by sgrimault** [comment]
Est ce que l'heure sera aussi à synchroniser coté GeoNature ?

**Comment by Chrispnv** [comment]
Bonne question @camillemonchicourt tu peux répondre ?

**Comment by TheoLechemia** [comment]
La table "t_releve" d'occtax contient des champs "hour_min" et "hour_max" (qui sont dans le standard) et l'API permet d'envoyer ces infos. Donc oui le formulaire du mobile doit pouvoir envoyer ces infos.

**Comment by gildeluermoz** [comment]
Même si sur mobile ce sera souvent la même chose (mais pas toujours car certains agents peuvent faire des saisies a posteriori), attention de ne pas confondre l'heure de l'observation et l'heure de création du relevé. S'il a transfert vers la base dans le schéma `pr_occtax`, c'est uniquement si l'heure d'observation est renseignée.
Elle peut-être fournie par default = now dans le formulaire - tout en étant modifiable - mais si c'est de l'heure de création du relevé dans le mobile dont il s'agit (= now), il ne faut pas la transmettre en base.

**Comment by Chrispnv** [comment]
@gildeluermoz 
Tu as tout à fait raison.
Je voyais l'affichage de l'heure comme un repère dans les saisies effectuées afin de modifier ou supprimer certaines à postériori (exemple à la pause de midi sur le terrain ou en fin de journée de prospection). Je sais qu'il y a des agents qui utilise l'heure comme repère.
La solution serait peut être de garder ce repère d'heure dans l'appli mobile mais de ne rien enregistrer en BDD.
Réaction ?

**Comment by camillemonchicourt** [comment]
Oui il y a d'ailleurs une élément qui n'est pas clair à ce niveau. 
L'interface affiche "Relevé créé le XXXX". Hors la date affichée est celle du relevé, pas de la date où il a été créé. En effet il faudrait plutôt afficher la date et l'heure de création du relevé, et non pas la date du relevé, ce qui n'est pas la même chose. 

Et c'est bien uniquement la date du relevé qui est envoyé à la BDD, et non pas la date et heure de sa création, uniquement affiché dans l'application mobile comme repère pour lister les relevés en cours.

**Comment by camillemonchicourt** [comment]
On peut garder le fonctionnement actuel, mais alors il faut renommer "Relevé créé le XXXX" en "Relevé du XXX", car XXXX est la date du relevé et non pas la date où il a été créé.

**Comment by camillemonchicourt** [comment]
Fait dans 2 commits la branche https://github.com/PnX-SI/gn_mobile_occtax/tree/fix-21, à partir de la branche ``develop``, mais pas sur si il faut aussi changer le nom de la variable ``home_input_created_at`` ?

Et quand j'essaie de faire une PR à partir de cette branche, cela inclut de nombreux autres commits car ``master`` en retard ?
https://github.com/PnX-SI/gn_mobile_occtax/compare/fix-21

**Comment by sgrimault** [comment]
@camillemonchicourt 
Un petit rebase à faire en local ?
Concernant le workflow git, c'est de créer les feature branchs / fix toujours à partir de `develop`. `master` n'est mis à jour uniquement lors des releases en faisant un rebase à partir de `develop`.

**Comment by camillemonchicourt** [comment]
J'ai fait directement depuis Github.
Mais en effet, j'ai du me rater et faire ma modification depuis ``master`` au lieu de ``develop``.
