### ISSUE TITLE
Valeur par défaut des champs "Min"et "Max" dans la partie dénombrement

### ISSUE THREAD

**Issue by sgrimault** [PnX-SI/gn_mobile_occtax#210]
Actuellement, les champs "Min" et "Max" ne prennent pas la valeur 1 par défaut si la nomenclature est configurée dans le fichier de paramétrage de l'application :

> En revanche, peux-tu mettre des valeurs 1/1 par défaut pour les dénombrements avant la publication de la 2.4.1 s'il te plait (qui s'appellera 2.5 d'ailleurs) ?
> _Originally posted by @DonovanMaillard in https://github.com/PnX-SI/gn_mobile_occtax/issues/209#issuecomment-1478482599_

**Comment by DonovanMaillard** [comment]
Je ne suis pas sur de comprendre : 

Min et Max (désormais count_min et count_max) ne sont pas des nomenclatures mais des inputs de type integer. Il n'y a aucune valeur par défaut configurée en BDD par exemple, et rien ne permet de définir une valeur par défaut dans settings.ini sauf erreur. 

Le 1/1 peut être défini en dur au niveau de l'appli sans passer par un paramètre.

**Comment by sgrimault** [comment]
Si on configure la partie "nomenclature" dans le fichier de configuration comme suit par exemple :

```json
{
  // ...
  "nomenclature": {
    "save_default_values": true,
    "information": [
      "METH_OBS",
      {
        "key": "ETA_BIO"
      },
      {
        "key": "METH_DETERMIN",
        "visible": true,
        "default": false
      },
      {
        "key": "determiner",
        "visible": true,
        "default": false
      },
      {
        "key": "STATUT_BIO",
        "visible": true,
        "default": false
      },
      {
        "key": "NATURALITE",
        "visible": true,
        "default": false
      },
      {
        "key": "PREUVE_EXIST",
        "visible": true,
        "default": false
      },
      {
        "key": "comment",
        "visible": true,
        "default": false
      }
    ],
    "counting": [
      "STADE_VIE",
      "SEXE",
      "OBJ_DENBR",
      "TYP_DENBR",
      "count_min",
      "count_max"
    ]
  },
  // ...
}
```
alors les valeurs par défaut ne sont pas prises en compte pour `count_min` et `count_max`, qui du coup restent à 0.
Les valeurs par défaut pour `count_min` et `count_max` sont déjà fixées à 1 pour la configuration par défaut, qu'il faut donc propager aussi pour une configuration "custom".
Ce point là est déjà corrigé dans la dernière version :)

**Comment by DonovanMaillard** [comment]
Super merci, désolé je n'avais pas saisi la logique. Du coup on peut fermer le ticket puisque c'est corrigé et publié :) 

Merci à toi!
