### ISSUE TITLE
[2.6.0-rc0] souci d'affichage page d'accueil

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_mobile_occtax#217]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.6.0-rc0
Version de GeoNature utilisée : 2.11.0

### Terminal et Version Android

Marque et modèle du terminal : galaxy samsung a33
Version d'Android : 12

### Description du bug et comportement attendu

Merci pour cette dernière version avec notamment la possibilité de synchroniser les relevés sans synchroniser les taxons qui est bien pratique ! Il y a un petit bug d'affichage de mon côté : affichage partiel du titre et de la liste des relevés 

![image](https://user-images.githubusercontent.com/40057801/232821501-34162506-32be-49d0-afed-d78cf0ffcb8c.png)

### Comment reproduire

Saisir une observation puis aller sur la page d’accueil, là où il y a la liste des relevés

**Comment by sgrimault** [comment]
Bonjour @JulienCorny,

Est ce que par hasard, vous avez modifié la taille des polices par défaut sur votre terminal (rubrique "Display" ou quelque chose qui s'en approche depuis les paramètres) ?
Pour information, la gestion de l'accessibilité n'est pas optimale, surtout quand il faut tenir compte d'une variété de configurations possibles et de terminaux ayant une densité d'affichage plus ou moins élevée.

**Comment by camillemonchicourt** [comment]
OK mais c'est dommage que la hauteur de chaque ligne ne s'adapte pas à son contenu et soit un peu plus haut si le texte doit passer sur 2 lignes. 
Pas possible ?

**Comment by sgrimault** [comment]
Je vais déjà voir pour le souci d'affichage des éléments de liste (listing des relevés).

**Comment by camillemonchicourt** [comment]
De mon côté, j'ai toujours le soucis du texte dans le bandeau du haut sur la 2.6.0-rc1, sur un Galaxy A21s : 

![Screenshot_20230419-224756_Occtax](https://user-images.githubusercontent.com/4418840/233294231-85c7acd7-e5d2-4e9f-8040-d1adbf1b82ef.jpg)

**Comment by sgrimault** [comment]
Oui, c'est corrigé sur la branche "develop" uniquement, le temps de faire
une passe sur les autres écrans.

**Comment by camillemonchicourt** [comment]
OK dans la 2.6.0.
