### ISSUE TITLE
[2.6.0-rc0] fond de carte en ligne ign

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_mobile_occtax#218]
Il semble que la pre-release 2.6.0 soit sortie 1 semaine avant la release 0.7.0 de gn_mobile_maps qui permet d'embarquer un fond en ligne ign ortho, fonctionnalité assez attendue. 

Est-ce que vous savez si ce sera disponible dans les prochaines semaines dans une 2.6.0-rc1 par exemple ?

Merci en tout cas pour les derniers développements.

**Comment by camillemonchicourt** [comment]
Oui c'est en effet dans les tuyaux.

Par contre, attention, la 2.6.0-rc1 a un soucis de synchronisation qui peut générer des doublons, donc à ne pas utiliser en production.

**Comment by JulienCorny** [comment]
Merci pour l'info ! du coup est-ce que je peux générer un apk avec la 2.5.0 et la 0.7.0 de gn_mobile_maps (branche master), ou est-ce que ça risque de générer des erreurs, vous pensez que c'est compatible ?

**Comment by sgrimault** [comment]
Bonjour @JulienCorny,

Une version 2.6.0-rc1 sera publiée d'ici à la fin de semaine qui embarquera notamment les évolutions du module "maps".

**Comment by sgrimault** [comment]
La version 2.6.0-rc1 est disponible :rocket: 
https://github.com/PnX-SI/gn_mobile_occtax/releases/tag/2.6.0-rc1

**Comment by camillemonchicourt** [comment]
Cela reste une RC en cours de test et validation, donc pas conseillée en production.
Mais je l'ai déployé sur le serveur de DEMO (demo.geonature.fr) et ait pu faire des saisies et les synchroniser.

Quelques tests et ajustements sont encore en cours avant de sortir une 2.6.0 officielle et aboutie.
