### ISSUE TITLE
Etape 2 Carte - Identification de l'unité géo du relevé

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#22]
Après le pointage, l'application calcule dans quelle unité géographique se trouve le point. Selon l'unité dans laquelle le pointage se trouve, les taxons ne sont pas présentés de la même manière dans l'étape suivante.
Est ce que cette fonctionnalité est opérationnelle ?

**Comment by camillemonchicourt** [comment]
Oui, à faire, en lien avec https://github.com/PnX-SI/gn_mobile_occtax/issues/5
