### ISSUE TITLE
Compatibilité version mobile vs geonature

### ISSUE THREAD

**Issue by lolofr** [PnX-SI/gn_mobile_occtax#226]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.6.1
Version de GeoNature utilisée : 2.9.2
Contexte : version déployé pour une association

### Terminal et Version Android

Marque et modèle du terminal : Samsung S9
Version d'Android : 10

### Description du bug et comportement attendu

Échec de synchronisation des relevés après le passage de la version mobile 2.2.0 à 2.6.1.
la synchro utilisateur ... se passe bien
impossible de synchronisé un nouveau relevé

J'ai l'impression que c'est parce que l'API api/occtax/OCCTAX/only/releve n'existe pas. ESerait-ce un pb de compatibilité en l'appli mobile et geonature. Existe-t'il quelquepart un tableau des compatibilité ?

Dans tous les cas bravo pour tout ce travail et merci pour la mise à dispo.

### Comment reproduire

Étapes à suivre pour reproduire le problème (sur quelle page se rendre, sur quel bouton cliquer,
avec quelles données présentes, …).

### Logs

[occtax_20230615_220919.log](https://github.com/PnX-SI/gn_mobile_occtax/files/11762370/occtax_20230615_220919.log)

**Comment by camillemonchicourt** [comment]
Oui c'est normal.
Il est indiqué dans les notes version d'Occtax-mobile à partir de la 2.5.0 que celle-ci nécessite GeoNature 2.10 ou plus.

Il faut bien regarder les notes de version des différentes releases.

**Comment by lolofr** [comment]
effectivement, je les avais parcourues, mais pas de manière suffisamment attentive.
Puis-je suggérer de mettre en en-tête de chaque note la version minimale de geonature (cela évite d'avoir à relire toute les note de version.

**Comment by camillemonchicourt** [comment]
Oui on pourrait le remettre en effet.
