### ISSUE TITLE
Rendre optionnel l'appel à la route api/synthese/color_taxon

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/gn_mobile_occtax#232]
Bonjour,

**Type d'amélioration**
Nouveau paramètre

**Proposition**
Serait-il possible de rendre optionnel l'appel à la route `api/synthese/color_taxon` si l'instance ne souhaite pas utiliser cette fonctionnalité ?

En effet, nous avons eu des retours de l'Agence Régionale pour la Biodiversité en île de France nous disant que la route mettait trop de temps à renvoyer des données et donc faisait planter l'application due à un timeout. Il était donc impossible pour les utilisateurs de télécharger les autres données nécessaires (JDD, taxons, observateurs etc.). Ils ne souhaitent également pas utiliser les profils de taxons dans occtax-mobile.

Je vais ouvrir également une issue pour tenter d'améliorer la requête SQL derrière cette route et la linkerai ici.

Merci beaucoup !

**Comment by sgrimault** [comment]
Bonjour @mvergez,

Il y a déjà un sujet là dessus pour améliorer la synchronisation des données (https://github.com/PnX-SI/gn_mobile_occtax/issues/133), notamment sur les données relatives aux taxons qui peut potentiellement être très lourde...

**Comment by camillemonchicourt** [comment]
La synchro des taxons et la synchro des couleurs des taxons dans chaque unité géographique (UG) sont quand même 2 choses distinctes.

Concernant la quantitébet le volume des couleurs de taxons par UG va dépendre de 2 choses : ta liste de taxons et ta quantité d'UG.
C'est sur deuxième paramètre que tu peux jouer. Je ne sais plus ce qui est configuré par défaut, mais sur un grand territoire si tu gardes les mailles de 1km ça va être bien trop volumineux à calculer mais aussi à synchroniser. Tu peux passer sur les mailles 5km, ou 10km (ou plus), ou même les communes ou les départements, voir même une seule zone avec tout ton territoire (même si dans ce cas là ça perdrait de son intérêt car cela permet de savoir ce qui a jamais été vu ou vu il y a longtemps autour de toi).

Et de mémoire il y a bien une manière de les désactiver complètement. Peut-être en ne renseignant pas le paramètre de type de zonage géographique dans la configuration d'Occtax-mobile (et/ou côté GeoNature où je crois me souvenir qu'il y a un paramètre aussi).

**Comment by camillemonchicourt** [comment]
Je viens de regarder la doc d'Occtax-mobile, elle indique notamment :

La couche d’unités géographiques doit être issue des entités qui peuplent la table ref_geo.l_areas.

Le code du type de zonage utilisé doit être renseigné dans le paramètre code_area_type du fichier settings.json de gn_mobile_core. Ce même code doit aussi être renseigné dans le paramètre occtaxmobile_area_type de la table gn_commons.t_parameters de la base de données de GeoNature.

Par défaut, si aucune couche vectorielle n’est configurée, l’application va simplement charger la base des taxons sans les informations additionnelles venant des unités géographiques.

**Comment by camillemonchicourt** [comment]
Pour le fait de pouvoir désactiver la synchro des couleurs de taxons, c'est aussi discuté ici - https://github.com/PnX-SI/gn_mobile_occtax/issues/100

En effet, il ne semble pas possible de la désactiver et on pourrait imaginer que si le paramètre `code_area_type` n'est pas renseigné, Occtax-mobile n'interroge pas la route des couleurs de taxons.

**Comment by DonovanMaillard** [comment]
Oui, assez d'accord pour ne pas faire l'appel à la route si le paramètre code_area_type est laissé nul.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.7.0 en ne renseignant pas le paramètre.
