### ISSUE TITLE
[Information] Génération et gestion des mbtiles.

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/gn_mobile_occtax#235]
Bonjour à tous,

Je suis en cours de tests pour trouver le meilleur compromis de gestion des fichiers mbtiles afin de pouvoir les uploader sur le mobile en vue d'une utilisation hors réseau.

Actuellement je génère les mbtiles depuis QGIS pour une petite zone d'étude mais pour une zone comme un région ou un département, est-ce gérable ? 

J'utilise un zoom min : 12 et max 18 et OSM Standard pour le fond de carte.

Avez-vous des conseils/préconisation à me donner pour une meilleure utilisation des cartes hors réseau ?

Merci pour vos retours.

geonature : v 2.11
occtaxmobile : 2.6.1.3210

**Comment by naidinp** [comment]
> Bonjour,
> 
> A priori, sur une région il faudrait limiter un zoom max plus faible, sinon votre fichier mbtiles sera trop conséquent. Mais sur l'essentiel de la région, une utilisation online serait posible en général.
> 
> L'approche que j'ai en interne : quand on a des missions dans une zone blanche on arrive à le prévoir, on sort un mbtiles à l'occasion. Pour le reste on est sur des fonds online.
> 
> Si vraiment c'est dur d'anticiper ou de produire les fonds à la demande, voir s'il n'est pas possble de cartograhpier uniquement les zones blanches mais bon, c'est pas la solution miracle...

Bonsoir, 
Merci pour ce retour qui est très pertinent, je le note sur ma liste de choix.

**Comment by camillemonchicourt** [comment]
Au Parc national des Écrins on a généré des mbtiles précis et complets sur tout le territoire du parc avec Oruxmaps (mais QGIS Qtiles fait bien le job aussi) avec le SCAN 25 et les orthophotos précises. C'est un peu lourd mais ça fonctionne bien.

**Comment by gildeluermoz** [comment]
Pour le scan, une région ça passe en offline, peut être en limitant le dernier niveau (15 au lieu de 16) selon sa taille.
Pour l'ortho, c'est beaucoup trop lourd, comme déjà dit, il faut tuiler les zones d'étude ou utiliser les fonds online.
Je ne connais pas bien l'outil de qgis mais Mobac permet de choisir un niveau de compression des tuiles pour gagner un peu d'espace 70 est un bon compromis. Il permet aussi de dessiner le contour de la zone pour ne prendre que les tuiles utiles.

**Comment by naidinp** [comment]
> Pour le scan, une région ça passe en offline, peut être en limitant le dernier niveau (15 au lieu de 16) selon sa taille. Pour l'ortho, c'est beaucoup trop lourd, comme déjà dit, il faut tuiler les zones d'étude ou utiliser les fonds online. Je ne connais pas bien l'outil de qgis mais Mobac permet de choisir un niveau de compression des tuiles pour gagner un peu d'espace 70 est un bon compromis. Il permet aussi de dessiner le contour de la zone pour ne prendre que les tuiles utiles.

Top, merci pour ces idées également.
Je les note et je vais procéder aux tests pour essayer.
