### ISSUE TITLE
C'est quoi un taxon orphelin?

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_mobile_occtax#237]
Bonjour à tous,

petite question: qu'est-ce qu'un taxon orphelin qui est filtré lors de la synchronisation des référentiels?

J'ai un peut plus de 20000 taxons téléchargés mais 18059 taxons dispo à la saisie...

Merci d'avance pour votre éclairage!

**Comment by TheoLechemia** [comment]
d'après ce que ce que je comprend, ça semble être des taxons qui on été initalement récupéré depuis GeoNature via la synchronisation des taxons qui ne sont plus dans les listes remonté par la synchro aujourd'hui. Autrement dis=t des taxons qui aurait été supprimé de bib_nom ou des listes que le l'appli mobile synchronise.
Dis moi si je dis des bétises @sgrimault

**Comment by camillemonchicourt** [comment]
J'espère que la refonte de la synchro des taxons et des listes permettra de ne plus avoir à nettoyer les taxons orphelins et ainsi éviter cette étape un peu complexe et lourde ?

**Comment by DonovanMaillard** [comment]
> J'espère que la refonte de la synchro des taxons et des listes permettra de ne plus avoir à nettoyer les taxons orphelins et ainsi éviter cette étape un peu complexe et lourde ?

Oui puisqu'on chargera tout le taxref dans tous les cas, sans se soucier de savoir si le taxon est dans une liste ou non.

**Comment by sgrimault** [comment]
> d'après ce que ce que je comprend, ça semble être des taxons qui on été initialement récupéré depuis GeoNature via la synchronisation des taxons qui ne sont plus dans les listes remonté par la synchro aujourd'hui. Autrement dit des taxons qui aurait été supprimé de `bib_nom` ou des listes que le l'appli mobile synchronise. Dis moi si je dis des bêtises @sgrimault

Oui, c'est ça :
La synchronisation des taxons part toujours des données récupérées via l'API et si celle-ci comporte des taxons en moins, l'application supprime les anciens taxons toujours présents localement mais qui n'ont plus lieu d'être.

La synchronisation des taxons est en cours de refonte, notamment avec l'intégration des nouvelles APIs exposées par TaxHub et son fonctionnement sera donc plus simple :
* Uniquement si l'API indique une nouvelle "version" du référentiel des taxons ou que l'application ne possède aucun taxon en local
* Synchronisation transactionnelle qui part toujours d'une base vierge si elle est exécutée, donc plus besoin de déterminer si on a des taxons à supprimer par rapport aux nouveaux
* La synchronisation des taxons est considérée comme terminée avec succès si l'ensemble des appels à l'API s'est bien déroulée afin de marquer une date de dernière synchronisation des taxons, date qui sera ensuite utilisée et comparée avec celle indiquée coté API.
