### ISSUE TITLE
[2.7.0 RC3-dev] Problème de synchronisation taxons

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_mobile_occtax#238]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.7.0 RC3
Version de GeoNature utilisée : 2.13.3

### Terminal et Version Android

Marque et modèle du terminal : Pixel 6A
Version d'Android : 14

### Description du bug et comportement attendu

La synchronisation (Mettre à jour les données) se bloque après quelques secondes au moment de synchroniser les taxons. Dans les logs, j'ai : 
````
14:49:00.094 INFO: [fr.geonature.datasync.sync.usecase.DataSyncUseCase] taxa last synchronization date from remote: 2023-12-12T11:47:11Z
14:49:00.096 INFO: [fr.geonature.datasync.sync.usecase.DataSyncUseCase] synchronize taxa...
14:49:00.102 INFO: [fr.geonature.datasync.api.ClientKt] --> GET https://taxhub.biodiv-occitanie.fr/api/taxref?limit=10000&page=1
14:49:00.176 INFO: [fr.geonature.datasync.api.ClientKt] <-- HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to taxhub.biodiv-occitanie.fr not permitted by network security policy
14:49:00.188 WARN: [fr.geonature.datasync.sync.usecase.DataSyncUseCase] taxa synchronization finished with errors
14:49:00.695 WARN: [fr.geonature.datasync.sync.worker.DataSyncWorker] Synchronisation des taxons terminée avec des erreurs
14:49:00.701 INFO: [fr.geonature.datasync.sync.worker.DataSyncWorker] local data synchronization finished with failed tasks in 10443ms
````

J'avais réussi à réaliser la synchro en RC2, mais je ne pouvais pas synchroniser mes relevés saisis.
Dispo pour d'autres infos si besoin.

Merci.

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour sur cette version de test RC3 que je n'ai pas encore pu tester de mon côté.

**Comment by sgrimault** [comment]
Bonjour @JeromeMaruejouls,
C'est comme si le client HTTP a détecté une redirection HTTP (donc non sécurisée) lors des appels API lors de la synchronisation.
Par défaut, les appels APIs doivent se faire en HTTPS uniquement (pas d'appel en clair). L' erreur est d'ailleurs très clair :
`HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to taxhub.biodiv-occitanie.fr not permitted by network security policy`.

Autre point, je n'arrive pas à récupérer la configuration :
`GET -> https://geonature.biodiv-occitanie.fr/api/gn_commons/t_mobile_apps` me donne une 500

**Comment by camillemonchicourt** [comment]
Le soucis peut aussi venir que la 2.7.0-RC3 nécessite (de mémoire) les évolutions de la route `/taxref`, enrichie dans la version 1.13.1 de TaxHub (https://github.com/PnX-SI/TaxHub/releases) ?

**Comment by JeromeMaruejouls** [comment]
Effectivement, je n'avais pas vu les infos de compatibilité et je suis bien sur ce serveur en 1.12.1 (car GN 2.13).
C'est donc surement normal que la synchro ne fonctionne pas.
Par contre, l'erreur de requete en HTTP est quand même bizarre car mes accès sont bien en HTTPS.

Merci et je vous tiendrai au courant, quand j'aurai monté Taxref en 1.13.

**Comment by camillemonchicourt** [comment]
Oui si la RC3 recquiert la version 1.13.1 minimale de TaxHub, c'est un oubli de notre part de ne pas l'avoir indiqué dans les notes de version de la RC3.

**Comment by camillemonchicourt** [comment]
GeoNature 2.14 est sortie, compatible avec TaxHub 1.13.
Les versions 2.7-RC ne doivent servir que pour des tests, pas en production.
