### ISSUE TITLE
Etape 3 - Filtres sur espèces

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#24]
Filtre Statut de protection, Filtre Statut de patrimonialité, Filtre Priorité d'observation dans la maille (cat1, cat 2, cat 3), Filtre Règne, Filtre Groupe 2 INPN

@sgrimault Où en es tu sur cette fonctionnalité ?

**Comment by camillemonchicourt** [comment]
Attention, dans GN2, les attributs taxonomiques Patrimonialité et Protection n'existent plus par défaut. 
Donc il ne faut pas les mettre dans les filtres, du moins les rendre paramétrables. 
Chaque GN peut avoir ses propres attributs. 
Donc soit on zappe ces 2 filtres, soit il faut les rendre paramétrable (id_attribut et label).

OK pour les autres filtres.

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Je ne vois toujours aucun filtre pour limiter la liste des taxons à un groupe/couleur, etc

**Comment by sgrimault** [comment]
Le filtre sur les rangs taxonomique est déjà posé, il sera présent lors de la prochaine release de l'application.

**Comment by camillemonchicourt** [comment]
OK. Est-il possible de ne proposer que les règnes et groupes pour lesquels il y a des taxons ?

**Comment by ClaireLagaye** [comment]
Je viens de tester avec la version 0.2.9
Quand je clique sur un groupe ou un règne pour filtrer, je n'ai pas d'erreur mais Occtax revient sur l'écran d'accueil, il est impossible de filtrer.
Il faudrait en effet pouvoir limiter aux groupes de la liste de taxons, ici je me retrouve avec les bactéries et autres algues qui ne nous serviront pas pour l'instant

**Comment by sgrimault** [comment]
Je confirme le bug qui fait revenir à l'écran d'accueil.

**Comment by ClaireLagaye** [comment]
Test des filtres en version 0.2.6
Les filtres fonctionnent et réduisent bien la liste des taxons. Il est surtout très facile de supprimer les filtres.
Je trouve que la liste des rangs taxonomiques n'est pas assez dense. Il faudrait pouvoir n'avoir que les règnes au départ et n'accéder au group_inpn que quand on clique dessus.
J'enlèverai également l'item any à la fin de la liste

**Comment by ClaireLagaye** [comment]
Il faudrait pouvoir filtrer par la couleur de taxon, pour voir rapidement les espèces déjà vues dans la maille et voir les données à réactualiser

**Comment by camillemonchicourt** [comment]
Pour le filtre par couleur de taxons, c'est précisé sur https://github.com/PnX-SI/gn_mobile_occtax/issues/48

Pour les filtres taxonomique, est-il possible de ne proposer que les règnes et groupes pour lesquels il y a des taxons ?
