### ISSUE TITLE
Auto-zoom sur la position

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_mobile_occtax#245]
**Type d'amélioration**
ergonomie

**Proposition**
A l'arrivée sur la carte, est-ce qu'il ne serait pas interessant de zoomer automatiquement sur la position de l’utilisateur.
ça évite un clique sur le bouton "geoloc", toujours pratique sur le terrain

**Comment by camillemonchicourt** [comment]
Oui c'est le sujet qu'on a discuté récemment sur https://github.com/PnX-SI/gn_mobile_occtax/issues/241
