### ISSUE TITLE
failed to load 'settings_occtax.json'

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/gn_mobile_occtax#248]
Bonjour,

Je ne parviens pas à utiliser occtax mobile 2.6.1 branché sur le serveur de demo (ni sur mon serveur, d'ailleurs).

- Essais multiples sur smartphone Samsung Xcover 4 (android 9) et Xcover 6 (android 14),
- apk téléchargé sur github ou directement sur le serveur de démo  https://demo.geonature.fr/geonature/api/media/mobile/occtax/occtax-2.6.1-generic-release.apk
- Installation de l'apk, lancement de l'appli, saisie de l'url https://demo.geonature.fr/geonature

- La synchro initiale fonctionne (appel de la route `GET https://demo.geonature.fr/geonature/api/gn_commons/t_mobile_apps` ) 
- Le fichier  `/storage/emulated/0/Android/data/fr.geonature.occtax2/settings_occtax.json` est bien écrit dans la phase de synchro initiale.
- Il est possible de se loguer (admin/admin) et de se déloguer, mais rien d'autre ne marche.

- le fichier de log 
[occtax_20240301_170602.log](https://github.com/PnX-SI/gn_mobile_occtax/files/14463771/occtax_20240301_170602.log)
confirme que la récupération des settings a fonctionné, mais indique que occtax ne parvient pas à recharger ces settings.

- j'ai remarqué que dans le fichier settings_occtax.json, toutes les valeurs entières du fichier original (route GET) sont transformées en float. 
[settings_occtax.json](https://github.com/PnX-SI/gn_mobile_occtax/files/14463811/settings_occtax.json)

- J'ai aussi constaté que la base de données sqlite est créée de façon aléatoire (en général, il n'y en a pas, sauf à une ou deux occasions que je n'ai pas su qualifier).

Tout se passe comme si le module occtax n'avait pas les mêmes droits que le module sync, et ne pouvait ni lire ni écrire dans le dossier privé de l'application. Ou alors que le fichier `settings_occtax.json` est corrompu.

Merci de votre aide :-)

**Comment by camillemonchicourt** [comment]
Oui le serveur de DEMO vient d'être configuré pour fonctionner avec la 2.7 de test justement pour qu'on la teste.
Mais une modif qu'on teste fait que la 2.6 ne fonctionne plus pour le moment.

**Comment by camillemonchicourt** [comment]
Pour préciser : Pour la 2.7 de nouveaux paramètres ont été ajoutés pour activer ou non les champs additionnels. On a activé ce paramètre pour faire des tests de la 2.7.
Mais comme la 2.6 ne connait pas ce nouveau paramètre elle plante la récupération du fichier de configuration et le corromp.
C'est pas normal mais ça fait partie des tests et retours en cours...

**Comment by vprunet** [comment]
Merci pour l'info.
J'en suis quitte pour une après midi de prise de tête. :-)
En remplaçant l'url par celle de votre serveur de production, l'initialisation de occtax mobile est ok.

Je vais retourner sur mon serveur.

Je n'ai pas encore de données sur mon serveur. Est-ce que j'ai intérêt à  passer directement sur geonature 2.14 occtax 2.7 ?

**Comment by camillemonchicourt** [comment]
Oui désolé mais on ne peut pas garantir tout le temps le bon fonctionnement du serveur de DÉMO, surtout quand on a besoin de faire différents tests sur des développements en cours, comme actuellement sur la 2.7 du mobile.

Celle-ci n'est pas terminée ni officiellement sortie donc n'y passe pas, surtout que des soucis sont en cours de résolution.

Par contre tu peux passer à GeoNature 2.14 qui reste compatible avec Occtax-mobile 2.6.

**Comment by sgrimault** [comment]
Bonjour,
La version [2.6.2](https://github.com/PnX-SI/gn_mobile_occtax/releases/tag/2.6.2) corrige ce problème.
