### ISSUE TITLE
Bug sur ajout de média

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_mobile_occtax#254]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.6.1
Version de GeoNature utilisée : 2.13.3

### Terminal et Version Android

Marque et modèle du terminal : oukitel wp22
Version d'Android : 13

### Description du bug et comportement attendu

Lors de l'ajout d'un média (depuis l'appareil photo ou la galerie), l'ajout du media plante et revient directement vers l'écran n°1"Observateur et date) avec le bouton "suivant" figé (en grisé). Les infos sur l'espèce et le relevé sont perdues.

### Comment reproduire

Ajout d'un relevé
Ajout d'une localisation
Ajout d'un taxon
Ajout d'un média ==> bug à la validation du choix du media.

### Logs
[occtax_20240408_135110.log](https://github.com/PnX-SI/gn_mobile_occtax/files/14908780/occtax_20240408_135110.log)

Depuis la version 2.0.0 d'Occtax-mobile, vous pouvez récupérer le fichier de log dans votre terminal,
dans le répertoire `/Android/data/fr.geonature.occtax2`, récupérable depuis le téléphone jusqu'à
Android 10. Ou en branchant le terminal à un ordinateur depuis Android 11.

**Comment by camillemonchicourt** [comment]
Ça m'étonne car on a testé plusieurs fois la fonctionnalité.

En regardant tes logs, ceux-ci indiquent cette erreur : 
```
14:00:17.779 ERROR: [fr.geonature.occtax.MainApplication$TinylogUncaughtExceptionHandler] java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
```

Ce que je comprends c'est que le fichier est trop gros. Il fait 192 Mo ??? 🤔

**Comment by AudreyEnGuyane** [comment]
En effet par défaut les photos étaient en 6000*8000 (7.5 Mo) .
En jouant avec les réglages, en 3456*4608 (3.10 Mo)  les photos passent nickel sur Géonature. 
Donc problème résolu.

Mais peut-être faudrait-il prévoir un message dans l'appli en cas de photo/média trop lourd...

**Comment by camillemonchicourt** [comment]
Oui, du coup je rouvre ce ticket.

**Comment by sgrimault** [comment]
Bonjour @AudreyEnGuyane,
Oui effectivement l'image prise (en tant que photo depuis la caméra ou depuis la galerie) reste à l'état brute et si tu as effectivement un bon appareil qui peut prendre des images en haute résolution, ça ne va pas passer... :smiling_face_with_tear: 
Ce que je peux faire est de systématiquement faire un redimensionnement automatique de l'image prise avec une légère compression pour avoir toujours un poids par image raisonnable.
Si je fixe la taille de l'image (en respectant le ratio) à 1280px avec une qualité de 98%, ça vous irait ? Ça donnerait une image finale avec un poids d'environ 400 ~ 800 Ko.
Comme en plus on a aucune limite sur le nombre de photos par relevé...

**Comment by camillemonchicourt** [comment]
Je m'interroge si parfois cela n'est pas trop petit pour zoomer et valider.
Je dirai 2000 px.

Ou sinon plutôt redimensionner que si l'image dépasse une certaine taille ?

**Comment by sgrimault** [comment]
Je vais faire quelques tests.

**Comment by camillemonchicourt** [comment]
Le redimensionnement à 2000 pixels max ainsi que la compression JPEG à 80% ont été ajoutés ici : https://github.com/PnX-SI/gn_mobile_occtax/commit/5e6fa4c81e1ece81c8268bc38a4b0bc8aa5d4f66

**Comment by camillemonchicourt** [comment]
Fait dans la 2.7.0
