### ISSUE TITLE
bug connexion quand prénom pas renseigné dans usershub

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_mobile_occtax#258]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.6.2
Version de GeoNature utilisée : 2.14.1
usershub : 2.4.3

### Description du bug et comportement attendu

Lorsqu'on veut se connecter à occtax mobile, si le prénom n'est pas renseigné dans usershub, il y a une erreur et la connexion est impossible. Alors que la connexion est possible dans geonature desktop. 

comportement attendu : 
Etant donné que le champ Prénom n'est pas obligatoire dans usershub, il serait logique de pouvoir se connecter sans prénom à OM. (ou le prendre dans l'autre sens et rendre le champ Prénom obligatoire dans usershub et ne pas pouvoir se connecter à geonature desktop si le prénom est manquant ? )

### Comment reproduire

Aller dans usershub, créer un utilisateur sans toucher au champ prénom et essayer de se reconnecter avec OM. Ou mettre prenom_role à null directement en bdd dans utilisateurs.t_roles pour un utilisateur déjà existant. 

### Logs

06-14 09:53:02.187 17394 17432 W AuthManagerImpl: invalid user: missing 'firstname' attribute

**Comment by camillemonchicourt** [comment]
En effet, déjà remonté et identifié ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/184

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.7.0
