### ISSUE TITLE
Etape 3 - Recherche taxon

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#26]
Recherche taxon en français et en latin.
Recherche taxon en latin = OK

@sgrimault Quid sur la recherche en français en même temps que le latin ?

**Comment by sgrimault** [comment]
Le libellé en latin correspond-il à `label_default` dans la réponse coté GeoNature ?

**Comment by sgrimault** [comment]
Coté GeoNature, je prends pour l'instant l'attribut `lb_nom` comme libellé par défaut d'un taxon, les autres attributs `nom_valide` et `search_name` correspondent il respectivement au libellé en français et et au libellé à utiliser pour la recherche ?

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Pas de changement pour cette version
Il faudrait en effet avoir le nom français sous le nom latin pour chaque taxon avec la recherche qui irait taper dans les 2

**Comment by camillemonchicourt** [comment]
Au niveau de GeoNature, on a un champs de recherche qui interroge une vue qui remonte les noms français et latins dans un champs unique.

**Comment by DonovanMaillard** [comment]
Testé et très bien conçu pour nous. La recherche sur tout ou partie du nom nous arrange bien (quand on a que le nom d'espece et pas de genre par exemple).

**Comment by ClaireLagaye** [comment]
Recherche testée en français et en latin dans la version 0.2.6
