### ISSUE TITLE
[MAP] Configuration centrage et limite map  

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/gn_mobile_occtax#266]
### Version de l'application

Version d'Occtax-mobile : 2.6.2
Version de GeoNature utilisée : 2.14.2

### Question 

Bonjour ,

Dans le cadre de l'utilisation de l'application mobile pour la DREAL Corse , le problème rencontré est l'impossiblité de se déplacer (charger la map) sur le coté Est et Sud de la Corse.
Le fichier de config a été modifié , pour mettre les valeurs suivantes centrées sur la corse : "center": [42.177, 9.602]. Mais le problème persiste .

Est ce qu'il y a d'autres paramètres à modifier (je pense à celui ci par exemple : "max_bounds": [
        [52.0, -6.0],
        [41.0, 9.0]
      ],
) ? 
Merci d'avance

**Comment by camillemonchicourt** [comment]
J'ai pas compris, tu as modifié `max_bounds` ?
Car en effet, avec les valeurs par défaut, tu seras logiquement bloqué.

**Comment by andriacap** [comment]
Ok merci
