### ISSUE TITLE
Champs additionnels : échec

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_mobile_occtax#269]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.7.0
Version de GeoNature utilisée : 2.14

### Terminal et Version Android

Marque et modèle du terminal : Crosscals Action-X5
Version d'Android : 12

### Description du bug et comportement attendu

Suite à la montée en version de GeoNature et TaxHub, nous voulons monter également en version pour OccTax-mobile, pour pouvoir notamment utiliser les champs additionnels (au nouveau des occurrences et dénombrements pour l'instant).
Si la synchronisation du référentiel taxonomique est capricieuse, j'ai un échec sur le téléchargement des champs additionnels.
Pourtant, la route renvoie bien la liste des champs additionnels et en dénombre 27...

> 11:36:05.712 INFO: [fr.geonature.datasync.api.ClientKt] <-- 200 OK https://gnpag.brgm-rec.fr/geonature/api/gn_commons/additional_fields?module_code=OCCTAX (1909ms, 75356-byte body)
> 11:36:06.459 INFO: [fr.geonature.datasync.sync.repository.SynchronizeAdditionalFieldsRepositoryImpl] 27 additional field(s) found
> 11:36:07.021 WARN: [fr.geonature.datasync.sync.worker.DataSyncWorker] Champs additionnels : échec

Le test que j'ai effectué avec demo.geonature.fr fonctionne jusqu'au bout donc ça doit venir de mon instance. 
En amont, le formatage des champs de type radio/select/... a bien été révisé afin de correspondre au standard spécifié dans le backoffice/champs additionnels "_select/multiselect/checkbox,radio (Format JSON : tableau de 'value/label'. Utilisez des doubles quotes pour les valeurs et les clés). Exemple [{"label": "trois", "value": 3}, {"label": "quatre", "value": 4}]_ "
Est-ce que ce serait lié à ça? 
Sur le site de démo, la forme de ces champs varie de la forme ["valeur1", "valeur2", "valeur3"] ==> https://demo.geonature.fr/geonature/api/admin/tadditionalfields/edit/?id=3&url=/geonature/api/admin/tadditionalfields/
à la syntaxe json attendue ==> https://demo.geonature.fr/geonature/api/admin/tadditionalfields/edit/?id=22&url=/geonature/api/admin/tadditionalfields/

### Comment reproduire

Installer occtax 2.70, saisir l'instance de GN, laisser synchroniser...

### Logs

cf. PJ: les logs d'occtax mobile et le fichier json de config 
[occtax_20241003_110547.log](https://github.com/user-attachments/files/17247622/occtax_20241003_110547.log)

[settings.json](https://github.com/user-attachments/files/17247623/settings.json)

**Comment by camillemonchicourt** [comment]
OK j'ai 2 pistes d'explication sur le sujet : 

- Il est possible de rendre inactif un JDD quand celui-ci est terminé. Cependant on le conserve dans la BDD et il peut avoir des champs additionnels associés. Cependant on le renvoie pas dans l'API quand on demande les JDD ouverts à la saisie. Ainsi on peut retourner des champs additionnels associés à des JDD qui ne sont plus disponibles à la saisie et donc pas renvoyés dans Occtax-mobile
- Il est possible qu'un utilisateur n'ait pas les permissions d'accéder à un JDD donc l'API ne lui renvoie pas, mais il recevra quand même les éventuels champs additionnels associés à ce JDD

Il est donc très important qu'Occtax-mobile ne plante pas quand on lui renvoie des champs additionnels associés à ces JDD mais qu'il ne connaisse pas ces JDD (car inactifs ou car l'utilisateurs n'a pas les permissions sur ces JDD).

Une correction est donc nécessaire au niveau d'Occtax-mobile.

**Comment by sgrimault** [comment]
Je vais faire une petite correction coté module de synchronisation lors du traitement des champs additionnels. Le lien avec des éventuels jeux de données pour chaque champ additionnel ne se fera que si le jeu de donnée existe bien en base lors de la synchronisation.
Dans le cas du problème remonté par @AudreyEnGuyane, le champ additionnel en question ne sera affecté à aucun jeu de donnée.

**Comment by camillemonchicourt** [comment]
Si un champs additionnel est associé à un ou plusieurs JDD, il ne faut l'associer à aucun dans le cas où l'on ne connait pas les JDD en question.
Mais bien ignorer ces champs additionnels.

Le cas d'Audrey concerne des champs additionnels associés à aucun JDD ?

**Comment by sgrimault** [comment]
Le cas d'Audrey concerne un champs additionnel affecté à un jeu de donnée inconnu coté "Occtax", lors de la synchronisation. Donc dans ce cas, il faut tout simplement ignorer ce champ additionnel ?

**Comment by camillemonchicourt** [comment]
> Le cas d'Audrey concerne un champs additionnel affecté à un jeu de donnée inconnu coté "Occtax", lors de la synchronisation. Donc dans ce cas, il faut tout simplement ignorer ce champ additionnel ?

Oui très important.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.7.1
