### ISSUE TITLE
Etape 4 Informations - Choix dans liste déroulante

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#27]
Mettre 'Choisir' au lieu de 'Ajouter' pour les noms des boutons d'accès aux listes déroulantes de 'Informations' et 'Informations avancées'

**Comment by camillemonchicourt** [comment]
Normalement, il y aura des valeurs par défaut renseignées pour chaque nomenclature (https://github.com/PnX-SI/gn_mobile_occtax/issues/3), donc on pourrait même imaginer utiliser le terme ``Modifier`` ?

**Comment by camillemonchicourt** [comment]
La route pour récupérer les nomenclatures par défaut : https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/backend/blueprint.py#L495

**Comment by camillemonchicourt** [comment]
Actuellement la route, ne renvoie qu'une valeur par type de nomenclature.
Du coup on ne peut pas dissocier des valeurs par défaut par règne ou Group2INPN pour le moment.
On reste comme ça, personne n'ayant de nomenclature par défaut définis par règne ou Group2INPN pour le moment.
