### ISSUE TITLE
Màj Occtax mobile de 1.3 à 2.7

### ISSUE THREAD

**Issue by aferchal** [PnX-SI/gn_mobile_occtax#270]
Suite à des tests avec Ludovic LP, ci-dessous les messages d'erreur obtenus sur un Android 10 (XCover4) lors de l'essai de la mise à jour :

`17:07:08.904 INFO: [fr.geonature.occtax.MainApplication] starting fr.geonature.occtax2 (version 2.7.0)...
17:07:08.906 INFO: [fr.geonature.occtax.MainApplication] logs directory: '/storage/emulated/0/Android/data/fr.geonature.occtax2/logs'
17:07:08.907 INFO: [fr.geonature.occtax.MainApplication] internal storage: 'MountPoint(mountPath=/storage/emulated/0, storageType=INTERNAL)'
17:07:08.908 INFO: [fr.geonature.occtax.MainApplication] external storage: 'MountPoint(mountPath=/storage/152C-3841, storageType=EXTERNAL)'
17:07:09.204 INFO: [fr.geonature.commons.data.DatabaseModule] loading local database '/storage/emulated/0/Android/data/fr.geonature.occtax2/databases/data.db'...
17:07:09.217 INFO: [fr.geonature.datasync.features.settings.usecase.UpdateSettingsFromRemoteUseCase] loading app configuration...
17:07:09.219 INFO: [fr.geonature.datasync.settings.DataSyncSettingsFileDataSourceImpl] loading data sync settings from '/storage/emulated/0/Android/data/fr.geonature.occtax2/settings_occtax.json'...
17:07:09.220 WARN: [fr.geonature.datasync.settings.DataSyncSettingsFileDataSourceImpl] '/storage/emulated/0/Android/data/fr.geonature.occtax2/settings_occtax.json' not found
17:07:09.247 WARN: [fr.geonature.occtax.ui.home.HomeActivity] failed to load settings from source '/storage/emulated/0/Android/data/fr.geonature.occtax2/settings_occtax.json'
17:07:09.629 INFO: [fr.geonature.datasync.packageinfo.worker.CheckInputsToSynchronizeWorker] available inputs to synchronize: 0
17:07:45.860 INFO: [fr.geonature.datasync.features.settings.usecase.GetAppSettingsFromRemoteUseCase] loading app configuration from 'https://gngua.brgm-rec.fr/geonature'...
17:07:45.863 INFO: [fr.geonature.datasync.api.GeoNatureAPIClientImpl] set server base URLs (GeoNature: 'https://gngua.brgm-rec.fr/geonature')...
17:07:45.938 INFO: [fr.geonature.datasync.api.ClientKt] --> GET https://gngua.brgm-rec.fr/geonature/api/gn_commons/t_mobile_apps
17:07:47.718 INFO: [fr.geonature.datasync.api.ClientKt] <-- 200 OK https://gngua.brgm-rec.fr/geonature/api/gn_commons/t_mobile_apps (1778ms, 917-byte body)
17:07:47.738 ERROR: [fr.geonature.datasync.features.settings.usecase.GetAppSettingsFromRemoteUseCase] package info 'fr.geonature.occtax2' not found from 'https://gngua.brgm-rec.fr/geonature': abort
17:12:14.492 INFO: [fr.geonature.datasync.features.settings.usecase.GetAppSettingsFromRemoteUseCase] loading app configuration from 'https://gngua.brgm-rec.fr/geonature'...
17:12:14.493 INFO: [fr.geonature.datasync.api.GeoNatureAPIClientImpl] set server base URLs (GeoNature: 'https://gngua.brgm-rec.fr/geonature')...
17:12:14.507 INFO: [fr.geonature.datasync.api.ClientKt] --> GET https://gngua.brgm-rec.fr/geonature/api/gn_commons/t_mobile_apps
17:12:16.287 INFO: [fr.geonature.datasync.api.ClientKt] <-- 200 OK https://gngua.brgm-rec.fr/geonature/api/gn_commons/t_mobile_apps (1778ms, 917-byte body)
17:12:16.295 ERROR: [fr.geonature.datasync.features.settings.usecase.GetAppSettingsFromRemoteUseCase] package info 'fr.geonature.occtax2' not found from 'https://gngua.brgm-rec.fr/geonature': abort
17:22:13.293 INFO: [fr.geonature.datasync.packageinfo.worker.CheckInputsToSynchronizeWorker] available inputs to synchronize: 0
`

**Comment by sgrimault** [comment]
Bonjour @aferchal,

La configuration coté GeoNature me semble correcte (cf. https://gngua.brgm-rec.fr/geonature/api/gn_commons/t_mobile_apps) et je retrouve les informations liées à l'application (package `fr.geonature.occtax2`).
Pourriez vous retester de nouveau si jamais vous aviez modifié la configuration entre temps ?

**Comment by camillemonchicourt** [comment]
Oui oui ça a été corrigé entre temps en renommant la package occtax en occtax2 et ça à résolu le soucis.
