### ISSUE TITLE
[Interface] Dénombrement : saisir le décompte au clavier

### ISSUE THREAD

**Issue by PaulLabruyere** [PnX-SI/gn_mobile_occtax#271]
**Type d'amélioration**
Ergonomie

**Proposition**
Bonjour,

Un de nos utilisateurs nous remonte une demande liée à l'interface concernant les  champs "Min" et "Max" de l'onglet "dénombrement".

Actuellement, ces champs ont une valeur de 1 par défaut, et peuvent être modifiés via une "molette"

![min_max](https://github.com/user-attachments/assets/febba695-bf65-406f-b709-f109ff8e8d00)

Ce fonctionnement convient à la plupart des cas de figure : on note rarement plus de quelques individus. Toutefois, le jour où notre utilisateur a voulu saisir 200 vanneaux huppés aperçus dans un champs, l'interface s'est révélée insuffisante ^^ Il aurait alors préféré saisir le dénombrement au clavier numérique dans une zone de texte.

Évidemment, si on modifie ce champ à l'échelle de l'application (par exemple dans les settings), on aura d'autres utilisateurs qui vont râler parce que c'est moins simple quand on veut passer de 1 à 2 individus. La solution idéale pourrait donc être d'avoir un petit bouton à côté des molettes pour passer en saisie "texte", un peu sur le modèle de ce qui se fait avec les dates / heures pour swicher entre calendrier/horloge et saisie manuelle ?

![date](https://github.com/user-attachments/assets/e7fc53f8-ee91-4318-9980-dc408bdde89f)

De ce que je vois dans notre base, ça concernerait surtout certaines espèces d'oiseaux et d'insectes, et pas dans la majorité des cas. Ce n'est donc pas une demande urgente, j'ouvre ce ticket pour garder trace et lancer la discussion. Je peux creuser de mon côté si une bonne âme m'indique à quel(s) endroit(s) se gère l'interface dans le code source (idéalement la partie counting et la partie date pour avoir un exemple).

MErci d'avance et bonne journée !

**Comment by sgrimault** [comment]
Bonjour @PaulLabruyere,

Vous avez la possibilité de saisir directement la valeur numérique en "tapant" directement sur la valeur actuelle :
<img src="https://github.com/user-attachments/assets/837b98f9-000b-4169-8522-f64ad0df9972" width="512">

**Comment by camillemonchicourt** [comment]
> Bonjour @PaulLabruyere,
> 
> Vous avez la possibilité de saisir directement la valeur numérique en "tapant" directement sur la valeur actuelle.

Ah bah oui, je me disais bien aussi que c'était déjà possible. Merci du retour.
