### ISSUE TITLE
Etape initiale - Relevés en cours

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#28]
On peut supprimer des relevés en faisant un clic long sur le relevé.
Peut être que le mieux serait un petit bouton 'Suppression' sur chaque relevé avec un message de confirmation pour éviter des suppressions non souhaitées.
Quelle que soit la méthode choisie, je pense qu'il faut un message de confirmation de suppression.

**Comment by ClaireLagaye** [comment]
**Test de la version 0.2.5**
Il est possible d'annuler la suppression avec le message qui s'affiche en bas de l'écran après le clic long
Est-ce suffisant?

**Comment by DonovanMaillard** [comment]
Actuellement, on peut supprimer un relevé (un appui long peut etre malheureux ou malencontreux, peut être qu'une confirmation serait utile?). 

On peut aussi le modifier... mais la modification est pour le moment peu optimisée. On doit reprendre une à une toutes les étapes. Ne serait il pas plus simple de lister les étapes et sélectionner directement celle dans laquelle on souhaite faire une modification (dénombrement, liste de taxons etc?). Ca éviterait, notamment de repasser sur la carte, qui redemande une localisation...

**Comment by camillemonchicourt** [comment]
Ce n'est pas prévu pour le moment.
Par contre ce n'est pas normal qu'une modification nécessite de relocaliser le relevé. Le marqueur devrait garder sa localisation initiale que l'on peut éventuellement modifier
