### ISSUE TITLE
Etape 4 Informations - Informations avancées

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#29]
Voir au niveau ergonomique ce qui est le mieux pour afficher les informations avancées.
- Afficher les champs supplémentaires en dessous comme actuellement, quitte à avoir un bouton pour replier le bloc Informations avancées
- Passer dans une page spécifique avec le retour via la petite flèche en haut à gauche

Plutôt qu'avoir un bouton 'Ajouter' ou 'Modifier' mettre une flèche qui montre que Informations avancées est un bloc non pas une liste déroulante.

**Comment by ClaireLagaye** [comment]
0.2.6, fonctionnement attendu
