### ISSUE TITLE
Valeurs par défaut

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_occtax#3]
A la vue du chemin utilisateur, je me suis (re)posé une question. Désolé si on avait abordé le point dans notre première réunion mais je ne m'en rappelle plus. 

Est-ce que, comme pour la synthèse, on peut définir des valeurs par défaut dans la configuration de l'application pour les différentes nomenclatures, voire le dénombrement (si non détaillé = 1) par exemple?

**Comment by camillemonchicourt** [comment]
Comme pour Occtax web, l'application mobile utilisera les valeurs par défaut des nomenclatures définies dans la BDD de GeoNature

**Comment by DonovanMaillard** [comment]
Top, merci !
