### ISSUE TITLE
Etape 5 Dénombrement - Choix dans liste déroulante

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#30]
Mettre 'Choisir' au lieu de 'Ajouter' pour les noms des boutons d'accès aux listes déroulantes.

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/gn_mobile_occtax/issues/27
Maintenant qu'on a des valeurs par défaut renseignés dans les nomenclatures, le terme ``Choisir`` porte à confusion car il laisse penser qu'il faut cliquer dessus pour CHOISIR la valeur, alors que l'on peut laisser comme ça et uniquement MODIFIER si l'on veut utiliser une autre valeur que la valeur par défaut. 

![Screenshot_20200125-165507_OccTax](https://user-images.githubusercontent.com/4418840/73123773-f4eaea80-3f93-11ea-939a-a1c3d94440a4.jpg)

Il vaut mieux donc mieux utiliser le terme ``Modifier`` comme dans l'étape Observateur et Jeu de données : 

![Screenshot_20200125-165444_OccTax](https://user-images.githubusercontent.com/4418840/73123779-0d5b0500-3f94-11ea-9374-244f80398bab.jpg)
