### ISSUE TITLE
Etape 5 Dénombrement - Dénombrements courants

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#32]
On peut supprimer des dénombrements en faisant un clic long sur le dénombrement.
Peut être que le mieux serait un petit bouton 'Suppression' sur chaque dénombrement avec un message de confirmation pour éviter des suppressions non souhaitées.
Quelle que soit la méthode choisie, je pense qu'il faut un message de confirmation de suppression.

**Comment by ClaireLagaye** [comment]
> Test de la version 0.2.5
Il est possible d'annuler la suppression avec le message qui s'affiche en bas de l'écran après le clic long
Est-ce suffisant?

**Comment by DonovanMaillard** [comment]
Je trouve par ailleurs que la saisie d'un dénombrement est peu intuitive. 

- 1 : on arrive sur une page blanche, une action supplémentaire est nécessaire pour créer un dénombrmeent (de toutes facons obligatoire). Je verrais mieux, par défaut, la page qui permet de saisir le dénombrement. 
- 2 : Quand on finit un dénombrement actuellement, il faut faire un "retour arrière" pour le valider sauf erreur de ma part... peu intuitif, en général utilisé pour annuler ou revenir en arrière, mais pas pour valider une saisie. 

Je verrais mieux une arrivée directmeent sur la page de saisie avec les menus. Et quand on appuie sur + (qui reste présent sur cette page de saisie)  ca valide le 1er dénombrement, ca le réduit en une ligne en haut de page, et ca réinitialise les menus déroulants pour saisir le dénombrement suivant. 

C'est une idée, mais ca nécessiterait moins d'allers retours et d'actions obligatoires de la part de l'utilisateur. L'objectif du mobile étant de saisir à la volée en simplifiant et accélérant au maximum la saisie.

**Comment by camillemonchicourt** [comment]
Oui je confirme aussi que le fonctionnement actuel est moins intuitif.

**Comment by sgrimault** [comment]
J'ai changé un peu le comportement par défaut vu que de toute façon il faut au moins un dénombrement pour valider la saisie :
* Lors de la première fois, l'utilisateur est automatiquement redirigé vers la page d'ajout d'un dénombrement.
* Il peut quitter cette saisie à tout moment en faisant "back", celle-ci sera automatiquement sauvegardée et ajoutée en tant que nouveau dénombrement.
* La page de récapitulatif des dénombrements permet de lister les dénombrements réalisés, l'utilisateur peut revenir pour chacun d'entre eux en cliquant simplement dessus.
* L'ajout d'un dénombrement se fait via le bouton "+"
* La suppression d'un dénombrement se fait via un toucher long, une barre de notification apparaît sur laquelle l'utilisateur peut annuler l'action de suppression

**Comment by ClaireLagaye** [comment]
Test en version 0.2.9
En effet le dénombrement fonctionne mieux et la page récapitulative des dénombrements est très bien.
Comportement étrange constaté ce jour: en créant un dénombrement, si je modifie le nombre d'individus (=100) et que je fais un retour arrière je reviens à l'écran de dénombrement par défaut avec les nombres remis à 1.  Si je refais un retour arrière j'arrive à la page de récapitulatif des dénombrements et là j'ai 2 dénombrements pour une espèce (100 individus et 1 individu) alors que je n'en ai mis qu'un.

**Comment by sgrimault** [comment]
Je n'arrive pas à reproduire ce bug. Coté gestion de la saisie, l'application génère un identifiant unique lors de la création d'un dénombrement, pour les distinguer facilement. C'est à partir de cet identifiant que l'on peut éditer/supprimer un dénombrement de la liste.

**Comment by ClaireLagaye** [comment]
Bug non reproduit en 0.2.6
