### ISSUE TITLE
Etape 5 Dénombrement - Infos sur dénombrements

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#33]
Sur chaque dénombrement les valeurs des différents champs s'affichent en dessous.
2 solutions
- Afficher de façon lisible toutes les infos sur chaque dénombrement => Cela peut être intéressant pour les utilisateurs pour s'y retrouver. D'un autre coté cela peut surcharger la page s'il y a de nombreux dénombrements. Cela peut être compliqué sur le terrain avec des infos affichées en petit
- Afficher que les numéros dénombrement sachant qu'en cliquant dessus on retourne sur la page de saisie.
Mon avis : Je pense qu'il est intéressant pour les utilisateurs d'avoir les infos qui s'affichent sur chaque dénombrement, mais il faut trouver une solution ergo et lisible sur le terrain.
Même réflexion #34 
Qu'en pensez vous ? @sgrimault @camillemonchicourt @gildeluermoz @TheoLechemia

**Comment by ClaireLagaye** [comment]
> Test de la version 0.2.5
Cela fonctionne, le résumé est présent mais difficilement lisible. Peut-être mettre le nombre en premier?

**Comment by ClaireLagaye** [comment]
Fonctionnement qui nous convient en 0.2.6
