### ISSUE TITLE
Etape initiale - Infos sur relevés

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#34]
2 solutions
- Afficher de façon lisible les infos clés sur chaque relevé => Cela peut être intéressant pour les utilisateurs pour s'y retrouver. D'un autre coté cela peut surcharger la page s'il y a de nombreux relevés. Cela peut être compliqué sur le terrain avec des infos affichées en petit
- Afficher que les numéros de relevé sachant qu'en cliquant dessus on retourne sur la page de saisie.
Mon avis : Je pense qu'il est intéressant pour les utilisateurs d'avoir les infos clés qui s'affichent sur chaque relevé, mais il faut trouver une solution ergo et lisible sur le terrain.
Il faut aussi définir les infos clés à afficher.
Même réflexion que #33 
Qu'en pensez vous ? @sgrimault @camillemonchicourt @gildeluermoz @TheoLechemia

**Comment by ClaireLagaye** [comment]
> Test de la version 0.2.5
Peut-être juste la date du relevé et le nombre de taxon saisis?

**Comment by camillemonchicourt** [comment]
Oui je pense aussi

**Comment by ClaireLagaye** [comment]
Version 0.2.6, fonctionnement attendu
