### ISSUE TITLE
Etape 6 Bilan - Infos sur saisie

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#35]
@sgrimault Où en es tu sur cette étape ?

**Comment by sgrimault** [comment]
Elle est terminée : Elle liste les taxons saisis et pour chacun on peut rééditer ses propriétés en redirigeant vers les étapes 4 et 5. L'ajout d'un taxon se fait via le bouton "+" qui fait une redirection vers l'étape 3.

**Comment by ClaireLagaye** [comment]
> Test de la version 0.2.5
En effet cela fonctionne.
Est-ce qu'il ne faudrait pas ajouter un recap des dénombrements?

**Comment by ClaireLagaye** [comment]
En version 0.2.6
Semble fonctionner avec le comportement attendu
