### ISSUE TITLE
URL des routes par défaut

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#36]
Il ne faudrait pas intégrer en dur dans les routes ``/geonature/`` au début de chaque route, car l'application n'est pas toujours à l'URL ``mondomaine/geonature``. Elle est plus souvent sur ``geonature.mondomaine`` sans ``/geonature/`` à la suite.

Du coup sur le serveur de démo, l'URL renseignée devrait plutôt être ``http://demo.geonature.fr/geonature`` plutôt que ``http://demo.geonature.fr`` avec ``/geonature/`` ajouté en dur à la suite.

**Comment by DonovanMaillard** [comment]
Idem pour nous, on a pas pu tester sur notre instance pour le moment, car elle est à la racine de son sous domaine. Le /geonature/ est donc bloquante pour nous.

**Comment by sgrimault** [comment]
Certaines routes commencent aussi par `taxhub`, au même niveau que le segment `geonature`. Par exemple pour l'instance de demo, j'ai à la fois la route `<BASE_URL>/geonature/api/meta/datasets` que `<BASE_URL>/taxhub/api/taxref/regnewithgroupe2`, où BASE_URL = `http://demo.geonature.fr`.

Du coup, si certaines instances pointent directement sur `geonature/`, comment ça se traduit pour les URLs commencant par `taxhub` ? `geonature/taxhub/` ?

**Comment by camillemonchicourt** [comment]
A oui bien vu. L'application a besoin de routes de GeoNature mais aussi de routes interrogeant directement TaxHub.
C'est pour ça que dans GeoNature on paramètre les URL des 2 API : https://github.com/PnX-SI/GeoNature/blob/master/config/geonature_config.toml.sample

Il va donc peut être falloir paramétrer aussi les URL des 2 API au niveau de l'application Sync-mobile aussi du coup...

**Comment by camillemonchicourt** [comment]
OK, à partir de la version 0.2.2 de Sync-mobile, on doit configurer l'URL de GeoNature et de TaxHub.
Valeurs à utiliser pour le serveur de démo : 
- GeoNature : http://demo.geonature.fr/geonature
- TaxHub : http://demo.geonature.fr/taxhub
