### ISSUE TITLE
Route de récupération des taxons

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#37]
En testant l'application 0.25 qui est branchée sur le serveur de démonstration (http://demo.geonature.fr), j'ai identifié que la route qui permet de récupérer la liste des taxons n'est pas bonne. 

En effet, l'application ne contient que 20 taxons. Hors la liste 100 de saisie Occtax contient tous Taxref, soit 536442 noms d'espèces...
C'est surement car l'application se base sur la route http://demo.geonature.fr/taxhub/api/taxref/allnamebylist/100 qui limite à 20 résultats (https://github.com/PnX-SI/TaxHub/blob/master/apptax/taxonomie/routestaxref.py#L347)

**Comment by sgrimault** [comment]
@camillemonchicourt 
Du coup quelle serait la route à appeler pour avoir l'intégralité de tous les taxons ?
La route http://demo.geonature.fr/taxhub/api/taxref est aussi paginée par défaut.

**Comment by camillemonchicourt** [comment]
Je ne sais pas qu'elle serait la bonne route. 
Et il faut peut-être en ajouter une sur mesure pour les besoins de l'application mobile ?

**Comment by sgrimault** [comment]
En attendant d'avoir une route dédiée (ou sans filtres), je vais changer l'appel pour y inclure une limite très grande. Ce qui donnera ceci :

`/taxhub/api/taxref/allnamebylist/100?limit=1000000`

**Comment by camillemonchicourt** [comment]
OK merci.

**Comment by sgrimault** [comment]
Ce n'est finalement pas aussi simple que ça :)

Les données remontées par cette route sont trop volumineuses et je saute les limites possibles. J'ai pu les contourner mais maintenant, le problème vient du fait que la connexion est coupée avant même d'avoir pu récupérer l'intégralité du flux. Du coup, je me retrouve avec une réponse JSON invalide...

Deux solutions possibles :
* faire une route dédiée qui retourne un stream
* compléter la route existante pour qu'elle gère la pagination (`limit` et `offset`) et y faire appel autant que fois que cette route retourne des données selon offset. C'est moins performant (une bonne dizaine d'appels si on fixe un offset à 50000), mais sans doute plus facile et rapide à mettre en œuvre

**Comment by camillemonchicourt** [comment]
OK je vois.
Comme évoqué précédemment, on n'aura souvent une liste plus limitée. Un peu plus de 6000 taxons dans notre cas au PNE.

Cependant certaines instances de GeoNature utilisent tout le référentiel Taxref pour la saisie Occtax (plus de 500000 taxons) comme c'est le cas sur le serveur de démo. Donc autant prévoir cette possibilité en effet.

**Comment by TheoLechemia** [comment]
Fait sur branche `develop`. L'ajout du paramètre `offset` en querystring permet d'appeler la route à plusieurs reprises en paginant les résultats.

**Comment by sgrimault** [comment]
@TheoLechemia 
Il faudrait appliquer les mêmes paramètres sur la route `/api/synthese/color_taxon` potentiellement plus volumineuse que la route des taxons.

Sur l'instance de test du parc de la Vanoise, je saute les limites aussi (~13MB de JSON à charger/parser).

**Comment by TheoLechemia** [comment]
@sgrimault Fait sur la route ``synthese/color_taxon`` également
