### ISSUE TITLE
Thème couleurs

### ISSUE THREAD

**Issue by sgrimault** [PnX-SI/gn_mobile_occtax#4]
### Thème couleurs par parc nationaux

Parc | `primary` | `dark` | `accent`
---|---|---|---
Les Écrins | ![#81197f](https://via.placeholder.com/32/81197f) | ![#510052](https://via.placeholder.com/32/510052) | ![#00a3de](https://via.placeholder.com/32/00a3de)
La Vanoise | ![#004494](https://via.placeholder.com/32/004494) | ![#001e65](https://via.placeholder.com/32/001e65) | ![#78b74a](https://via.placeholder.com/32/78b74a)
Le Mercantour | ![#79b63e](https://via.placeholder.com/32/79b63e) | ![#488603](https://via.placeholder.com/32/488603) | ![#ce4f18](https://via.placeholder.com/32/ce4f18)
Les Cévennes | ![#f39400](https://via.placeholder.com/32/f39400) | ![#ba6600](https://via.placeholder.com/32/ba6600) | ![#95a9c9](https://via.placeholder.com/32/95a9c9)

### Thème par défaut

`primary` | `dark` | `accent`
---|---|---
![#43a047](https://via.placeholder.com/32/43a047) | ![#00701a](https://via.placeholder.com/32/00701a) | ![#f4511e](https://via.placeholder.com/32/f4511e)

Inspiré de l'ancienne [charte graphique des parcs nationaux](http://www.ecrins-parcnational.fr/sites/ecrins-parcnational.com/files/page/9241/chartegraphiquepnx.pdf).

**Comment by camillemonchicourt** [comment]
OK, paramétrable pour les autres structures qui utiliseront Occtax mobile.

**Comment by camillemonchicourt** [comment]
Ne devrait-on pas proposer une version neutre par défaut pour ceux qui auront pas la capacité de repackager une version à leur couleur ?
Et proposer en bonus une version aux couleurs PNV et une PNE ?

**Comment by sgrimault** [comment]
C'est déjà prévu en appliquant simplement le thème par défaut.

Dans tous les cas, ce sera assez facile de générer des nouvelle déclinaisons selon le thème par parc national.

**Comment by camillemonchicourt** [comment]
OK j'ai pas encore bien compris les pré-requis.
Mais il faudra quand même avoir l'environnement de développement Android et un peu le comprendre pour déployer une APK à ses couleurs, non ?

**Comment by sgrimault** [comment]
Oui, dans tous les cas, il faudra au minimum le JDK 8 et Android Studio pour pouvoir lancer le build.

Je documenterai cette partie là, notamment comment personnaliser l'application.

**Comment by camillemonchicourt** [comment]
Si possible, générer aussi les APK pour chaque release aussi les versions PnCévennes et PnMercantour.

Pour la version par défaut, elle sera utilisée plus largement que par d'autres parcs nationaux. 
Et la charte graphique générale des parcs nationaux n'est plus d'actualité.

Donc pour la version par défaut : 
- Ne plus préfixer la version par défaut avec le terme "pnx", mais plus "" ou "generic" ou "default"
- Utiliser plutôt une palette de vert, en lien avec la thématique "Nature" de GeoNature, par exemple #3c9f3e. Et en complément pour les textes par exemple #F05F40
