### ISSUE TITLE
Nomenclatures triées par ordre alphabétique

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#42]
Il serait plus lisible que les valeurs des listes déroulantes soient triées par ordre alphabétique.

**Comment by sgrimault** [comment]
De la route `/geonature/api/nomenclatures/nomenclatures/taxonomy`, j'applique le tri sur les valeurs selon l'attribut `hierarchy`. Exemple :

```json
{
  "id_type": 7,
  "mnemonique": "ETA_BIO",
  "label_default": "Etat biologique de l'observation",
  "nomenclatures": [
    {
      "mnemonique": "NSP",
      "label_default": "NSP",
      "cd_nomenclature": "0",
      "taxref": [
        {
          "group2_inpn": "all",
          "regne": "all"
        }
      ],
      "id_nomenclature": 155,
      "hierarchy": "007.000"
    },
    {
      "mnemonique": "Non renseigné",
      "label_default": "Non renseigné",
      "cd_nomenclature": "1",
      "taxref": [
        {
          "group2_inpn": "all",
          "regne": "all"
        }
      ],
      "id_nomenclature": 156,
      "hierarchy": "007.001"
    },
    {
      "mnemonique": "Observé vivant",
      "label_default": "Observé vivant",
      "cd_nomenclature": "2",
      "taxref": [
        {
          "group2_inpn": "all",
          "regne": "all"
        }
      ],
      "id_nomenclature": 157,
      "hierarchy": "007.002"
    },
    {
      "mnemonique": "Trouvé mort",
      "label_default": "Trouvé mort",
      "cd_nomenclature": "3",
      "taxref": [
        {
          "group2_inpn": "all",
          "regne": "all"
        }
      ],
      "id_nomenclature": 158,
      "hierarchy": "007.003"
    }
  ]
}
```

L'avantage est que c'est administrable indépendamment des applications, puisqu'il suffit d'organiser ces valeurs selon cet attribut.

**Comment by camillemonchicourt** [comment]
OK je ne suis pas sur que cet attribut serve à cela. 
Dans GeoNature, on ordonne les nomenclatures de manière alphabétique pour faciliter leur lecture dans les listes, mais je vais confirmer.

**Comment by DonovanMaillard** [comment]
La hiérarchie sert à gérer une arborescence et créer des "sous-nomenclatures". Pour les nomenclatures "officielles" du référentiel, elles se retrouveront triées non pas par ordre alphabétique, mais par ordre de l'id_nomenclature (qui est à la fin de la hierarchy). 

La hiérarchie suit la logique 0.id_type.id_nomenclature, donc indépendante de tout ordre logique au sein d'un type donné (en général ca se retrouve dans l'ordre du cd_nomenclature ou dans l'ordre d'intégration au moment de la création de la base, pour un type donné). 

Pour les sous nomenclatures, ca dépend comment elles sont créées. Mais dans tous les cas, il ne s'agit pas d'un ordre logique pour l'utilisateur, l'ordonnancement sur ce champs s'appuie sur des infos purement techniques.

**Comment by camillemonchicourt** [comment]
OK donc ça confirme. Merci

**Comment by camillemonchicourt** [comment]
OK avec Sync-mobile 0.2.2
