### ISSUE TITLE
Perte du JDD par défaut 

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#43]
Je n'ai pas pu identifier le contexte clair mais j'ai défini un JDD par défaut et ce paramètre saute régulièrement. 

Je dois souvent redéfinir le JDD par défaut. 

Pas de soucis par contre sur l'observateur par défaut.

**Comment by ClaireLagaye** [comment]
bug non reproduit ici en version 0.2.6, même après redémarrage
