### ISSUE TITLE
Documentation installation/paramétrage/déploiement Occtax-mobile

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_mobile_occtax#44]
Bonjour,

Merci à tous ceux qui ont travaillé sur le développement et les tests de GeoNature mobile V2 !
Est il prévu d'intégrer prochainement une documentation permettant l'installation, le paramétrage, et le déploiement GeoNature Mobile V2 ?

Bonne journée à tous.

**Comment by camillemonchicourt** [comment]
Pour le moment les indications sont dans les notes des versions des 2 applications à installer (Sync-mobile puis Occtax-mobile) : https://github.com/PnX-SI/gn_mobile_occtax/releases

C'est assez simple : 
- Il faut installer les APK des 2 applications, puis éditer et intégrer leurs fichiers json respectifs de configuration
- En option, tu peux aussi charger sur ton mobile les fonds offline, là aussi il y a les explications dans les notes de version, renvoyant sur https://github.com/PnX-SI/gn_mobile_maps/blob/develop/maps/README.md
- La première fois que tu lances l'application Sync-mobile, il faut que tu renseignes les paramètres des URL de ton API GeoNature et TaxHub pour qu'il puisse synchroniser les données.

Tu peux tester en te connectant au serveur de démo de GeoNature.

**Comment by samuelpriou** [comment]
Ok ! 
Merci

**Comment by sgrimault** [comment]
Bonjour,

Un début de documentation est présent dans le git du projet :
* https://github.com/PnX-SI/gn_mobile_occtax/blob/develop/docs/installation-fr.md
* https://github.com/PnX-SI/gn_mobile_maps/tree/develop/maps
* https://github.com/PnX-SI/gn_mobile_core/tree/develop/docs
