### ISSUE TITLE
0.2.6 - Impossible d'ajouter un deuxième taxon

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_occtax#45]
Lors de la saisie du relevé, tout se passe bien jusqu'à la fin du premier taxon (dénombrement compris).
Si je clique sur le + pour ajouter un second taxon, je retourne à la page d'accueil de l'appli

Si je retourne sur mon relevé pour ajouter un 2eme taxon, j'ai cette fois une erreur "Occtax s'est arrêté"

**Comment by ClaireLagaye** [comment]
Le bug est toujours présent dans la version 0.3

**Comment by sgrimault** [comment]
Je n'arrive pas à le reproduire de mon coté.
@ClaireLagaye Pourrais tu fournir les logs (`adb`) de l'application ?

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas non plus sur un Galaxy J7, Android 8.1.0

**Comment by ClaireLagaye** [comment]
Ici j'ai un Galaxy A50, Android 10
Toujours impossible de mettre un 2eme taxon sur un relevé.
J'irai au bureau demain et essaierai l'install sur d'autres appareils pour voir.
Voici le log 
[log_occtax.txt](https://github.com/PnX-SI/gn_mobile_occtax/files/4675702/log_occtax.txt)

**Comment by sgrimault** [comment]
Concernant les logs je n'ai pas l'origine de l'erreur (sans doute à cause du grep sur logcat qui filtre un peu trop ?)
Sinon, je pense savoir d'où peut provenir l'erreur. Elle surviendrait si le pointeur sur la carte sélectionne une zone géographique sur laquelle on va charger les informations supplémentaires sur les taxons.
Je vais reconstituer un jeu de données contenant des zones géographiques dont les IDs correspondent à la base locale des taxons.

**Comment by ClaireLagaye** [comment]
@sgrimault si tu as besoin de logs plus complets je peux les faire.
J'ai retesté hier le multitaxon sur 2 autres appareils (android 10 et 8), le résultat était le même (pas de couleur de taxon non plus).

**Comment by ClaireLagaye** [comment]
Testé avec la version 0.3.1, la saisie multitaxon fonctionne, même en revenant sur un relevé déjà créé.
