### ISSUE TITLE
Etape 4 - Filtre sur couleur taxon

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_occtax#48]
A partir des données remontées par api/synthese/color_taxon et  d'un paramètre XXX d'occtax qui serait le nombre de jours utilisé dans la vue v_color_taxon (par défaut 365 jours)
rajouter un filtre au niveau du choix des taxons qui permette de filtrer :
les taxons 'rouge' -> Observé depuis plus de XXX jours/mois/années 
les taxons 'gris' -> Observé depuis moins de XXX jours/mois/années
les taxons 'blancs' -> Aucune observation dans l'unité géographique

**Comment by ClaireLagaye** [comment]
@camillemonchicourt 
Juste une idée: vu que les couleurs ne sont plus utilisées côté web, peut-être serait-il possible de supprimer complètement la colonne color de la vue v_color_taxon et de n'envoyer au mobile que le nb d'obs et dernière date par taxon et par maille?
Ainsi tout pourrait se paramétrer uniquement au niveau du mobile?

**Comment by camillemonchicourt** [comment]
Oui intéressant, en plus ça serait plus léger, et c'est pas terrible de calculer des "couleurs". On devrait envoyer une info factuelle, la couleur étant un choix de représentation.
A voir car ça nécessiterait des évolutions de GeoNature, qu'on n'a pas forcément le temps de faire là. 
Mais comme il faut ajuster des trucs au niveau du calcul des "couleurs", c'est peut-être l'occasion.

**Comment by camillemonchicourt** [comment]
Ce que tu proposes @ClaireLagaye est de se baser sur la table ``gn_synthese.cor_area_taxon`` qui renvoie exactement les infos que tu proposes. 
Mais à voir si c'est pertinent et performant de faire le traitement et le calcul par Occtax-mobile, plutôt que par une vue de GeoNature qui précalcule la "couleur" ?
Dans ce cas là, on peut faire une route basée sur ``gn_synthese.cor_area_taxon`` est même supprimer la vue ``gn_synthese.v_color_taxon```.

**Comment by camillemonchicourt** [comment]
Test en version 0.3.1. 
Je n'ai pas intégré de couche des unités géographiques pour le moment. 
Quand je filtre les taxons "Selon la durée d'observation" puis revient à la liste des taxons, l'application crashe, "Occtax s'est arrêté".

**Comment by ClaireLagaye** [comment]
Test en version 0.3.1
J'ai intégré des unités géographiques et pas mal de données.
http://5.196.209.136/geonature/api/synthese/color_taxon?limit=10000
Y a-t-il eu des changements sur la route? 

Le filtre selon la date de dernière observation semble fonctionner mais aucune couleur ne remonte (même dans des mailles où je suis certaine d'avoir des dizaines d'obs)

**Comment by sgrimault** [comment]
@camillemonchicourt ça fera parti de la prochaine version :) car effectivement en testant aussi de mon coté, il y a des cas limites ou en terme d'expérience utilisateur, ça reste un peu moyen.
Coté saisie, on peut avoir plusieurs cas possibles :
1. Aucune couche de données chargée (ou configurée), les taxons n'ont donc aucune données relatives à une zone géographique. Les filtres applicables sont uniquement ceux par défaut (recherche textuelle, filtre par rang taxonomique)
2. Une couche de données est présente, les taxons peuvent donc avoir des données relatives à une zone géographique :
  2.1. L'utilisateur pointe en dehors de toute zone géographique présente sur la carte, on se retrouve dans le cas 1.
 2.2. L'utilisateur pointe sur une zone géographique, on peut donc appliquer en plus des filtres par défaut ceux concernant la "durée"

**Comment by camillemonchicourt** [comment]
Oui ça serait le fonctionnement idéal, merci.
