### ISSUE TITLE
Couleur des taxons / Paramètre de durée

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#50]
La durée à partir de laquelle les taxons s'affichent en gris en rouge en fonction de l'unité géographique est défini dans la vue ``gn_synthese.v_color_taxon_area`` (https://github.com/PnX-SI/GeoNature/blob/master/data/core/synthese.sql#L1040-L1047). Il est possible d'ajuster cette durée directement dans la vue. 

En lien avec son affichage dans Occtax-mobile (https://github.com/PnX-SI/gn_mobile_occtax/issues/48), il faut donc pouvoir ajuster la durée affichée dans l'application avec un paramètre en jour (365 par défaut) et un affichage "pretty" en jours, mois ou années selon la valeur du paramètre.

**Comment by ClaireLagaye** [comment]
Je viens de tester avec la MAJ 0.3.4
J'ai ajouté le paramètre dans le fichier de settings une première fois avec 365 jours puis une deuxième avec 5 ans et tout a bien fonctionné, mes taxons ont bien changé de couleur
