### ISSUE TITLE
Fonds de carte online

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#51]
Actuellement l'application fonctionne uniquement avec des fonds de carte offline (format MBTILES) grâce au module https://github.com/PnX-SI/gn_mobile_maps.

Ce fonctionnement est privilégié. Cependant il serait utile que l'application puisse fonctionner aussi avec des fonds online. Les fonds offline seraient priorisés si ils sont présents. Mais si ils ne le sont pas, alors un fond online paramétrable (OSM ou OpenTopoMap par défaut, sinon IGN ou autre) seraient utiliser.

**Comment by DonovanMaillard** [comment]
Fonctionnalité à venir, je dois reprendre contact avec @sgrimault pour qu'on lance ce travail avec Flavia

**Comment by lpofredc** [comment]
Dans l'idéal, avec une possibilité de mise en cache, voire de téléchargement de zones, pour une utilisation offline (zone sans réseau, courant dans nos métiers, ou forfaits réduits, également courant ;). Et c'est aussi plus écolo ;)

**Comment by lpofredc** [comment]
_NB_, c'est le fonctionnement actuel de l'appli Naturalist de Biolovision. Très pratique et apprécié.

**Comment by lpofredc** [comment]
Ex pour du cache: https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached

**Comment by camillemonchicourt** [comment]
Fonds online, en complément des éventuels fonds offline mis en place dans la version 1.2.0.
Voir https://github.com/PnX-SI/gn_mobile_maps/issues/4 pour plus de détails.

**Comment by DonovanMaillard** [comment]
Implémenté pour la prochaine release à venir.
