### ISSUE TITLE
Afficher un fond de carte par défaut

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_mobile_occtax#54]
Bonjour,
Actuellement à l'ouverture de OccTax mobile, tous les fonds de carte sont affichés ainsi que les mailles en vecteur.
Il serait plus pratique de pouvoir ajouter un fond raster par défaut (ex : Scan25) puis charge à l'utilisateur de cliquer sur le contrôle des couches pour ajouter par exemple l'Orthohoto et les mailles.
Est il possible d'ajouter un paramètre dans le fichier de conf settings_occtax.json pour afficher un raster par défaut et d'empêcher l'affichage automatique des mailles ? 
J'ai également constaté un comportement erratique. Lorsque l'on décoche une couche (par exemple mailles), la couche reste affichée et à l'inverse si on coche (mailles), la couche ne s'affiche pas instantanément. A voir si d'autres rencontre ce problème.
 
![Screenshot_20200625-142444_Occtax](https://user-images.githubusercontent.com/9743288/85834105-15151480-b793-11ea-98e2-9057b8d9f2e7.jpg)

Merci !

**Comment by DonovanMaillard** [comment]
Pour info, il faut qu'on passe la commande, mais on va effectivement modifier un peu ce fonctionnement pour les fonds de carte en : 
1 - Ajoutant des fonds de cartes récupérés à la volée en ligne
2 - mettant une priorité des fonds de carte, les premiers cités dans la conf étant chargés en premier, le 2eme chargé si le 1er ne répond pas, et ainsi de suite.

**Comment by camillemonchicourt** [comment]
OK le sujet des fonds online est un peu périphérique. 
Là déjà en effet il faut voir pourquoi tous les fonds sont affichés par défaut et comment pouvoir paramétrer l'affichage par défaut des couches et fonds offline.

**Comment by DonovanMaillard** [comment]
Oui, c'est surtout avec le point 2 que je réagissais, puisqu'il sera question de prioriser les fonds qui seront affichés dans l'ordre de leur apparition dans le fichier de conf. Si le 1 répond, les suivants ne seront pas chargés donc il deviendra un fond par défaut

**Comment by samuelpriou** [comment]
L'affichage des fonds de carte et des mailles en simultanée fait planter OccTax Mobile sur des Samsung Xcover 4. 
Très handicapant.

**Comment by camillemonchicourt** [comment]
OK, il faudrait partager les logs au moment du crash, pour savoir le soucis.
Je viens de faire la documentation pour obtenir les logs depuis un PC Linux ou Windows : https://github.com/PnX-SI/gn_mobile_occtax/blob/doc-installation/docs/installation-fr.md#logs

**Comment by samuelpriou** [comment]
J'ai du mal à interpréter les logs en direct avec ADB and Fastboot. 
Le mieux serait peut être que j'envoie les rasters que j'utilise au prestataire ?
![Occtax_Mobile](https://user-images.githubusercontent.com/9743288/86344927-30809380-bc5b-11ea-9630-494afa5db74b.jpg)

**Comment by camillemonchicourt** [comment]
Je viens de corriger la commande de récupération des logs pour Windows. Il manquait un ``|`` pour n'avoir que les logs concernant l'application GeoNature.

Il faut que tu lance adb, lance la commande ``adb logcat`` et fasse l'action sur l'appli qui entraîne le plantage.
Et que tu partages les logs bruts dans le ticket.
Pas envoyer tes rasters non, car ça nécessite pas mal de travail pour remettre le contexte, faire tous les tests, et le problème sera difficilement reproduit.

**Comment by DonovanMaillard** [comment]
Non reproduit sur les dernières versions du module maps. On peut cloturer ?

**Comment by camillemonchicourt** [comment]
Si tu ne reproduis pas, oui.

**Comment by DonovanMaillard** [comment]
> Si tu ne reproduis pas, oui.

Pour le moment je n'ai pas la main pour fermer les tickets ouverts par d'autres ;)
