### ISSUE TITLE
Valeurs redondantes dans les nomenclatures.

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_mobile_occtax#55]
Lorsque je fais une saisie dans OccTax Mobile et que je souhaite ajouter des critères pour la méthode d'observation, j'obtiens un quadruplons pour la valeur cadavre.
![Screenshot_20200625-122816_Occtax](https://user-images.githubusercontent.com/9743288/85846976-fae53180-b7a6-11ea-81f7-7f857948632c.jpg)
![valeurs redondantes_bis](https://user-images.githubusercontent.com/9743288/85846986-ffa9e580-b7a6-11ea-9abb-af73692ad743.jpg)
Je rencontre également ce problème pour le statut biologique.
![valeurs redondantes](https://user-images.githubusercontent.com/9743288/85847090-2831df80-b7a7-11ea-8281-bdec27741ccb.jpg)

**Comment by camillemonchicourt** [comment]
@samuelpriou, as-tu toujours ce soucis ? S'agit-il d'un bug ?

**Comment by samuelpriou** [comment]
@camillemonchicourt Oui j'ai toujours des doublons dans les critères des nomenclatures (méthode d'observations et statut biologique). Je ne rencontre pas ce dysfonctionnement pour Occtax Web.

**Comment by samuelpriou** [comment]
A priori c'est lié à une erreur dans la table ref_nomenclature.t_nomenclatures.
![erreur_bdd](https://user-images.githubusercontent.com/9743288/90264233-14befe80-de51-11ea-91f7-9cc1fb4c3667.jpg)

**Comment by camillemonchicourt** [comment]
C'est ton module CHIRO là, donc pas lié à GeoNature.
Peut-être que tu as fait plusieurs tests d'installations successifs d'installation du module, ce qui a dupliqué ses nomenclatures spécifiques.
