### ISSUE TITLE
Afficher le filtre "Couleurs des taxons"

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_mobile_occtax#56]
Bonjour,
Je ne parviens pas à afficher le filtre "Couleurs des taxons". J'ai inséré le fichier unities.json dans le répertoire avec les fonds de carte, je me suis assuré que l'id de chaque maille correspond bien à l'id des mailles insérées dans la table ref_geo.l_areas.

[https://geonature.mercantour-parcnational.fr/api/synthese/color_taxon?code_area_type=UG](url)

**Comment by camillemonchicourt** [comment]
A priori réglé ? 
Sinon voir la doc sur les unités géographiques : https://github.com/PnX-SI/gn_mobile_occtax/blob/master/docs/installation-fr.md#occtax-mobile
