### ISSUE TITLE
Etape dénombrement - Ergonomie

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#59]
Cette étape pose des soucis de compréhension par les utilisateurs, du fait qu'il faut valider le dénombrement en utilisant un bouton "RETOUR". 
Il faudrait plutôt un bouton VALIDER ou SUIVANT, même si il est d'une forme similaire dans la barre de navigation supérieure, sous forme d'icone, mais à droite et pas à gauche et SUIVANT ou VALIDER plutôt que RETOUR.

**Comment by samuelpriou** [comment]
Effectivement devoir effectuer un retour après l'étape du dénombrement dans la saisie perturbe les utilisateurs. A corriger.

**Comment by camillemonchicourt** [comment]
OK c'est bien mieux ainsi dan la 1.1.0.
Par contre, en français cela affiche le message SAVE en anglais, normal ?
![Screenshot_20200913-232557_Occtax](https://user-images.githubusercontent.com/4418840/93029674-01a07980-f61d-11ea-9f11-74002443fd67.jpg)

Si trop long, utiliser une icone ?

**Comment by sgrimault** [comment]
Sans doute un petit souci de wording, je ferai la correction :)

**Comment by camillemonchicourt** [comment]
OK dans la 1.1.1
