### ISSUE TITLE
API GeoNature + Occtax

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#6]
Précisions de @TheoLechemia sur l'API de GeoNature.

Voici un Postman décrivant les routes utiles pour le mobile : 
https://geonature.fr/documents/2019-05-GeoNature%20v2.postman_collection.json

Il faut au préalable avoir installé GeoNature (https://geonature.readthedocs.io/fr/latest/) sur sa branche develop actuellement, et Taxhub (https://taxhub.readthedocs.io/) en version 1.6.2.

Les routes d'Occtax et métadonnées sont protégées et nécessitent la présence d'un token dans le header.

On peut utiliser cette route pour le créer : http://127.0.0.1:8000/auth/login (voir la route User - login du postman). On a des problèmes de récupération du token lorsque l'on n'est pas sur le même domaine ou qu'on est en mobile.
Dans le Postman aussi un exemple de POST d'Occtax et la route de récupération des jeux de données (filtrés avec les droits de l'utilisateur).
Concernant les nomenclatures, il y a une route pour récupérer les items d'un ou plusieurs types de nomenclature (http://localhost:8000/nomenclatures/nomenclatures?code_type=TYP_DENBR&code_type=STADE_VIE). On passe le "code_type" des nomenclatures qu'on veut récupérer (voir champ mnémonique de la table ``ref_nomenclatures.bib_nomenclatures_types``).

Pour les utilisateurs, une route permet de récupérer tous les utilisateurs d'une liste (anciennement appelé menu, d'ou le nom de la route : http://localhost:8000/users/menu/1 )

Les "couleurs" des taxons sont récupérables à cette route : http://localhost:8000/synthese/color_taxon?code_area_type=M10. Elle renvoie la couleur des taxon pour chacune des aires intersectées en interrogeant la table ``gn_synthese.cor_area_taxon``. Contrairement à la V1, on n’intersecte pas qu'avec les "unités géographiques", mais avec l'ensemble des "zonages" présents dans le référentiel géographique (mailles, natura 2000 : voir la table ``ref_geo.bib_areas_type`` etc...). Ici la route renvoie les couleurs des taxons pour les mailles de 10km.

Les routes concernant la taxonomie utilisent l'API de TaxHub (qui tourne par défaut sur le port 5000).
Tu peux récupérer une liste de taxons à partir de cette route: (http://localhost:5000/api/taxref/allnamebylist/100). Ici on récupère tous les taxons de la liste 100, qui est la liste fournie par défaut et qui est utilisé sur le module Occtax WEB (voir la table ``taxonomie.cor_nom_liste`` et ``taxonomie.bib_noms`` pour peupler cette liste. Elle ne contient par défaut que quelques taxons, tu peux la peupler plus largement avec cette requête: 

```SQL
 DELETE FROM taxonomie.cor_nom_liste;
 DELETE FROM taxonomie.bib_noms;

 INSERT INTO taxonomie.bib_noms(cd_nom,cd_ref,nom_francais)
 SELECT cd_nom, cd_ref, nom_vern
 FROM taxonomie.taxref
 WHERE id_rang NOT IN ('Dumm','SPRG','KD','SSRG','IFRG','PH','SBPH','IFPH','DV','SBDV','SPCL','CLAD','CL',
 'SBCL','IFCL','LEG','SPOR','COH','OR','SBOR','IFOR','SPFM','FM','SBFM','TR','SSTR');

INSERT INTO taxonomie.cor_nom_liste (id_liste,id_nom)
SELECT 100,n.id_nom FROM taxonomie.bib_noms n;
```

En complément : 

- Le GeoJson de la route en POST ``/occtax/releve`` peut contenir plusieurs occurrences (clé "t_occurrences_occtax" de "properties", qui est un tableau), qui elles même peuvent contenir plusieurs dénombrement (clé "cor_counting_occtax" de "t_occurrences_occtax")
- Tous les attributs des properties du GeoJSON sont obligatoires ou non ? Non, on peut regarder en BDD quels champs sont obligatoires. Mais par défaut le GeoJSON construit par le front initie toutes les valeurs du formulaire à "null". La plupart des nomenclatures sont en NOT NULL,  la route pour récupérer les nomenclature par défaut (https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/backend/blueprint.py#L461) est la suivante : 127.0.0.1:8000/pr_occtax/defaultNomenclatures. Elle interroge la table ``pr_occtax.defaults_nomenclatures_value``. On peut lui passer les paramètre suivant en query string : "organism" (pour récupérer des nomenclatures par défaut propre à un organisme, s'il elles sont renseignées) et "regne" et "group2_inpn" qui sont des filtres taxonomiques.
- "date_min" et "date_max". Dans le standard occurrence de taxon, un relevé peut être fait sur une période donnée (par exemple les enthomo qui mettent des pièges lumineux pour capturer des papillons, notent la date de début puis la date de fin de la capture). Par défaut en web on n'affiche que la "date début" et il y a un accordéon pour remplir la "date fin" qui est prérempli avec la "date début". Même chose pour "hour_min", "hour_max". 
- "id_digitiser" ? Identifiant de la personne qui saisit le relevé (en web, la personne qui saisit peut être différente de la personne qui était sur le terrain). Comme on sera en mode "identifié" sur mobile, on met l'id de la personne connecté.
- L'attribut "id_releve_occtax" correspond à l'ID du relevé. Il est donc ignoré par l'application mobile puisqu'elle ne fait que créer de nouveau relevé. C'est un serial généré par la BDD.
- Quelle valeur renseigner pour l'attribut "meta_device_entry" ? En mode Web on a donc "web", coté application mobile ce sera "mobile"

**Comment by DonovanMaillard** [comment]
> Concernant les nomenclatures, il y a une route pour récupérer les items d'un ou plusieurs types de nomenclature (http://localhost:8000/nomenclatures/nomenclatures?code_type=TYP_DENBR&code_type=STADE_VIE). On passe le "code_type" des nomenclatures qu'on veut récupérer (voir champ mnémonique de la table ref_nomenclatures.bib_nomenclatures_types).

Est-ce pertinent d'utiliser le code_type et non pas l'id_type comme en base? Je pose la question, parce que si on regarde le cas des dernières évolutions du référentiel occurrence de taxon, la nomenclature méthode garde ses modalités mais s'appelle maintenant technique... qui existait par ailleurs dans le précédent référentiel avec des valeurs et un sens différent. 
Dans ce cas précis, la mise à jour vers le nouveau référentiel ne pourrait-il pas poser soucis, en allant chercher les anciennes modalités des 'anciennes' techniques, plutôt que d'aller chercher la bonne nomenclature, que l'on vient d'appeler technique? Je sais pas si c'est très clair... à vrai dire c'est pas très clair non plus dans le changement de référentiel ^^

**Comment by camillemonchicourt** [comment]
On ne peut pas utiliser les ``id_type`` en dur dans le code car ils peuvent varier d'une instance GeoNature à une autre.
Les évolutions du standard et du MCD Occtax devront s'accompagner d'évolutions des outils de saisie.

**Comment by DonovanMaillard** [comment]
Ca marche. Je pensais justement que la seule chose stable, d'une instance à l'autre, seraient les ID... 

Du coup se pose l'autre question : ne faut-il pas développer le mobile compatible avec le dernier référentiel et faire évoluer GN d'ici là?

**Comment by camillemonchicourt** [comment]
Non justement, c'est pour ça qu'on ne les utilise pas dans le code de GeoNature.
