### ISSUE TITLE
Problème récupération du nombre de taxons de geonature

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#61]
Bonjour,
Dans l'application mobile, nous n'avons pas la totalité des taxons qui ont été créés dans geonature.
Nous avons 922 taxons et seulement 252 semble synchronisés sur le téléphones.
Nous avons modifié les paramètres page_size et page_max_retry. Cela semble avoir une influence car les espèces remontées ne sont pas les mêmes qu'au paramétrage initial cependant nécessaire ne sont pas remontés.
Pouvez-vous nous indiquer comment faire pour remonter tous nos taxons ?
Cistude Nature

**Comment by camillemonchicourt** [comment]
Pouvez-vous indiquer les paramètres que vous avez pour la pagination ?
Et quelle version de TaxHub utilisez vous ?

**Comment by camillemonchicourt** [comment]
Et quelle version de Sync-mobile ?

**Comment by christianbieche** [comment]
bonjour,
La version de taxhub utilisé est  : 1.7.2
La version de sync : sync-1.0.0-generic-release.apk
Les paramètres utilisés sont : 
"page_size": 1000,
  "page_max_retry": 5
mais nous avions essayé avant les paramètres suivant : 
"page_size": 200,
 "page_max_retry": 6
visiblement cela change des choses mais nous n'avons jamais la totalité des taxons de notre base du coup c'est inutilisable.
Christian Bièche
Informatique
Cistude Nature

**Comment by camillemonchicourt** [comment]
OK donc TaxHub est bien la bonne version où les problèmes de pagination ont été réglés.

L'important est notamment la définition de l'``id_liste`` de la liste des taxons utilisée et définie dans TaxHub.
Mais de notre côté, j'ai constaté un soucis si on définit des paramètres puis qu'on les change, ça ne semble pas vraiment pris en compte. Voir https://github.com/PnX-SI/gn_mobile_core/issues/21.

@sgrimault, tu identifies un soucis potentiel ?

**Comment by sgrimault** [comment]
@camillemonchicourt 
Actuellement l'application de synchronisation garde effectivement les données déjà synchronisées en ajoutant les nouvelles non présentes. Je ferai une correction en ce sens, pour repartir sur une base vide à chaque fois dès que la synchronisation retourne de nouvelles données (cf. https://github.com/PnX-SI/gn_mobile_core/issues/21).

**Comment by camillemonchicourt** [comment]
Oui bonne idée de procéder comme ça.
Là le problème de @christianbieche semble autre chose mais je ne vois pas bien quoi et il faudrait certainement plus de précisions.
Notamment URL du TaxHub utilisé et l'id de la liste de taxons pour vérifier ce que renvoie l'API.

**Comment by christianbieche** [comment]
bonjour,
L'url du taxhub utilisé est : "https://obs-nature.org/taxhub" 
l'id de la liste des taxons est : "taxa_list_id": 100
Cordialement,
Cistude Nature

ps: si vous me dites comment faire je peux aussi tester de mon côté pour voir ce que donne les apis ...

**Comment by camillemonchicourt** [comment]
OK j'essaierai de regarder les API et faire un retour.
A noter qu'une version 1.0.1 de Sync-mobile est sortie et améliore certains points de la synchronisation.

**Comment by camillemonchicourt** [comment]
Les URL des API utilisées par les applications mobiles sont indiquées dans la documentation.
Pour accéder aux versions et conf des applications, la route est https://obs-nature.org/geonature/api/gn_commons/t_mobile_apps

On y voit que le paramètre ``page_size`` est défini à 100 et le ``page_max_retry`` à 5. Donc cela permet de synchroniser 500 noms maximum.

Or la route appelée pour récupérer tous les noms de votre liste ``100`` renvoie 1758 résultats : https://obs-nature.org/taxhub/api/taxref/allnamebylist/100?limit=10000

A noter que la version 1.0.1 de Sync-mobile corrige https://github.com/PnX-SI/gn_mobile_core/issues/21

**Comment by christianbieche** [comment]
bonjour,
Merci pour votre réponse. Les paramètres correspondent bien  à ce que j'avais compris cependant je viens de vérifier et l'application ne récupère que 252 taxons et non pas 500 comme on pouvais s'attendre puisque effectivement je suis revenu à ces paramètres avant de laisser faire des tests sur le terrain.
J'avais modifié ces paramètres comme je l'avais indiqué précédemment dans des valeurs supérieures mais cela n'avait rien changé en nombre de taxons récupérés. Simplement ce n'était pas les mêmes.

Je tenterais avec la nouvelle version en mettant un paramètre page-size = 400 et page_max_retry = 5 pour voir si maintenant cela fonctionne.

**Comment by christianbieche** [comment]
J'ai mis à jour les 2 applications.
Cette fois le programme de synchro m'a indiqué la récupération de 1759 taxons ce qui semble bien correspondre à l'attendu.
Cependant quand j'ai testé pour voir une saisie dans occtax il me donne que 906 taxons ?
Est ce normal ? est ce que le nombre de taxons est fonction du jeux de données choisie ?
Cordialement,
Christian Bièche
Cistude Nature

**Comment by camillemonchicourt** [comment]
Votre liste contient bien 906 noms donc c'est normal : https://obs-nature.org/taxhub/#!/listes/100

La route de TaxHub renvoie en effet 1759 lignes car elle contient une ligne pour les noms scientifiques et une pour les noms vernaculaires : https://obs-nature.org/taxhub/api/taxref/allnamebylist/100?limit=10000

Mais ensuite l'application se charge de les regrouper en une seule ligne par nom, donc 906 noms.

**Comment by christianbieche** [comment]
Parfait alors.
Tout fonctionne. Les utilisateurs vont être content.
