### ISSUE TITLE
Demande de mise à jour de l'application ?

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#62]
Bonjour,
Je constate depuis ma dernière réinstallation d'occtax qu'il y a systèmatiquement une demande de mise à jour de celle ci alors que j'ai récupéré la dernière release sus github.
Pourquoi cette demande et comment supprimer, car même si on télécharge cela ne change rien ?

Cistude Nature

**Comment by camillemonchicourt** [comment]
L'application mobile propose une mise à jour, en fonction des informations qu'elle trouve dans la table ``gn_commons.t_mobile_apps``.
Si les applications Sync-mobile et Occtax-mobile installées sur le terminal sont différentes de celles indiquées dans cette table, alors l'application mobile va proposer une mise à jour vers la version indiquée dans la table.

Idem pour la configuration, c'est celle centralisée sur le serveur GeoNature qui fait référence et écrase celle sur le terminal si elle existe. Voir https://github.com/PnX-SI/gn_mobile_core/issues/8

**Comment by camillemonchicourt** [comment]
@christianbieche, problème réglé ?

**Comment by christianbieche** [comment]
Bonjour,
Effectivement. J'avais un problème de version. Pas en phase avec la base d'où le message persistant.
Je suis allé sur un téléphone pour trouver la version code et j'ai mis à jour la table gn_commons.t_mobile_apps avec la valeur trouvée et je n'ai pas le message de mise à jour.

Par contre pourquoi avais-je une valeur incorrecte en base ? Quand ce fait cette mise à jour ? Après l'installation au premier lancement  ?

**Comment by christianbieche** [comment]
Par contre pourquoi avais-je une valeur incorrecte en base ? Quand ce fait cette mise à jour ? Après l'installation au premier lancement  ?

**Comment by camillemonchicourt** [comment]
La table t_mobile_apps n'est modifié que manuellement.
Je ne comprends pas bien la question ?

**Comment by christianbieche** [comment]
Bon. Je note. 
Je ne me rappelle pas avoir modifié cette table, cependant comme nous sommes actuellement 2 à faire des modifications c'est peut être mon collègue qui a fait la mise çà jour.
Ma question est donc sans objet. Merci.
