### ISSUE TITLE
Echec authentification (version 1.1 sync mobile

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/gn_mobile_occtax#63]
Bonjour, 

J'ai installé un geonature tout neuf (2.4.1) sur un serveur de test et j'ai voulu tester l'application mobile.
J'ai installé à la main l'application sync sur mon android et créé le fichier de configuration comme dans l'exemple donné (et mis à jour les urls). Je tente de me logger (admin/admin) et j'ai toujours le message "Echec lors de l'authentification".
Y a t-il des étapes à faire coté serveur pour que cela fonctionne ?
Le fait que je sois sur une adresse de type : http://XX.XXX.XX.XXX/geonature peut poser pb ?
Les étapes décrites dans le paragraphe "Installation et configuration centralisées" de la documentation sont obligatoires ? 
J'ai aussi testé avec les urls de l'instance de demo mais cela me mets le même message....
Est-ce que l'on peut voir des logs qq part ?

merci

**Comment by camillemonchicourt** [comment]
Oui pour les logs, voir le paragraphe dédié dans la documentation.

Sinon ton soucis vient certainement du fait que Android impose que le serveur soit en HTTPS.
On va passer le serveur Démo en HTTPS dès que possible.

La configuration centralisée n'est pas obligatoire.

**Comment by RomainBaghi** [comment]
OK merci, je vais tester avec https.

**Comment by RomainBaghi** [comment]
C'était bien ça.

**Comment by camillemonchicourt** [comment]
OK tant mieux 👍 
C'est rajouté dans la doc (https://github.com/PnX-SI/gn_mobile_occtax/commit/bea335f170dfd4bc721210ddfbce0d9bba67a2bf)
