### ISSUE TITLE
Données en attente de synchronisation

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_occtax#64]
Sur certains des mobiles au PNV (environ 5 sur 40), les relevés finalisés (et même synchronisés) restent sur la page d'accueil d'Occtax.
Les agents sont donc obligés de vérifier que le relevé passe bien dans les relevés à synchroniser en haut et ensuite de le supprimer en haut pour ne pas avoir une liste à rallonge.
Ca ne concerne que qq appareils mais sur ces appareils c'est systématique.

**Comment by camillemonchicourt** [comment]
Même problème sur mon mobile de test. 
Je créé un relevé et me termine, il s'affiche dans la liste des RELEVES EN COURS.
L'état du terminal indique 1 relevé non synchronisé.
Je synchronise les données, cela fonctionne.
Sur Occtax-mobile il indique désormais 0 relevé non synchronisés.
Cependant le relevé est toujours listé dans les relevés en cours.

**Comment by DonovanMaillard** [comment]
Même problème sur un galaxy note 10 confirmé par Yann. Le comportement des relevés terminés est instable, des fois la synchronisation se fait et le relevé disparait, des fois il ne se synchronise pas. Des fois le relevé est modifiable des fois non...

**Comment by camillemonchicourt** [comment]
Reproduit en version 1.1.1.

**Comment by camillemonchicourt** [comment]
Je viens de reproduire sur Occtax-mobile 1.1.2.

- Je lance Sync-mobile et Occtax-mobile où j'ai aucun relevé en cours.
- Je créé un relevé complet
- Une fois le relevé terminé, Occtax-mobile indique "1 relevé à synchroniser" et "1 relevé en cours"
- Après synchronisation, le relevé est toujours affiché dans la liste des relevé en cours

Aperçu vidéo : 

![20200927_183838](https://user-images.githubusercontent.com/4418840/94370825-82b64100-00f2-11eb-9419-ba588b9d0613.gif)

**Comment by camillemonchicourt** [comment]
OK corrigé avec la 1.1.1 de Sync-mobile et la 1.1.3 d'Occtax-mobile quand on créé un relevé complet dès la première fois.
Par contre si je créé un relevé partiel, que je ne le termine pas.
Je reviens ensuite dessus pour le termine, là j'ai toujours le même problème, il reste dans la liste des "Relevés en cours" même une fois terminé et même une fois synchronisé.

**Comment by camillemonchicourt** [comment]
Et sur mon autre terminal mobile, j'ai toujours le soucis, même quand je créé directement un relevé complet.

**Comment by camillemonchicourt** [comment]
Avec la version 1.1.4, je n'ai plus le problème sur mon terminal mobile où il se produisait uniquement quand je reprenais un relevé partiel et le terminait dans un second temps.
Et plus non plus sur l'autre terminal où cela se produisait lors de la création intiale d'un relevé complet.
Donc la 1.1.4 semble régler le soucis ?

**Comment by camillemonchicourt** [comment]
Plus de problème avec la version 1.1.4.
