### ISSUE TITLE
Impossible d'afficher les données carte dans l'application occtax

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#65]
bonjour,
J'ai installé les dernière versions mobiles : sync-1.0.0-generic-release.apk et occtax-1.0.0-generic-release.apk
Cela fonctionne.
J'arrive à me connecter sur le nouveau serveur et la synchronisation est effectuée.
Cependant si je tente d'afficher des données ou d'ajouter une nouvelle donnée.
Aucune carte ne s'affiche.

j'ai installé un fond de carte aquitaine avec le fichier de configuration suivant : 
{
  "area_observation_duration": 365,
  "map": {
    "show_scale": true,
    "show_compass": true,
    "max_bounds": [
      [
        41.463,
        -1.876
      ],
      [
        51.62,
        8.6
      ]
    ],
    "center": [
      47.225827,
      -1.554470
    ],
    "start_zoom": 10.0,
    "min_zoom": 8.0,
    "max_zoom": 19.0,
    "min_zoom_editing": 12.0,
	"base_path": "/storage/4735-425B/DCIM/Camera",
    "layers": [
      {
        "label": "Aquitaine",
        "source": "aquitaine.mbtiles"
      }
    ]
  },
  "no_such_property": "no_such_value"
}

Par contre en regardant les logs du terminal : j'ai cette erreur là : 

7-29 17:13:34.676 15687 15964 D fr.geonature.commons.data.helper.SQLiteSelectQueryBuilder: sql:
07-29 17:13:34.676 15687 15964 D fr.geonature.commons.data.helper.SQLiteSelectQueryBuilder: SELECT taxa."_id" AS taxa__id, taxa."name" AS taxa_name, taxa."kingdom" AS taxa_kingdom, taxa."group" AS taxa_group, taxa."name_common" AS taxa_name_common, taxa."description" AS taxa_description, taxa."rank" AS taxa_rank
07-29 17:13:34.676 15687 15964 D fr.geonature.commons.data.helper.SQLiteSelectQueryBuilder: FROM taxa taxa
07-29 17:13:34.676 15687 15964 D fr.geonature.commons.data.helper.SQLiteSelectQueryBuilder: ORDER BY taxa_name ASC
07-29 17:13:34.676 15687 15964 D fr.geonature.commons.data.helper.SQLiteSelectQueryBuilder: args: []
07-29 17:13:34.713 15867 15867 W fr.geonature.commons.data.TaxonArea: column 'taxa_area_taxon_id' does not exist. Available columns: [taxa__id, taxa_name, taxa_kingdom, taxa_group, taxa_name_common, taxa_description, taxa_rank]
07-29 17:13:34.835 15867 15867 I chatty  : uid=10150(fr.geonature.occtax) identical 17 lines

Est ce que les 2 problèmes sont liés ?
La version installée de taxhub est 1.7.2
Christian Bièche
Cistude Nature

**Comment by christianbieche** [comment]
Bonjour,
Effectivement si j'utilise votre carte france et cela fonctionne. J'ai bien l'affichage de la carte. Le zoom sur la zone affiche une pixellisation mais il suffit de dézoomer pour vérifier le positionnement.
Il me semble que l'affichage est plus rapide mais c'est peut être qu'une impression.
Le problème constaté est donc bien un problème à priori de performance et de taille de carte en mbtiles.

Christian Bièche
Cistude Nature

**Comment by camillemonchicourt** [comment]
OK, je pense qu'un intermédiaire peut être une bonne solution.
Votre fond initial était surement trop précis et volumineux donc il faisait ramer les terminaux mobiles.
Par contre le notre de démo est vraiment crados car très général, peu précis et léger.
Bonne journée.

**Comment by christianbieche** [comment]
Bonjour,
Je viens de reinstaller les nouvelles versions des applications téléphones sur plusieurs téléphones et je rencontre toujours des problèmes sur l'affichage des cartes. J'ai gardé la carte de démo pour les téléphones mais même avec des téléphones complétement identique parfois la carte s'affiche parfois non !!
Que faut-il faire pour avoir un affichage des cartes ? ya t-il d'autres paramètres ???
Christian Bièche
Cistude Nature
