### ISSUE TITLE
bug, dénombrement doublé 

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/gn_mobile_occtax#67]
Lorsqu'on saisi un relevé, le dénombrement est doublé à partir du second taxon saisi.

**Comment by DonovanMaillard** [comment]
Merci Romain,

Je devais faire un ticket, j'ai eu le même retour cet après-midi, les dénombrements se dédoublent quand il y a plusieurs taxons

**Comment by camillemonchicourt** [comment]
OK je viens de reproduire. 
En effet la fenêtre de saisie d'une occurrence est affichée 2 fois de suite à partir du second taxon d'un relevé.

**Comment by camillemonchicourt** [comment]
OK dans la version 1.1.1
