### ISSUE TITLE
Masquer certains champs

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#7]
Dans le module web d'Occtax, il est possible de masquer certains champs.
Dans ce cas c'est la valeur par défaut qui est postée.

Il faudrait pouvoir masquer certains champs de la même manière dans l'application mobile.

**Comment by camillemonchicourt** [comment]
Au niveau d'Occtax-web, c'est géré dans la configuration du module : https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/config/conf_gn_module.toml.example#L134-L165

Ensuite au niveau du formulaire web, selon la valeur du paramètre, le champs est affiché ou caché : https://github.com/PnX-SI/GeoNature/blob/develop/contrib/occtax/frontend/app/occtax-map-form/form/occurrence/occurrence.component.html#L67

**Comment by camillemonchicourt** [comment]
Les champs à pouvoir masquer sont, dans l'étape 4 : 
* Méthode d'observation (obs_method)
* Etat biologique (bio_condition)
* Methode de détermination (determination_method)
* Déterminateur (determiner)
* Statut biologique (bio_status)
* Niveau de naturalité (naturalness)
* Preuve d'existence (exist_proof)

Dans l'étape 5 : 
* Stade de vie (life_stage)
* Sexe (sex)
* Objet du dénombrement (obj_count)
* Type de dénombrement (type_count)
* Nombre minimum (count_min) / Même si ça ne fonctionnerait pas bien
* Nombre maximum (count_max) / Même si ça ne fonctionnerait pas bien

**Comment by camillemonchicourt** [comment]
Ajouter aussi le champs masquable "Comportement (behaviour)", en cours d'implémentation dans Occtax au niveau de l'occurrence de taxon, dans le cadre du passage à la version 2.0 du standard Occurrences de taxons (https://github.com/PnX-SI/GeoNature/issues/516). Le champ sera ajouté dans la version 2.5.0 de GeoNature à venir courant septembre.

On laisse de côté les autres champs ajoutés pour le moment, car trop complexe ou peu utiles.

**Comment by sgrimault** [comment]
@camillemonchicourt 
Concernant le nouveau champ "Comportement", il faudrait me préciser son code mnémonique correspondant tel qu'il sera remonté via la route `/nomenclatures/nomenclatures/taxonomy`, ainsi que son attribut correspondant lors de l'envoi d'un relevé via la route `/occtax/releve` (`id_nomenclature_*` ?)

**Comment by camillemonchicourt** [comment]
OK on est en train de finaliser le passage au standard Occurrences de taxons v2 et sa mise en place dans GeoNature 2.5.
Il y a aussi un champs renommé (méthode d'observation) et un champs supprimé (technique d'observation).
On te précise ça.

**Comment by TheoLechemia** [comment]
Le code mnemonique du champs comportement est : ``OCC_COMPORTEMENT``. Il est bien remonté dans la route `/nomenclatures/nomenclatures/taxonomy`. Le nom du champs dans le POST du relevé est `id_nomenclature_behaviour` (il se situe dans la table `pr_occtax.t_occurrences_occtax`).
Le champs est à afficher dans la partie AVANCE, après statut biologique. Et à rendre masquable.

Autre changements:
le champs `id_nomenclature_obs_meth` de la table `pr_occtax.t_occurrences_occtax` est renommé `id_nomenclature_obs_technique`. Il faut donc aussi renommer ce champs "Technique d'observation" dans l'interface. Le champ correspond toujours au code mnémonique `METH_OBS`.

NB: je ne sais pas si tu utilisais ce champs, car il n'est pas dans l'interface, mais l'ancien champs  `pr_occtax.t_releves_occtax .id_nomenclature_obs_technique` est renommé `id_nomenclature_tech_collect_campanule`. Ce champs n'a plus de contrainte `NOT NULL` dans la base et à vocation à être supprimé, donc il faudrait le supprimer aussi de ton côté.

Cela ne sera compatible qu'avec la version 2.5.0 de GeoNature à venir, qui intègre ces évolutions.

**Comment by sgrimault** [comment]
Merci pour ces précisions.
Ça veut donc dire que la prochaine version de "Occtax" qui intégrera ces évolutions ne sera donc compatible qu'avec la version 2.5.0 de GeoNature.
Il n'y a pas de rétrocompatibilité possible (ou prévue) entre les différentes versions de GeoNature ? Car à mon niveau, je n'ai aucun moyen de déterminer si l'URL renseignée de GeoNature pour une version de "Occtax" est bien compatible.
Avez vous prévu (ou prévoyez de faire) de versionner les différentes APIs de GeoNature ?

**Comment by camillemonchicourt** [comment]
Oui ça pourrait être rétrocompatible si il n'y avait que des champs ajoutés et supprimés. Dans ce cas ça fonctionnerait avec l'ancienne ou la nouvelle version.
Mais ce qui est bloquant est qu'un champs soit renommé et prenne le nom d'un champs qui est supprimé mais qui tapait pas sur la même nomenclature... Et là on est coincé. 
Donc on devra indiquer dans la prochaine version d'Occtax-mobile "Compatible avec GeoNature version 2.5.0 et plus". 
Pas trop le choix dans ce cas particulier.

**Comment by sgrimault** [comment]
Oui, je m'en doutais un peu :)
La prochaine version de "Occtax" qui inclura cette évolution sera donc 1.1.0 où la "branche" 1.1.z indiquera cette non compatibilité avec la "branche" 1.0.z actuelle.

**Comment by camillemonchicourt** [comment]
Oui OK, d'autant plus justifié avec les nouveautés fonctionnelles qu'elle apportera.

**Comment by camillemonchicourt** [comment]
OK dans la 1.1.0.
