### ISSUE TITLE
configuration, chemin vers le fichier de fond cartographiques

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/gn_mobile_occtax#71]
Je n'arrive pas à trouver le bon "base_path" dans le settings_occtax.json dans le cas ou le fichier est mis sur le stockage interne. Des indées ? J'imagine que cela dépand des terminaux (?). Ici c'est sur un samsung galaxy s10).
(j'y arrive bien pour le stockage externe "mnt/").

**Comment by camillemonchicourt** [comment]
Pour faciliter cela, une fonctionnalité a été mise en place dans l'application Sync-mobile. Quand on va dans les paramètres de Sync-mobile, cela affiche les chemins absolus vers la mémoire interne (et externe si le terminal en dispose) : 

![image](https://user-images.githubusercontent.com/4418840/93206899-6f9e8b00-f75a-11ea-8759-a9b2c0be9500.png)

C'est indiqué dans la documentation (https://github.com/PnX-SI/gn_mobile_occtax/blob/master/docs/installation-fr.md), qui indique aussi qu'il est possible d'indiquer un chemin relatif sinon (non conseillé car moins performant cependant : 

> La page "Paramètres" de l'application Sync-mobile indique les chemins absolus de la carte interne et éventuellement de la carte externe SD.

> Il n'est cependant pas obligatoire de préciser le chemin pour résoudre le chargement des fonds de carte. L'application va privilégier la carte SD externe (si présente) et à défaut la mémoire interne. Le paramètre base_path peut prendre un chemin absolu (pour une résolution rapide), un chemin relatif (selon le point de montage, par exemple Android/data) ou être omis. Dans ce cas, la résolution sera plus lente car elle impliquera un scan complet des stockages du terminal mobile.

Sur le serveur démo, le chemin absolu vers le stockage interne est : ``"base_path": "/storage/emulated/0/DCIM/maps"``.

Pour voir tous les paramètres du serveur de démo : https://demo.geonature.fr/geonature/api/gn_commons/t_mobile_apps

**Comment by RomainBaghi** [comment]
Merci pour la réponse. Le problème persiste malgré le chemin bien saisi. J'ai autorisé l'appli à avoir accès au local storage. Je testerai avec une carte sd.

**Comment by DonovanMaillard** [comment]
On est sur des galaxy aussi et pour le moment, pas moyen de mettre le moindre fond de carte non plus romain ;) 

On doit lancer prochainement avec notre trésorier une presta pour permettre le chargement des fonds de carte en ligne, facon "google map", applis gps etc

**Comment by christianbieche** [comment]
Bonjour,
Même problème sur 1 galaxy S9.
J'ai vérifié le chemin d'accès à la carte qui est correct mais la carte ne s'affiche pas.
D'autre part cela fonctionne sur d'autres téléphones avec le même chemin et la même carte.
Cistude Nature

**Comment by camillemonchicourt** [comment]
OK alors si il s'agit de différences liés aux modèles de téléphone, c'est bizarre...
Il faudrait des précisions, des logs ou autre pour identifier la source su problème.

**Comment by DonovanMaillard** [comment]
A reproduire avec les chemins absolus pour voir où ça en est. 

Sur nos galaxys on arrive à faire fonctionner l'appli correctement avec des chemins relatifs sans soucis maintenant.
