### ISSUE TITLE
Carte / Edition / Zoom - et disparition marqueur

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_occtax#72]
- Je modifie un relevé
- Je dézoome
- Je déplace le marqueur
- Je zoome
- Le marqueur disparait à un certain niveau de zoom
- Il réapparait quand je dézoome

Aperçu : 

![20200915_175523](https://user-images.githubusercontent.com/4418840/93234573-c0bf7680-f77c-11ea-8c4f-27eea00e4195.gif)

**Comment by sgrimault** [comment]
La prochaine version de l'application devrait corriger ce souci (du moins, je n'ai pas réussi à le reproduire).
À retester :)

**Comment by camillemonchicourt** [comment]
Reproduit en 1.1.1 mais pas essentiel.
C'est quand on modifie un relevé, que l'on dézoome beaucoup, le déplace et rezoome dessus.

**Comment by amandine-sahl** [comment]
Reproduit avec la version 1.1.4

**Comment by camillemonchicourt** [comment]
Oui normalement corrigé par le dernier commit du module Maps en cours de développement et qui sera intégré dans la prochaine Release
