### ISSUE TITLE
Problème de synchronisation avec occtax 1.1.0 

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#73]
Bonjour,
Pour résoudre mon problème de synchronisation des taxons. J'ai installé la nouvelle version de la synchro : sync-1.1.0-generic-release.apk
Effectivement cela fonctionne. Comme il existait aussi une nouvelle version 1.1.0 d'octax j'ai donc aussi installé cette version
occtax-1.1.0-generic-release.apk
Problème avec cette version la synchronisation ne fonctionne plus !

J'ai donc remis la version 1.0.0 package : occtax-1.0.0-generic-release.apk
Et la synchronisation refonctionne.

Il y a donc une régression dans le fonctionnement de l'application.
Pouvez-vous voir ce point ? 
D'avance merci.

Cistude Nature

**Comment by TheoLechemia** [comment]
Bonjour,

La version 1.1.0 n'est compatible qu'avec la version 2.5.x de GeoNature, que nous sommes en train de préparer.

Voir les notes de version: https://github.com/PnX-SI/gn_mobile_occtax/releases/tag/1.1.0

**Comment by christianbieche** [comment]
Bonjour,
Parfait c'est donc normal. Merci.

**Comment by christianbieche** [comment]
Merci. On attendra la nouvelle version de GeoNature.
