### ISSUE TITLE
Suppression d'un objet : message d'annulation très rapide

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_mobile_occtax#77]
Lorsque l'on supprime un élément (des fois par erreur en laissant trainer son doigt trop longtemps sur l'écran). Un petit message, permettant d'annuler la suppression, apparait pendant environ 2 secondes. Ce qui demande énormément de réactivité si on a fait une fausse manipulation.

Piste d'amélioration : 
 - faire en sorte que le message s'affiche plus longtemps
 - au lieu d'annuler, demander une confirmation

**Comment by DonovanMaillard** [comment]
Je serais assez pour une confirmation également, même fausse manip de mon coté cet été.

**Comment by camillemonchicourt** [comment]
Oui beaucoup d'utilisateurs ont demandé que les suppressions aient un message de confirmation

**Comment by DonovanMaillard** [comment]
Intégré au projet AAP, et envisagé dans une révision ergonomique un peu plus globale

**Comment by DonovanMaillard** [comment]
Sera intégré à la prochaine commande en cours de rédaction :)
