### ISSUE TITLE
Relevés non synchronisés - blocage de la synchronisation

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_mobile_occtax#79]
Suite à la mise à jour de GeoNature (2.5.5) ainsi que des versions de Occtax mobile et de sync, des anciens relevés restent bloqués et empêchent de faire une synchronisation. 
Existe t'il un moyen de supprimer ces anciens relevés ?

Merci !

**Comment by camillemonchicourt** [comment]
Oui c'est normal que ces relevés ne passent pas car le modèle de données a évolué dans GeoNature 2.5.
Donc ces données sont bloquées et à supprimer.
Certainement dans la BDD SQLite locale dans le fichier ``/Android/data/fr.geonature.sync/databases/`` à ouvrir avec un éditeur de BDD. 

En amélioration on pourrait imaginer que les données qui ne sont pas bonnes soient gardées mais que les autres qui sont OK soient postées quand même.

**Comment by samuelpriou** [comment]
OK. Merci !

**Comment by ClaireLagaye** [comment]
Nous avons eu le même problème au PNV suite à la mise à jour. Il y avait pas mal de données coincées donc on ne voulait pas simplement les supprimer.
J'ai demandé à mes utilisateurs de m'envoyer le contenu de leur dossier Android/data/fr.geonature.occtax/inputs (et de le vider pour décoincer la synchro).
J'ai récupéré tous les json bloqués et avec une petite routine avec un éditeur de texte, il suffit de remplacer id_nomenclature_obs_meth par id_nomenclature_obs_technique dans le fichier json pour le remettre à la synchro

**Comment by camillemonchicourt** [comment]
Excellent, merci pour ce retour

**Comment by samuelpriou** [comment]
@ClaireLagaye. Ça fonctionne parfaitement !
Merci pour la manip
