### ISSUE TITLE
Test appli Occtax 0.0.7

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_mobile_occtax#8]
- Appli OccTax 0.0.7 installé sur mobilé avec Android 8 sans adb.

L'application s'ouvre, mais sans données observateurs et espèces même en cliquant sur Synchronisation.
Sinon possible de naviguer dans les premiers écrans.
Comment faire le lien avec l'appli Sync qui contient un petit jeu de données

**Comment by sgrimault** [comment]
Il faudrait pouvoir sortir les logs de l'application "Sync" et voir si les données sont bien chargées car l'application "OccTax" ne fait qu'interroger l'application "Sync" pour lister les données. Avec la commande `adb` ça donne ceci :

```bash
adb logcat | grep fr.geonature
```

Après avoir lancé l'application "OccTax", on doit retrouver ce genre de logs :

```
...
06-18 20:45:30.655  6063  6063 D fr.geonature.commons.model.MountPoint: MountPoint: '/sdcard', canonical path: '/storage/emulated/0'
06-18 20:45:30.656  6063  6063 D fr.geonature.commons.util.MountPointUtils: internal storage from system environment: MountPoint(mountPath=/storage/emulated/0, storageType=INTERNAL)
06-18 20:45:30.656  6063  6063 I fr.geonature.sync.MainApplication: internal storage: MountPoint(mountPath=/storage/emulated/0, storageType=INTERNAL)
06-18 20:45:30.656  6063  6063 D fr.geonature.commons.model.MountPoint: MountPoint: '/sdcard', canonical path: '/storage/emulated/0'
06-18 20:45:30.656  6063  6063 D fr.geonature.commons.util.MountPointUtils: internal storage from system environment: MountPoint(mountPath=/storage/emulated/0, storageType=INTERNAL)
06-18 20:45:30.685  6063  6063 D fr.geonature.commons.model.MountPoint: MountPoint: '/storage/emulated/0', canonical path: '/storage/emulated/0'
06-18 20:45:30.686  6063  6063 D fr.geonature.commons.util.MountPointUtils: external storage not found
06-18 20:45:30.686  6063  6063 I fr.geonature.sync.MainApplication: external storage: null
...
```

où on peut voir les points de montage trouvés.

**Comment by Chrispnv** [comment]
Au téléphone tu me disais d'installer une appli windows pour interroger les logs via adb, peux tu me donner un lien.
Merci.

**Comment by sgrimault** [comment]
Le lien suivant pointe sur la page de téléchargement de l'environnement de développement pour Android :
https://developer.android.com/studio#downloads

Il va installer l'intégralité de l'environnement de développement pour Android avec notamment la suite d'outils comme `adb`.

Plus bas, on peut aussi uniquement télécharger les outils en ligne de commande, par exemple pour Windows :
https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip

Si on veut limiter la place occupée sur le disque.

Ensuite, il faut dézipper l'archive et placer le contenu dans le répertoire qui convient.
Dans ce répertoire, on doit donc trouver le sous-répertoire `tools/`.
En ligne de commande, se placer dans le répertoire d'installation et exécuter les commandes suivantes :

```bash
$ tools/bin/sdkmanager --install tools platform-tools
```

Accepter la licence pour poursuivre l'installation des outils (notamment `adb`). Une fois l'installation terminée, on doit trouver un nouveau sous-répertoire `platform-tools/` toujours dans le répertoire d'installation dans lequel on peut trouver l'utilitaire `adb`.

**Comment by Chrispnv** [comment]
Sébastien,
voici le log Geonature généré et récupéré via adb.
[log_geonature.txt](https://github.com/PnX-SI/gn_mobile_occtax/files/3310418/log_geonature.txt)

**Comment by sgrimault** [comment]
Ok merci :)

D'après les logs :

```
06-20 14:21:10.488  2939  2966 D fr.geonature.commons.model.MountPoint: MountPoint: '/sdcard', canonical path: '/storage/emulated/0'
06-20 14:21:10.488  2939  2966 D fr.geonature.commons.util.MountPointUtils: internal storage from system environment: MountPoint(mountPath=/storage/emulated/0, storageType=INTERNAL)
06-20 14:21:10.488  2939  2966 D fr.geonature.sync.data.LocalDatabase: Loading local database '/storage/emulated/0/Android/data/fr.geonature.sync/databases/data.db'...
```
L'application charge la base de données locale depuis `/sdcard/Android/data/fr.geonature.sync/databases/data.db`.

Pour faire simple, il faudrait donc supprimer tous les fichiers présents dans le répertoire `/sdcard/Android/data/fr.geonature.sync/databases` puis de copier dans ce même répertoire le fichier `data.db` présent dans la release note de l'application "Sync".

Mais auparavant et aussi par curiosité, on peut aussi récupérer les fichiers actuellement présents dans le répertoire `/sdcard/Android/data/fr.geonature.sync/databases` puis de l'ouvrir avec un client SQLite (par exemple [DB Browser for SQLite](https://sqlitebrowser.org)) et de voir si on a bien des données présentes ou non.

**Comment by Chrispnv** [comment]
J'ai ouvert le fichier /sdcard/Android/data/fr.geonature.sync/databases/data.db initial avec DB Browser for SQlite
Il contient bien toutes les données sur les observateurs (observers) et sur les espèces (taxa).

Je ne comprends où récupérer le data.db dans la release note. C'est un nouveau fichier ?

**Comment by camillemonchicourt** [comment]
Oui c'est un petit fichier fourni avec la release (https://github.com/PnX-SI/gn_mobile_core/releases/tag/0.0.2) : 

![image](https://user-images.githubusercontent.com/4418840/60177024-280ba680-9818-11e9-9f99-ffe7662c4cfd.png)

**Comment by Chrispnv** [comment]
C'est bien le fichier que j'ai récupéré. Je pensais qu'il y avait un nouveau fichier ailleurs. 
Le contenu du fichier initial sur le mobile est le même que celui sur Github.
J'ai quand même effectué la manip jusqu'au bout, c'est à dire vider le rep databases et remettre le fichier data.db.
Cela ne change rien, on ne voit ni observateurs ni espèces dans l'interface OccTax mobile.

**Comment by sgrimault** [comment]
Je vais refaire une nouvelle release avec plus de logs des deux cotés. Car coté "Sync" ce serait ok vu que les données sont bien présentes et que l'accès à la base de données fonctionne. J'ai donc besoin de savoir si le lien entre les deux applications fonctionne aussi.
