### ISSUE TITLE
Besoin d'aide pour le paramétrage de la coloration des taxons + synchro liste taxon

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/gn_mobile_occtax#81]
Bonjour,

En phase de test de la version mobile d'OccTax, je fais face à plusieurs petits problèmes, certainement lié à mon niveau de maîtrise encore limité de l'outil.
(Je n'ai pas connaissance de la version de taxhub sur les instance BRGM)

**Premier problème - Affichage des couches vectorielles**
J'ai extrait de ref_geo.l_area les mailles 1km reprojetées en WGS84:EPSG4326 et j'ai enregistré le fichier en wkt (l'id étant id_area) 
Extrait :

```
117538,MULTIPOLYGON(((-1.19616802073987 48.9825030951776,-1.19689381384788 48.9914825278172,-1.18324875629564 48.9919594609003,-1.18252531405701 48.9829799498928,-1.19616802073987 48.9825030951776)))
117539,MULTIPOLYGON(((-1.19689381384788 48.9914825278172,-1.19761985783734 49.0004618799938,-1.1839724486077 49.0009388914596,-1.18324875629564 48.9919594609003,-1.19689381384788 48.9914825278172)))
117540,MULTIPOLYGON(((-1.19761985783734 49.0004618799938,-1.19834615283824 49.009441151476,-1.18469639112276 49.0099182413394,-1.1839724486077 49.0009388914596,-1.19761985783734 49.0004618799938)))
117544,MULTIPOLYGON(((-1.20052654521072 49.0363784794409,-1.20125384555897 49.0453574258303,-1.18759466580744 49.045834829433,-1.18686972118294 49.0368558045865,-1.20052654521072 49.0363784794409)))
118309,MULTIPOLYGON(((-1.18180212176234 48.9740003586686,-1.18252531405701 48.9829799498928,-1.1688823574302 48.9834552529424,-1.16816151532669 48.9744755836193,-1.18180212176234 48.9740003586686)))
```

Je place le fichier sur la carte SD (au même endroit que le SCAN25 en mbtiles qui fonctionne bien) mais les mailles ne s'affichent pas sur la carte même si je vais les cocher dans la liste des couches. 
La configuration est la suivante (occtax/settings.json) : 
```
{
  "map": {
    "area_observation_duration": 365,
    "show_scale": true,
    "show_attribution": true,
    "show_compass": true,
    "max_bounds": [
      [
        42.62826733061433,
        -0.8016423262464326
      ],
      [
        43.22256196933102,
        0.4281502819777965
      ]
    ],
    "center": [42.922276035501696, -0.16777084451550842],
    "start_zoom": 10.0,
    "min_zoom": 10.0,
    "max_zoom": 16.0,
    "min_zoom_editing": 12.0,
    "layers": [
      {
        "label": "IGN-SCAN25",
        "source": "scan25.mbtiles"
      },
      {
        "label": "Mailles 1km",
        "source": "maille1km.wkt",
        "properties": {
	        "style": {
	          "stroke": true,
	          "color": "#FF0000",
	          "weight": 8,
	          "opacity": 0.9,
	          "fill": true,
	          "fillColor": "#FF8000",
	          "fillOpacity": 1
	        }
	      }
      }
    ]
  }
}
```
ps : j'ai essayé en geojson et avec différentes projections, aucune couche vectorielle ne s'affiche sur la carte... Je sèche...

**Second problème - coloration des taxons**
Je souhaite activer la coloration des taxons selon la maille où se fait l'observation.
J'ai configurer sync/settings.json avec : 
```
  "code_area_type": "M1",
```

J'ai ajouté dans la table gn_commons.t_parameters la ligne suivante : 
```
insert into gn_commons.t_parameters (
	id_organism, 
	parameter_name,
	parameter_desc,
	parameter_value
)
values (
	0,
	'occtaxmobile_area_type',
	'Code de la zone utilisé pour la coloration des taxons sur OccTax-Mobile',
	'M1'
)
```

La synchronisation d'OccTax-Mobile se fait mais aucune coloration dans la liste des taxons... 
Est-ce qu'il me manque quelque chose ?

**Troisième problème - Synchronisation des taxons**
J'ai réalisé une liste réduite de taxon sur taxhub (id_liste = 101) qui contient 9792 taxons uniques (=cd_ref).
Je configure sync/settings.json pour qu'il ce synchronise avec cette liste :
```
"taxa_list_id": 101,
"page_size": 1000,
"page_max_retry": 20
```
Je lance la synchro, tout semble bien se passer mais lorsque je suis en saisie sur octax-mobile, je n'ai le choix qu'entre 6403 taxons.
Ou sont passés les autres ?

ps : https://gnpyr.brgm-rec.fr/taxhub/api/taxref/allnamebylist/101?limit=20000 me retourne 13882 résultat (nombre de taxon + nombre de taxon avec un nom vernaculaire)

Je vous remercie par avance pour les éclairages que vous pourriez m'apporter

**Comment by xavyeah39** [comment]
Bonjour,

> Premier problème - Affichage des couches vectorielles
> J'ai extrait de ref_geo.l_area les mailles 1km reprojetées en WGS84:EPSG4326 et j'ai enregistré le fichier en wkt (l'id étant id_area)

As-tu essayé avec une conversion en polygone unique de sorte a avoir des `POLYGON` comme dans l'exemple de la doc ? Dans ton exemple tu es en multi.  Chez moi, c'est OK avec de `POLYGON`

> ps : j'ai essayé en geojson et avec différentes projections, aucune couche vectorielle ne s'affiche sur la carte... Je sèche...

As-tu bien fermé complétement l'application Sync après avoir fait tes modifs dans le settings.json sur le serveur (pour que celui-ci soit bien rechargé). De mon côté pas eu de soucis avec un geojson exporté depuis QGIS en WGS84 et après renommage de champ `id_area` en `id` (et suppressions des autres champs inutiles).

> La synchronisation d'OccTax-Mobile se fait mais aucune coloration dans la liste des taxons...
> Est-ce qu'il me manque quelque chose ?

Peut-être lié au fait de couche vectorielle ne se charge pas correctement dans l'appli ?-> pas d'intersection avec ton pointage.

**Comment by xavyeah39** [comment]
> Je lance la synchro, tout semble bien se passer mais lorsque je suis en saisie sur octax-mobile, je n'ai le choix qu'entre 6403 taxons.
> Ou sont passés les autres ?

Si j'ai bien compris, cela doit être lié à https://github.com/PnX-SI/gn_mobile_occtax/issues/61#issuecomment-691929260

**Comment by lepontois** [comment]
Merci pour ces éléments

Sur ce dernier point, la dernière synchro m'a bien récupéré l'intégralité des taxons... Je n'ai malheureusement aucune explication...

Je regarde pour ma couche vecteur des maille 1km et vous tiens au courant

**Comment by lepontois** [comment]
J'ai créé un nouveau wkt en forçant la géométrie en polygone.
J'ai adapté la config pour pointer vers ce nouveau fichier.
J'ai effacé toutes les données de sync et occtax.
J'ai relancer sync, il m'a synchronisé 9133 taxons cette fois (il en manque toujours un peu..)
Je lance occtax et les mailles s'affichent bien sur la carte ! 
Par contre toujours pas de coloration des taxons..

Il y a du mieux !

**Comment by lepontois** [comment]
Je constate que le style appliqué à la couche des mailles n'a aucun effet sur son affichage...

**Comment by xavyeah39** [comment]
Cool déjà. Le plus simple à générer c'est encore le geojson je trouve.

En fait, c'est lié à ta pagination des routes dans le fichiers de `settings.json` de sync.
Ton nombre total de résultats renvoyés (1000 x 20) est suffisant pour tes taxons mais pas pour ton nombre de mailles à priori.
Du coup, il y a de grandes chances pour que tu fasses un test de pointage dans une maille dont l'info `color_taxon` n'a pas été synchronisée.
Il te faut donc adapter la pagination des résultats renvoyées par les routes en fonction du nombre d'entités présentes dans la vue gn_synthese.v_color_taxon_area et là ça devrait rouler.

++

**Comment by xavyeah39** [comment]
> Je constate que le style appliqué à la couche des mailles n'a aucun effet sur son affichage...

Pas de soucis de mon côté. 
Après avoir modifié le settings de occtax, il faut bien refermer complètement l'application sync (kill) pour bien resynchroniser les fichiers de settings des applis sur le terminal et que les modifs s'appliquent.

**Comment by lepontois** [comment]
Merci pour ton suivi !

j'ai actuellement plus de 305'000 lignes dans gn_synthese.v_color_taxon_area.
J'ai donc mis 1000 x 306 dans les paramètres et 9197 taxons sont remontés (il m'en manque toujours un peu - attendu : 9792).
La coloration des taxons fonctionne !

Question, va-t-il falloir adapter les paramètres au fil des données saisies ?
Que se passe-t-il si je lui met dès à présent des valeurs importantes (ex 1000 x 1000) ?

Pour le style de la couche, j'ai beau relancer les app, ça ne change rien pour l'instant... Je vais creuser un peu plus.

**Comment by xavyeah39** [comment]
> Question, va-t-il falloir adapter les paramètres au fil des données saisies ?
> Que se passe-t-il si je lui met dès à présent des valeurs importantes (ex 1000 x 1000) ?

Bonnes questions... 
Oui, on peut mettre des valeurs importantes par anticipation sans que cela n'affectent le temps de synchronisation. De ce que je comprends, l'appel des routes s'arrête quand il n'y a plus de résultats renvoyés par celles-ci.
Chez moi j'ai un peu moins de 100000 lignes dans v_color_taxon area et en testant avec des valeurs à 50000 x 1000, ça fonctionne parfaitement.

**Comment by camillemonchicourt** [comment]
Alors beaucoup de sujets en 1, voici des éléments de réponse : 

- J'ai un peu réorganisé la documentation (dans la branche ``develop`` uniquement pour le moment) il y a quelques jours et je viens d'y ajouter un schéma global d'architecture (à compléter et mettre au propre) : https://github.com/PnX-SI/gn_mobile_occtax/blob/develop/docs/installation-fr.md
- OK pour le fichier des unités géographiques, de mon côté je n'ai testé qu'avec des geojson en 4326 et une fois bien formaté comme indiqué dans la documentation ça fonctionnait bien. @amandine-sahl vient de financer une évolution à venir pour ne les afficher qu'à partir d'un certain de zoom, car sur un grand territoire, cela peut être lourd à afficher
- Concernant le paramètre ``page_max_retry`` il vaut mieux le définir assez large, pas besoin de le bouger en permanence. En effet l'application Sync-mobile va interroger la route, mais si elle arrive au bout des résultats, elle va s'arrêter, même si le nombre de boucle n'a pas atteint la valeur de ``page_max_retry``, voir la documentation qui indique cela : 

> Les conditions d'arrêt de l'interrogation de ces routes sont :
> - Nombre d'appels = page_max_retry
> - Tableau de valeurs vide
> - Taille du tableau de valeurs < page_size
> - Erreur 404

- Concernant la route qui renvoie les couleurs de chaque taxon par unité géographique, le fonctionnement a été entièrement revu dans la 2.6.0 : https://github.com/PnX-SI/GeoNature/issues/997. En effet jusqu'à présent le fonctionnement était assez lourd à calculer et utiliser. On avait une table qui stockait l'info, mise à jour par trigger à chaque insert/update dans la Synthèse de GeoNature. L'info était calculée pour tous les types de zonages présents dans le ``ref_geo`` alors qu'on l'utilisait que pour un type de zonage. C'est pour ça qu'on a supprimé le trigger dans la 2.6.0 de GeoNature et on a remplacé la table qu'il alimentait par une vue. On a aussi ajouté le paramètre ``gn_commons.t_parameters.occtaxmobile_area_type`` qui est utilisé par le vue pour limiter le calcul uniquement sur un type de zonages (https://github.com/PnX-SI/GeoNature/blob/master/data/core/synthese.sql#L962-L970). Cela va ainsi fortement réduire le nombre de résultats dans la vue ``gn_synthese.v_color_taxon_area``. Mais je pense que tu es pas encore en 2.6.0. Dans tous les cas ce n'est pas déterminant, car Occtax-mobile n'interroge pas toute la route, mais la filtre sur un seul type de zonage, défini au niveau du paramètre dans la conf de Occtax-mobile, dans ton cas : https://gnpyr.brgm-rec.fr/geonature/api/synthese/color_taxon?code_area_type=M10&limit=10&offset=20

**Comment by lepontois** [comment]
Merci Camille pour ces éléments.

J'ai donc bien augmenté la valeur de "page_max_retry" pour être tranquille.
Je suis bien en GN 2.5.5 et j'ai donc anticipé le paramètre gn_commons.t_parameters.occtaxmobile_area_type qui ne doit alors avoir aucun impact dans l'immédiat. Pas grave.

Je constate tout de même que la synchro des taxons a un comportement étrange car suite à la dernière synchro, je suis passé de 9197 taxons à 8944 sans raison apparente ... Peut-être que ces mieux gérés sur la 2.6...

C'est une bonne chose que de faire évoluer OccTax mobile pour pouvoir paramétrer le seuil de zoom.

**Comment by xavyeah39** [comment]
Yes merci Camille :)
Voici une proposition de modestes compléments à la doc d'installation où j'ai essayé de clarifier quelques bricoles : 
https://github.com/xavyeah39/gn_mobile_occtax/blob/develop/docs/installation-fr.md

Camille, peux-tu jeter un coup d'oeil et relire ? Ou tu préfères une PR directe ?

**Comment by camillemonchicourt** [comment]
OK quand tu passeras en 2.6.0, fais gaffe car l'update SQL ajoute ce paramètre.

Pour la synchronisation, je ne sais pas ce qu'il se passe, la route renvoie tous les synonymes mais aussi une ligne pour le nom scientifique et une autre pour le nom vernaculaire. Et ensuite l'application Sync-mobile s'occupe de remettre tout ça en forme à sa sauce.
En tout cas, il n'y a aucun changement dans la 2.6.0 sur ce que renvoie la route.
Plutôt à voir au niveau de Occtax-mobile.

**Comment by camillemonchicourt** [comment]
Oui une PR est idéale, avec plaisir !

**Comment by JulienCorny** [comment]
Bonjour,

J'ai le même souci pour la synchronisation du nombre de taxons, je devrais en avoir 8432 mais seulement 5369 sont proposés. 
- GN 2.5.5
- apk gn_mobile_occtax : release 1.1.4
- apk gn_mobile_core : release 1.1.4
- 31000 lignes dans gn_synthese.v_color_taxon_area (page_size : 5000 x page_max_retry : 10). 

J'ai essayé de faire varier les valeurs de page_size et page_max_retry, ça ne change que faiblement le nombre de taxons retournés (entre 5000 et 5400). 

Est-ce que quelqu'un a rencontré/résolu ce problème depuis les derniers échanges ? 

Merci !

**Comment by DonovanMaillard** [comment]
Sur ce dernier point, avec les pre-release de sync et occtax, pas de soucis de mon coté.  page_size 200, max-retry_100 il me sort bien tous mes taxons. Et avec des variables plus vaibles (200-20) il me limitait bien la récupération à 4.000

**Comment by JulienCorny** [comment]
Salut Donovan,
Merci pour ta réponse, j'ai installé les pre-release de sync et occtax, toujours le même souci. Je fais varier les page_size et max-retry, j'obtiens entre 6000 et 7300 taxons. Même sans faire varier les page_size et max-retry j'obtiens des nombres légèrement différents d'une synchronisation à l'autre.

**Comment by camillemonchicourt** [comment]
Ce soucis m'est familier mais je ne sais plus quand et comment je l'ai eu et si je l'ai toujours. 🤔
@sgrimault une idée ou une piste pour élucider cela ?

**Comment by sgrimault** [comment]
Bonjour,
J'aurais besoin de logs pour voir un peu ce qu'il se passe lors de la synchronisation.
@camillemonchicourt c'est bien en lien avec #61

**Comment by JulienCorny** [comment]
Bonjour,

Bon désolé ça fonctionne en fait en prenant en compte le nombre de taxons qu'il y a dans gn_synthese.v_color_taxon_area comme indiqué plus haut et mettant 1 en page_max_retry. 

J'ai 31000 lignes dans gn_synthese.v_color_taxon_area donc en indiquant 50000 en page_size x 1 en page_max_retry ça fonctionne, j'ai récupère bien mes 8432 taxons. 

Au départ j'avais tenté des config avec des page_retry, par exemple 10000 en page size x 5 en page_max_retry, et là ça fonctionne pas, ça met un nombre de taxons aléatoire. 

Merci pour votre aide !

**Comment by camillemonchicourt** [comment]
OK mais du coup ce n'est pas normal ni souhaitable car c'est risqué de mettre 50000 en page_size, ça fait beaucoup d'un coup.
