### ISSUE TITLE
impossible de changer le jeu de donnée lors de la saisie d'un taxon

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#85]
Bonjour,
Nous utilisons la version 1.7.3 de taxhub et nous avons mis à jour du coup la version mobile en prenant la version 1.1.4 qui est compatible avec geonature 2.5.5
On me signale un problème dans la saisie des taxons sur l'application téléphone. Nous avons plusieurs jeux de donnée et un en particulier est toujours sélectionné. Impossible de sélectionner un autre jeu de donnée, l'application après choux retourne sur celui par défaut.
La mise à jour de l'application a été faite automatiquement à partir des informations stockées dans geonature\backend\static\mobile 
Comment peut-on corriger ? Est ce lié à la mise à jour ? Doit-on réinstaller l'application en manuel ?
Christian Bièche
Cistude

**Comment by camillemonchicourt** [comment]
Le soucis s'est reproduit ?
Ça me dit rien.
La liste des JDD est bien disponible ?

**Comment by DonovanMaillard** [comment]
ticket sans réponse, différentes modifications conséquentes ont été apportées dans les dernières versions d'Occtax-mobile et notamment sur la synchronisation. Le soucis n'est pas reproduit sur les versions 2.x
