### ISSUE TITLE
bouton ajout taxons inactif

### ISSUE THREAD

**Issue by aferchal** [PnX-SI/gn_mobile_occtax#89]
Sur les applis GN hébergées BRGM Guadeloupe (dev et prod) le module occtax fonctionne bien sauf qu'on ne peut pas ajouter plus de 1 taxon à un relevé. Le clic sur le + à la fin ne propose rien et on reste donc dans une relation 1 relevé - 1 taxon alors que j'ai lu que le mobile permettait de saisir 1 relevé - n taxons
A noter des différences de versions entre les instances mais meme pb sur les 2 :
DEV = SYNC 1.1.4 et OCCTAX 1.2.0
PROD = SYNC 1.1.7 et OCCTAX 1.2.2

**Comment by camillemonchicourt** [comment]
Je pense que c'est le soucis discuté ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/87
Et corrigé dans Occtax-mobile 1.2.3.

**Comment by aferchal** [comment]
ok, pas vu car ticket fermé. A voir si poss de déployer le 1.2.3 sur BRGM
Merci

**Comment by camillemonchicourt** [comment]
@aferchal, tu as bien fait.
Tu peux aussi voir le détail des versions existantes dans la page dédiée : https://github.com/PnX-SI/gn_mobile_occtax/releases
