### ISSUE TITLE
Test OccTax 0.1.2

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_occtax#9]
La synchronisation fonctionne bien (je vois les listes des observateurs/taxons);
OccTax a l'air de bien s'installer mais dès que je l'ouvre il se ferme ("OccTax a cessé de fonctionner")

Log de adb en pj
[log_geonature.txt](https://github.com/PnX-SI/gn_mobile_occtax/files/3392435/log_geonature.txt)

**Comment by sgrimault** [comment]
Bonjour,
Pourriez vous me transmettre le fichier de paramétrage de l'application (`settings_occtax.json`) ?
Avez vous pu aussi ajouter un jeu de données cartographique à l'application ?
Est ce que vous aviez une version précédente de l'application "OccTax" d'installée ? Si oui, pourriez vous tout désinstaller et de repartir sur une base vierge (aucune application d'installée).

**Comment by ClaireLagaye** [comment]
Bonjour,
Au retour de vacances j'ai testé une nouvelle fois sur un nouvel appareil.
En changeant le fichier de settings et en mettant un mbtiles de test, j'arrive à ouvrir l'application.
Voici les observations que j'ai faites:
- Je suis obligée de mettre en dur le chemin de mon répertoire avec le nom de la carte SD sinon j'ai une erreur de chargement du fichier de settings: dans mon cas /storage/C0A5-1AE0/Android/data/fr.geonature.maps.sample - ou alors il existe une façon de spécifier la carte SD que je ne connais pas
- La spécification de l'observateur par défaut semble ne pas être prise en compte
- Quand on sélectionne un observateur puis qu'on clique sur modifier, au retour dans la fenêtre Observateur & date, la fenêtre ne se recharge pas (il faut quitter puis réouvrir le relevé pour voir que le changement a en effet été réalisé). Pour la date ça fonctionne
- Dans le module carto, il semble y avoir un problème d'affichage du mbtiles avec une mauvaise superposition des échelles (j'ai mis la capture d'écran ainsi que la visu du même mbtiles dans oruxmaps)
![mbtiles_occtax](https://user-images.githubusercontent.com/11782642/63779929-ab647980-c8e7-11e9-9d39-e7855e8a0103.png)
![mbtiles_oruxmaps](https://user-images.githubusercontent.com/11782642/63779932-ab647980-c8e7-11e9-8ecf-67411527e7ad.png)
- La spécification dans les paramètres de voir ou pas l'échelle semble ne pas être prise en compte
- Dans le module carto encore on voit les limites des dalles, est-il possible de les enlever?
- Dans le module carto, d'aprés ce que je comprends quand on clique sur l'outil de saisie de point, le point se crée au centre de la carte et on peut le modifier ensuite. 
Problème: quand je clique je ne vois rien à l'écran, il me faut zoomer ou dézoomer pour qu'il apparaisse
- Si j'édite le point saisi, il y a un phénomène de multiplication des points... Sinon l'outil de modification du point est simple et efficace.
![saisie_point](https://user-images.githubusercontent.com/11782642/63782237-5fb3cf00-c8eb-11e9-99ce-ca3f75a94014.png)
- Si je spécifie plusieurs fonds de carte dans le fichier de settings, je ne vois que le dernier dans l'appli
Sinon,  la  navigation dans la carte est facile et  fluide (je n'ai pas encore testé avec de gros fichiers de fonds de carte)

**Comment by sgrimault** [comment]
Bonjour @ClaireLagaye 

Je vous remercie pour votre retour. Pourriez vous me faire partager votre fichier de paramétrage de l'application `settings_occtax.json` ainsi que les logs de l'application après lancement ?
Je voudrais m'assurer que les accès à la carte SD (interne et/ou externe) se fassent bien.

Concernant votre retour :

* > Je suis obligée de mettre en dur le chemin de mon répertoire avec le nom de la carte SD sinon j'ai une erreur de chargement du fichier de settings: dans mon cas /storage/C0A5-1AE0/Android/data/fr.geonature.maps.sample - ou alors il existe une façon de spécifier la carte SD que je ne connais pas

  Coté carte, il faut effectivement mettre un chemin absolu pour indiquer le répertoire où se trouve le répertoire des fonds cartographique. À terme, on pourra aussi spécifier un chemin relatif qui privilégiera la carte SD externe si elle est présente.

* > La spécification de l'observateur par défaut semble ne pas être prise en compte

  Je l'ai aussi constaté de mon coté et c'est un bug.

* > Quand on sélectionne un observateur puis qu'on clique sur modifier, au retour dans la fenêtre Observateur & date, la fenêtre ne se recharge pas (il faut quitter puis réouvrir le relevé pour voir que le changement a en effet été réalisé). Pour la date ça fonctionne

  À retester du coup lors de la prochaine version car je n'ai pas de souci de mon coté.

* > Dans le module carto, il semble y avoir un problème d'affichage du mbtiles avec une mauvaise superposition des échelles (j'ai mis la capture d'écran ainsi que la visu du même mbtiles dans oruxmaps)

  Vous voulez parler de la barre d'échelle affichée en bas à gauche ? Effectivement, les valeurs sont différentes et dans l'exemple que vous montrez avec "OccTax", vu que le zoom est plus élevée, la valeur de l'échelle devrait être plus faible. De mon coté, c'est un composant standard de la bibliothèque sous-jacente utilisée. Je regarderai du coup si il y a un souci lors du calcul de l'échelle.

* > La spécification dans les paramètres de voir ou pas l'échelle semble ne pas être prise en compte

  Oui, ce n'est pas encore pris en compte.

* > Dans le module carto encore on voit les limites des dalles, est-il possible de les enlever?

  En mode "debug" de l'application, le module cartographique devient plus bavard (dans les logs) et affiche des données supplémentaires sur la carte notamment sur la disposition des tuiles. Du coup on voit effectivement les limites des tuiles. Pour l'instant, je préfère rester dans ce mode là (debug) pour éventuellement faciliter les échanges en cas de problème remontés.

* > Dans le module carto, d'aprés ce que je comprends quand on clique sur l'outil de saisie de point, le point se crée au centre de la carte et on peut le modifier ensuite.
Problème: quand je clique je ne vois rien à l'écran, il me faut zoomer ou dézoomer pour qu'il apparaisse

  C'est bien entendu le comportement attendu. Suite à votre remarque précédente, je ferais du coup deux releases différentes : une en version "debug" (pour les logs, etc.) et une en version "normale" (le mode qui sera utilisé à terme).

* > Si j'édite le point saisi, il y a un phénomène de multiplication des points... Sinon l'outil de modification du point est simple et efficace.

  Même remarque que précédemment, il faudrait que j'arrive à voir d'où vient ce comportement que vous décrivez ; d'où deux releases histoire de voir si le mode "debug" coté module cartographique ne créé pas des effets de bords.

* > Si je spécifie plusieurs fonds de carte dans le fichier de settings, je ne vois que le dernier dans l'appli

  Je n'ai pas vraiment testé tous les cas possibles sur cette partie, mais l'idée est la suivante :
  * Un fond de carte est une source pointant sur un fichier MBTiles (extension `*.mbtiles`) (On pourrait choisir d'autre types de source mais pour l'instant j'ai volontairement limité à ce type de source).
  * Si on définit plusieurs fonds de carte, la première qui répond à la question "donne moi la tuile aux coordonnées x, y pour le zoom z" a gagné. Si jamais on indique deux fonds de carte couvrant la même zone géographique pour les mêmes niveaux de zoom, on ne verra qu'une des deux (avec aussi comme effet de bord possible de voir un mix de tuiles entre les deux...)
  * Si on veut correctement définir plusieurs fonds de carte, il faut que la première couvre une zone géographique pour une plage de zoom donnée, la seconde peut couvrir la même zone géographique mais la plage de zoom doit être différente de la première pour être visible ou couvrir une autre zone géographique adjacente à la première avec les mêmes niveaux de zoom.

**Comment by ClaireLagaye** [comment]
@sgrimault 
Voici le fichier de settings que j'utilise

```
{
  "map": {
    "base_path": "/storage/C0A5-1AE0/Android/data/fr.geonature.maps.sample",
    "show_scale": true,
    "show_compass": true,
    "max_bounds": [
      [
        45.419299,
        6.910915
      ],
      [
        45.336943,
        6.782684
      ]
    ],
    "center": [
      45.38,
      6.83
    ],
    "start_zoom": 10.0,
    "min_zoom": 8.0,
    "max_zoom": 16.0,
    "min_zoom_editing": 15.0,
    "layers": [
      {
        "label": "Scans",
        "source": "scan.mbtiles"
      },
	  {
        "label": "Ortho",
        "source": "ortho.mbtiles"
      }
    ]
  }
}
```
Pour les autres points

- La mauvaise superposition des échelles dont je parle est la superposition de différents niveaux de zoom (pour ma zone cœur, cela fonctionne bien au niveau 10 mais à l'extérieur je vois apparaître les niveaux 6-7-8 avec une mosaïque étrange). C'est assez clair sur les captures d'écran.
- OK pour avoir 2 releases debug/normale qui permettront de mieux voir le résultat final
- Dans mon fichier de settings, j'ai 2 fonds de carte spécifiés, qui ont exactement la même étendue et niveaux de zoom (scans et orthos), je voulais savoir s'il était possible une fois dans la carte de passer de l'un à l'autre pendant la saisie (comme c'était le cas précédemment) pendant la saisie
- N'avoir que du mbtiles nous convient

**Comment by camillemonchicourt** [comment]
> Coté carte, il faut effectivement mettre un chemin absolu pour indiquer le répertoire où se trouve le répertoire des fonds cartographique. À terme, on pourra aussi spécifier un chemin relatif qui privilégiera la carte SD externe si elle est présente.

En effet, il n'est pas envisageable à terme de renseigner le chemin absolu avec le nom de la carte au niveau de chaque terminal mobile.

**Comment by sgrimault** [comment]
Pourriez vous supprimer le répertoire `/storage/C0A5-1AE0/Android/data/fr.geonature.maps.sample/tiles` (et tout le contenu) ?
Par défaut, le cache ne devrait pas fonctionner en mode "offline" mais la bibliothèque cartographique créé quand même un répertoire de cache...
Concernant vos MBTiles et vu qu'ils couvrent la même zone est ce que toutes les tuiles sont bien présentes à tous les niveaux de zooms sur la zone en question ?
J'ai fais ce test de mon coté :
* Premier MBTiles limité aux zooms 12 à 15, pour une zone précise avec toutes les tuiles présentes pour chaque zoom selon la zone en question. La carte s'affiche correctement et les zones vides restent en fond gris
* Second MBTiles limité aussi en niveau de zoom (6 à 15) mais où les tuiles ne sont pas toutes présentes pour les zooms supérieurs et les tuiles aux zooms inférieurs couvrent une zone beaucoup plus grande. Du coup en zoomant sur la carte, les zones vides pour le zoom donnée seront comblés à partir des tuiles présentes aux zooms inférieurs. D'où l'effet d'avoir des zones plus ou moins pixelisés visibles sur la carte.

Sur la carte il manquerait un widget permettant la sélection des couches courantes avec deux types de couches :
* les couches raster (MBTiles)
* les couches vectorielles

Dans le cas des couches raster, on ne voit que les couches actives selon le zoom donnée dans le cas où on a plus d'une couche qui peut répondre à la zone demandée pour un zoom donnée. Dans le cas par défaut, ce sera une seule couche visible à un niveau de zoom donnée.

**Comment by sgrimault** [comment]
Je ferai une nouvelle release prochainement qui corrigera notamment un certains nombre de points, ainsi que quelques améliorations UX lors de la saisie d'un POI sur la carte :
* Observateur par défaut sélectionné (si défini) lors d'une nouvelle saisie
* Prise en compte des préférences utilisateur pour la partie cartographique (affichage de l'échelle et boussole)
* Correction du bug du POI "dupliqué" sur la carte. Il intervient quand on revient sur l'étape précédente puis on revient sur l'étape "Pointage".
* Quand on revient sur carte et qu'elle contient déjà un POI, la carte se recentre automatiquement sur ce POI.
* Quand on sélectionne un POI, la carte est se recentre automatiquement sur ce POI.
* Quand on commence à déplacer le POI sur la carte (mode édition via un toucher long), la carte se recentre automatiquement sur le POI uniquement dès qu'on s'approche du bord visible. Par défaut il reste en état afin de faciliter le pointage.
* Quand on quitte le mode édition, la carte se recentre automatiquement sur le POI nouvellement modifié.

**Comment by camillemonchicourt** [comment]
Depuis la version 0.2.9, il n'est plus obligatoire de préciser le paramètre ``base_path`` pour indiquer où se trouve le répertoire des fonds de carte. Maintenant ce paramètre reste optionnel et par défaut l'application va d'abord scanner les répertoires de la carte SD externe (si présente) avant d'aller le faire sur la mémoire interne.

Ce paramètre peut prendre comme valeur soit un chemin absolu (résolution la plus rapide pour charger les fonds de carte), soit un chemin relatif selon le point de montage (carte SD externe ou mémoire interne). Si il n'est pas présent, l'application cherchera d'abord sur la carte SD externe puis ensuite sur la mémoire interne les fonds de carte (résolution la plus lente).
