### ISSUE TITLE
Erreur de récuparation des JDD et settings.json

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_occtax#93]
Actuellement sur GN2.7.2, j'ai fait une montée de version du mobile vers la version 1.3 : 
- Erreur lors de la récupération de settings_occtax.json
- Aucune donnée dans les jeux de données -> saisie impossible. 

J'ai rétrogradé le mobile vers les versions 1.1.9 / 1.2.1 (Sync) et 1.2.4 (Occtax) -> même erreur. 

Le mois dernier j'ai modifié ma conf occtac pour le volet nomenclature, ca a bien été pris en compte. Sur les versions 1.1.9 et 1.2.4 du mobile, ca semblait donc fonctionner il y a peu. Pour le coté JDD, est-ce qu'il avait gardé les jeux récupérés avant ou est-ce que le mobile faisait bien la mise à jour... je ne sais pas. 
Dans tous les cas, plusieurs soucis qui s'entrecroisent.

Est-ce que d'autres ont ce type de soucis avec GeoNature 2.7.2 ?

**Comment by DonovanMaillard** [comment]
Réglé avec la dernière release 1.3.0 du mobile et GeoNature 2.7.5

**Comment by geobrun** [comment]
Pour info, j'ai rencontré exactement le même problème avec Occtax-mobile en 1.3.0 et GeoNature en 2.7.2. Et il s'est aussi réglé en passant en 2.7.5

**Comment by camillemonchicourt** [comment]
Merci pour ton retour.
Oui, il est indiqué dans les notes de version (https://github.com/PnX-SI/gn_mobile_occtax/releases/tag/1.3.0) que Occtax-mobile 1.3.0 n'est compatible qu'avec les versions 2.5.x, 2.6.x et 2.7.5 (et plus) de GeoNature.
Donc non compatible avec GeoNature 2.7.2.
