### ISSUE TITLE
Simplifier le déploiement en une seule appli mobile

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_occtax#94]
Bonjour,

A l'origine, la solution mobile a été développée autour de 2 applications complémentaires (Occtax et Sync) ainsi que la "brique" maps directement reprise dans Occtax. Occtax génère l'interface de saisie et stocke en json les relevés terminés, tandis que Sync se charge d'échanger les données entre le mobile et GeoNature, dans les deux sens.

L'intérêt de ce choix était de permettre une application de synchronisation commune à plusieurs applications mobiles de saisie dont occtax. Dans les faits : 

- Pour le moment seul Occtax existe pour la saisie mobile
- Les modules de saisie ont de plus en plus leur propre configuration y compris pour la partie synchronisation (listes d'utilisateurs, de taxons, de jeux de données, de champs et donc de nomenclatures) -> chaque module est donc susceptible de récupérer des informations différentes in fine, et dans certain cas on peut même imaginer sur des API différentes (sites pour du monitoring etc)
- Les autres applications mobiles à venir pourraient ne pas adopter les mêmes langages ou fonctionnements

Le bénéfice d'avoir plusieurs applications semble aujourd'hui en deça de ses inconvénients... Pour faciliter le déploiement des solutions mobiles et la maintenance, Flavia APE et les écrins proposent donc de fusionner Occtax-mobile et Sync dans une seule application mobile "tout-en-un". Les bénéfices seraient : 

- une seule application à déployer et mettre à jour, 
- une seule configuration centralisée,  
- pas de soucis/questions de compatibilités entre les versions de Sync et Occtax-mobile
- un seul dépôt pour les échanges et la documentation (plus confortable!)

L'idée pourrait être, comme pour la brique "maps", de conserver un dépôt distinct si c'est nécessaire pour les développements, mais de manière transparente pour les utilisateurs.

Est-ce que cette fusion des deux applis en une seule convient pour tout le monde ?

**Comment by DonovanMaillard** [comment]
Cette fusion sera mise en œuvre dans les prochaines semaines, dans le cadre de l'Appel à Projet "SINP" pour lequel Occtax-Mobile a été retenu. 

Les modalités seront détaillées ici.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour information sur l'avancée de ce point : 
- Le soutien de l'OFB (appel à projet SINP 2021) est désormais formalisé
- La prestation de développement débutera très rapidement. Le cahier des charges ci-dessous pour information  
[Demande devis n°1 occtax mobile - fusion applications.pdf](https://github.com/PnX-SI/gn_mobile_occtax/files/7659369/Demande.devis.n.1.occtax.mobile.-.fusion.applications.pdf)

@amandine-sahl , peux-tu nous dire via quelle route on peut connaitre l'URL Taxhub pour le retirer de la conf ? Je n'ai pas réussi à trouver l'info

**Comment by amandine-sahl** [comment]
L'url de taxhub est présent dans le fichier des settings de gn_mobile_core

**Comment by DonovanMaillard** [comment]
Merci  ! En effet, je le cherchais sur une API...

**Comment by camillemonchicourt** [comment]
Oui mais du coup, ça veut dire qu'il faut renseigner l'URL de GN, qui va récupérer la conf et à ce moment là il y trouvera l'URL de TaxHub ?
OK si possible, ça évite de saisir les 2 URL, surtout que les utilisateurs connaissent l'URL de GeoNature mais pas forcément de TaxHub.

**Comment by DonovanMaillard** [comment]
Oui c'est bien ça l'idée, une fois que l'appli a l'URL de GeoNature (tapée à la main ou scannée avec un QRCode), elle peut récupérer la configuration sur le serveur, et donc récupérer l'URL de TaxHub. Pour un déploiement de l'appli par les utilisateurs directement, via un playstore par exemple, ça évite de connaitre l'URL de TaxHub et son existence :)

**Comment by camillemonchicourt** [comment]
L'application "sync" a été intégrée en tant que module dans la version 2.0.0 de Occtax-mobile.
Désormais on n'installe donc plus que l'application Occtax-mobile sur les terminaux.
La doc a aussi revue et complétée en conséquence.

**Comment by camillemonchicourt** [comment]
Dans la version 2.1.0, la configuration a été simplifiée, en ne demandant que l'URL de GeoNature et plus de TaxHub.
Au premier lancement, une interface de configuration a été mise en place pour ne demander que l'URL du GeoNature : 

![Screenshot_20220504-084328_Occtax](https://user-images.githubusercontent.com/4418840/166666349-fb6dcd1d-cbca-4514-8e59-e88beee6160e.jpg)
