### ISSUE TITLE
Amélioration des configurations

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_occtax#95]
Après avoir réalisé l'amélioration #94 si elle fait consensus , un seul fichier de configuration centralisé serait nécessaire pour la solution Occtax-mobile. Comme aujourd'hui, cette configuration serait centralisée sur le serveur de GeoNature. Deux évolutions complémentaires seraient envisagées pour améliorer ce fonctionnement : 

- Permettre une surcouche (facultative) de la configuration centralisée par une configuration locale sur le terminal de l'utilisateur : cela permettrait aux utilisateurs les plus avancés de mieux adapter l'application à leurs besoins (déclaration de fonds de cartes additionnels, centrage des cartes autour de chez eux, masquage de certaines nomenclatures etc)
- Permettre la livraison d'une APK qui embarque directement un fichier de configuration lors de l'installation. Cela permettrait à l'utilisateur de simplement télécharger son APK auprès de son organisme, l'installer, se connecter. Et ouvrirait la possibilité de délivrer cette apk sur le playstore par exemple pour un organisme qui le souhaiterait -> l'utilisateur n'aurait qu'à télécharger son appli et se connecter. Je suis moins renseigné sur cet aspect, c'est peut-être déjà possible, mais dans ce cas à documenter.

Dans un second temps, on pourrait envisager que les paramétrages que l'utilisateur définit via son appli occtax viennent renseigner ce fichier de configuration local.

**Comment by DonovanMaillard** [comment]
Le #94  semble faire l'unanimité , la mise à jour des configurations se fera également dans les prochaines semaines, dans le cadre de l'AAP SINP.

**Comment by DonovanMaillard** [comment]
Suite des réflexions : 

- Sur le premier point, on va réfléchir à une configuration locale qui ne sera pas une surcouche mais plutôt un "complément" : celà signifie que pour tous les paramètres définis dans la conf centralisée, on appliquera cette conf. Pour les paramètres non définis de manière centralisée, il deviendrait possible d'en définir par un fichier en local. Attention si on ajoute ces paramètres dans la conf centralisée, les choix locaux ne seraient donc plus appliqués. Cette "configuration locale" permettrait notamment d'ajouter des nouvelles couches cartographiques au niveau de l'utilisateur.

- Quant au fait de fournir une apk avec fichier de conf, l'idée n'est plus forcement d'actualité, pour bien rester sur une configuration centralisée justement. En revanche, on pourra prévoir un versement sur le play-store, et que les utilisateurs n'aient qu'à rentrer l'URL de leur GeoNature ou scanner un QRCode vers cette instance. Le fichier de conf centralisé sera alors récupéré automatiquement, ce qui donne la même facilité pour l'utilisateur.

**Comment by camillemonchicourt** [comment]
Ok mais je comprends pas pourquoi les paramètres définis dans la conf locale ne surcoucheraient pas ceux de la conf centralisée. Cela perd alors de son intérêt.

Si je veux définir un dossier different des fonds de carte, un centrage différent, etc...

**Comment by DonovanMaillard** [comment]
c'était ma proposition initiale. Mais Amandine et toi aviez suggéré de ne pas faire de surcouche quand un paramètre est déjà fixé dans ka conf fournie par le serveur ;)

**Comment by camillemonchicourt** [comment]
OK bah je sais plus pourquoi, car là ça me semble pas très pertinent.
Plutôt pouvoir tout surcoucher en local...

**Comment by DonovanMaillard** [comment]
Une surcouche locale sera mise en place courant 2022

**Comment by camillemonchicourt** [comment]
Détail : 
- Offrir à l’utilisateur la possibilité de personnaliser tout ou en partie la configuration issue de GeoNature via une une configuration optionnelle sous forme de fichier JSON, à l’image de "settings_occtax.json"
- Si la configuration personnalisée est définie, l’application « Occtax » procédera à une « fusion » des paramètres en prenant d’abord en compte ceux définis coté configuration personnalisée (donc en surchargeant la valeur par défaut) puis ceux définis coté configuration issue de GeoNature si ces paramètres n’ont pas été redéfinis coté configuration personnalisée
- ⚠ Cela reste un usage strictement réservé aux utilisateurs avancés. Il n’y aura pas un écran dédié coté application pour faciliter ce paramétrage. L’utilisateur devra suivre la documentation en ligne sur le Github du projet pour constituer sa configuration personnalisée.
- En cas de problème lors du chargement de la configuration, l’information⚠ sera tracée dans les logs de l’application et ce seront les valeurs de la configuration issue de GeoNature qui prennent le dessus pour le ou les paramètres en question.

**Comment by DonovanMaillard** [comment]
Oui, ok avec tout ça. Je sais pas si la prestation d'ajout des fonds carto "perso" a été commandée ou non. De mémoire, à revoir avec @sgrimault mais ce volet là était prévu dans le même temps, puisque les couches perso iraient s'inscrire dans un fichier de conf custom

**Comment by sgrimault** [comment]
@DonovanMaillard ,
Tu parles de [#8](https://github.com/PnX-SI/gn_mobile_maps/issues/8) ? Ça fait partie d'un pack d'évolutions traité avec Christophe Chillet (cf. call prévu le 13 février).

**Comment by camillemonchicourt** [comment]
La commande PNV concerne le support des fonds IGN online.
Les sujets évoqués ci-dessus concernent la commande PNPC.

**Comment by camillemonchicourt** [comment]
Dans la 2.7.0, il est possible de surcoucher la configuration générale de l'application fournie par le serveur GeoNature, en ajoutant localement un fichier `settings_occtax.local.json`, surcouchant uniquement les paramètres que l'on souhaite différent sur un appareil.

Voir doc https://github.com/PnX-SI/gn_mobile_occtax/blob/develop/README.md#override-parameters-from-app-settings

**Comment by camillemonchicourt** [comment]
J'ai testé de créer un fichier local settings_occtax.local.json dans lequel j'ai mis :

{
  "map": {
    "center": [
      49.0,
      2.0
    ],
    "show_compass": false,
}

Mais cela ne semble pas pris en compte, il centre la carte par défaut sur les coordonnées définies dans le fichier settings_occtax.json

**Comment by sgrimault** [comment]
Bonjour @camillemonchicourt,

J'ai fais un test de mon coté et ça fonctionne bien :
```json
{
  "map": {
    "center": [49.0, 2.0],
    "show_compass": false
  }
}
```

**Comment by camillemonchicourt** [comment]
Ah oui exact, mon json était mal formaté.
Je confirme donc le bon fonctionnement du mécanisme de surcouche locale du fichier de configuration. 👍

**Comment by camillemonchicourt** [comment]
Possibilité de surcoucher localement le fichier de configuration fait dans la 2.7.0
