### ISSUE TITLE
[1.3.0] Saisie dénombrement : pas de min et max

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_mobile_occtax#96]
Bonjour,

Je teste la saisie mobile avec les 2 appli sync et occtax en 1.3.0, et GeoNature 2.7.5.

J'ai suivi la doc pour l'installation et je peux bien saisir sur mobile. Par contre, le min et le max des dénombrements sont à 1, et je n'ai pas de champ pour changer ces valeurs.
De mémoire, avec la version 1.2 d'occtax_mobile, les champs min et max apparaissaient bien. 

Est-ce un soucis avec le settings.json par défaut ? 

Merci d'avance pour votre aide !

**Comment by DonovanMaillard** [comment]
Bonjour, 

En effet la conf permet de faire apparaître ces champs. En principe ca devrait être le cas par défaut... je vérifierai a l'occasion. Dans tous les cas ces champs peuvent être ajoutes dans la conf.

**Comment by DonovanMaillard** [comment]
Bonjour @Splendens , est ce que tu as pu solutionner le soucis ?

**Comment by Splendens** [comment]
Salut ! Oui, en rajoutant les champs de min et max dans la conf, merci ! 
Et effectivement, je suis d'accord avec toi, ces champs devraient être présents par défaut.

**Comment by DonovanMaillard** [comment]
@sgrimault sera-t-il possible de corriger la valeur par défaut pour ces deux champs count_min et count_max pour les prochaines releases ? 
La doc indique que les champs count_min et count_max sont affichés par défaut, mais dans la pratique s'ils ne sont pas explicitement activés dans le settings.ini, ils ne sont pas affichés :)

**Comment by sgrimault** [comment]
L'idée est que l'on considère que ces champs restent visibles et obligatoires quelque soit la configuration ?

**Comment by camillemonchicourt** [comment]
Les champs de dénombrement sont bien présent dans l'interface par défaut, même si cela n'est pas indiqué explicitement dans la config.
