### ISSUE TITLE
Occtax 1.3.0 impossible de terminer une saisie

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#97]
Bonjour,
Suite à l'installation de la version GEONATURE 2.6.2 j'ai été obligé de passer à la version 1.3.0 sur les applications mobiles occtax et sync.

Je viens de tester sur un téléphone, HTC  cette nouvelle version (avec lequel l'application en version occtax 1.1.4 fonctionnait parfaitement) et je n'arrive pas à valider définitivement la saisie quand on arrive sur le dernier écran avec le bouton terminer.
Pour revenir à l'écran d'accueil, je peux utiliser le bouton retour arrière du téléphone.
Les informations du relevé sont quand même conservées et la synchronisation se fait avec enregistrement des données.

Y-a-il des informations nouvelles à saisir indispensables qui expliquerait que le bouton Terminer ne fonctionne pas !

Christian Bièche
Cistude Nature

**Comment by DonovanMaillard** [comment]
Bonjour,

Aucune nouvelle information obligatoire sur la saisie... c'est un soucis qui ne nous était pas encore remonté. 

Avec quelle version d'Android fonctionne votre terminal ?

C'est surprenant qu'avec un retour arrière le relevé soit considéré comme terminé et soit intégré à la synchronisation suivante...

**Comment by christianbieche** [comment]
Android version 6.
C'est peut être pour cela.
C'est un téléphone pour mes tests car sur mon téléphone Honor l'application plante.
Je vais attendre le retour d'autres utilisateur pour voir si cela est vrai sur les autres téléphones.

**Comment by DonovanMaillard** [comment]
à tester avec les versions actuelles d'occtax-mobile et de GeoNature, de nombreuses corrections et évolutions ont été faites sur la gestion des fonds de carte etc. 

Différents soucis ont été réglés au niveau de l'authentification, il reste encore un cas "fragile" pour lequel le code de l'application sera simplifié et amélioré dans la prochaine version.
