### ISSUE TITLE
OccTax 1.3.0 : impossible d'afficher une carte en ligne

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_occtax#98]
Pour faire suite à mon install et mes problèmes de saisie issue #97, je viens d'installer les applications mobiles en version 1.3.0 sur un fairphone, avec android en version 10.
Geonature est en 2.6.2

Je constate que la fonctionnalité d'affichage d'une carte locale et d'une carte en ligne n'est pas disponible sur ces téléphones.

j'ai repris la configuration (fichiers json) du téléphone HTC (issue #97) . J'ai 2 cartes 1 en locale et l'autre en ligne OpenStreetMap.
L'application ne permet pas de "switcher" entre les 2 cartes. Il n'affiche pas le choix et ne propose que la carte en local.  C'est comme s'il conservait l'information précédent d'une carte strictement locale ??
J'ai pourtant effacé les données caches pour être sûr et même en le laissant que le layer en ligne cela ne fonctionne pas.

J'avoue que je ne comprends pas, parce que sur le HTC l'affichage des 2 cartes est possible.

Autre info, je ne vois pas le rapport mais on ne sait jamais, je n'ai pas mis à jour en central sur mon serveur de PROD la version des applications téléphones, ni les fichiers de configuration (table gn_commons.t_mobile_apps)
_Cela posait des problèmes aux utilisateurs ayant un paramétrage différent des autres et la configuration était effacée à chaque fois._

**Comment by DonovanMaillard** [comment]
Bonjour, 

La gestion centralisée des configurations est obligatoire désormais, sync va chercher par défaut les configurations sur le serveur. Mais je pense que c'est une autre question en effet... 

Pour les fonds de carte, ça fonctionne bien avec un terminal HTC mais pas fairphone ? De la même version d'android et avec un même fichier de configuration ? 
Il y a dans les paramètres utilisateurs un paramètre "utiliser les fonds en ligne", il faudrait vérifier si ce paramètre est le même,pour les deux appareils.

**Comment by camillemonchicourt** [comment]
> Bonjour, quelqu'un peut me répondre sur ce sujet ?

Attention, il ne s'agit pas ici d'un SAV.
Nous n'avons pas rencontré les soucis que vous remontez.
Vous pouvez contribuer au projet si vous le souhaitez.
Si vous souhaitez un service garanti d'assistance, vous pouvez aussi contractualiser avec un prestataire.
